### ISSUE TITLE
New Major Release

### ISSUE THREAD

**Issue by drademacher** [Quick/Quick#1033]
Hi. I would like to ask for a new major release. The master branch has some breaking changes, so a minor / patch release would not properly reflect that and can lead to problems in libraries that include `Quick`.

And the changes in the current master branch solve XCode warnings (iOS 8 deprecated) and also move to the stable branch of `Nimble 9` instead of a RC version.

**Comment by ikesyo** [comment]
[v4.0.0](https://github.com/Quick/Quick/releases/tag/v4.0.0) has been released!
