### ISSUE TITLE
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99.

### ISSUE THREAD

**Issue by emadhegab** [Quick/Quick#1034]
Hello .. I just installed Quick via SPM .. and I got the warning 
`The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99.`
although my app target is actually 11.

**Comment by claudiagrilli** [comment]
I have the same. It looks like the package.swift in SPM is old:

let package = Package(
    name: "Quick",
    platforms: [
        .macOS(.v10_10), .iOS(.v8), .tvOS(.v9)
    ],
    products: [
        .library(name: "Quick", targets: ["Quick"]),
    ],
    dependencies: [
        .package(url: "https://github.com/Quick/Nimble.git", from: "9.0.0-rc.1"),
    ],....

and different from the one in the repository.

**Comment by dwhitla** [comment]
This is because this issue wasn't fixed on master until 17 Sept 2020 and the latest tag available for SPM was 3.0.0 on 8 June 2020. All they really need to do is tag 3.0.1 or 3.1.0.

**Comment by emadhegab** [comment]
well this ticket is here for a month and none of the team responded :) so no

**Comment by ikesyo** [comment]
Should be resolve by https://github.com/Quick/Quick/releases/tag/v3.0.1.
