### ISSUE TITLE
Name clash in generated Obj-C headers

### ISSUE THREAD

**Issue by nikolaykasyanov** [Quick/Quick#1038]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

This isn't necessarily a bug in Quick, but I believe it's useful to have it for the record and to avoid more tickets like this as more people try the beta.

### What did you do?

Tried to build my project for testing with Xcode 12.5 beta.

### What did you expect to happen?

I expected it would build as usual.

### What actually happened instead?

Build of one of the test targets failed due to a name clash:

<img width="361" alt="Screen Shot 2021-02-05 at 10 26 31" src="https://user-images.githubusercontent.com/136644/107015012-9fe3d600-679c-11eb-90e9-5623f2673da2.png">
<img width="1321" alt="Screen Shot 2021-02-05 at 10 25 39" src="https://user-images.githubusercontent.com/136644/107014917-7f1b8080-679c-11eb-9da6-a558c708a8e7.png">

Both Quick and another library have `Configuration` class, and they clash when emitted to Obj-C headers.

This looks very much like https://developer.apple.com/forums/thread/658012, even the workaround mentioned there to set `SWIFT_INSTALL_OBJC_HEADER` to `NO` works (well, as long as one doesn't need Quick's Obj-C interface, that is).

### Environment

List the software versions you're using:

 - Quick: *3.0.0*
 - Nimble: *9.0.0*
 - Xcode Version: *12.5 beta (12E5220o)*, new build system
 - Swift Version: *5.4*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: *1.10.1*

### Project that demonstrates the issue

The other library involved is a closed source one, unfortunately.

**Comment by ikesyo** [comment]
We should rename the class to `QCKConfigartion` for Objective-C.

**Comment by nikolaykasyanov** [comment]
Doesn't appear to be happening on Xcode 12.5 RC (12E262).
