### ISSUE TITLE
Xcode warning about Info.plist file included in Sources

### ISSUE THREAD

**Issue by eric2801** [Quick/Quick#1046]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

My Swift package imports Quick & Nimble for its unit tests. Xcode successfully checks out Quick and Nimble, and the MyLibTests target builds and tests succeed. However, Xcode complains with a build warning about Quick.

### What did you expect to happen?

Quick should build without warnings.

### What actually happened instead?

Xcode throws a build warning while building Quick:

`found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target`

`/Users/user/Library/Developer/Xcode/DerivedData/my_lib-epumhbhplsmgovdvdedbzeiuqoka/SourcePackages/checkouts/Quick/Sources/Quick/Info.plist`

### Environment

List the software versions you're using:

 - Quick: *3.1.1*
 - Nimble: *9.0.0*
 - Xcode Version: *12.4 (12D4e)*
 - Swift Version: *Xcode Default*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Swift Package Manager *5.3.0 (swiftpm-???)*

### Project that demonstrates the issue

[MyLib.zip](https://github.com/Quick/Quick/files/5947115/MyLib.zip)

**Comment by ikesyo** [comment]
Looks like this is a side-effect of #1037.

https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package:

> If you declare a Swift tools version of 5.3 or later in your package manifest, you can bundle resources with your source code as Swift packages. For example, Swift packages can contain asset catalogs, storyboards, and so on.

**Comment by ikesyo** [comment]
@eric2801 Could you try #1047's branch?

**Comment by eric2801** [comment]
@ikesyo I updated the Package.swift dependency in the attached MyLib framework to import Quick from the `3.x-swiftpm-plist-in-resources` branch. Unfortunately the build warning is still present, though slightly different:

`/Users/user/Library/Developer/Xcode/DerivedData/MyLib-czutktybbywbmtblldogxljxzywq/SourcePackages/checkouts/quick/Sources/Quick/Resources/Info.plist
`

The Info.plist file is now present in the Resources sub-directory.

**Comment by ikesyo** [comment]
Here is an another attempt: #1048

**Comment by ikesyo** [comment]
Just released [v3.1.2](https://github.com/Quick/Quick/releases/tag/v3.1.2).

**Comment by eric2801** [comment]
Success! I tested your recent commit 456f776 to the `3.x-branch` branch, and Xcode did not emit any build warnings! Thanks!

**Comment by eric2801** [comment]
Confirmed. No build warnings with v3.1.2.
