### ISSUE TITLE
Inherited Generic Class does not create tests

### ISSUE THREAD

**Issue by kofsiwon** [Quick/Quick#1060]
- [ ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I created a new generic class inherited from QuickSpec

```swift
protocol TestArgumentRecognizable {
    associatedtype TestArgumentKey : RawRepresentable, Hashable where TestArgumentKey.RawValue == String
}

class Quickable<ARG_KEY: RawRepresentable & Hashable>: QuickSpec, TestArgumentRecognizable where ARG_KEY.RawValue == String{
typealias TestArgumentKey = ARG_KEY
 ...
}

enum SiwonTestArgumentKey : String{
    case account = "SiwonTestAccount"
    case password = "SiwonTestAccountPwd"
}

class SiwonBaseQuickable : Quickable<SiwonTestArgumentKey>{
 ...
}

class LoginTests: SiwonBaseQuickable {
  ...
  override func spec() {
     ...
  }
}
```

### What did you expect to happen?

LoginTests runts its(tests)

### What actually happened instead?

Test was immediately successed.
There is no tests under LoginTests in Test navigator.
There is no error. 

None Generic Quickable works well (Remove ARG_KEY and TestArgumentRecognizable)

### Environment

List the software versions you're using:

 - Quick: 3.1.2
 - Nimble: 9.0.0
 - Xcode Version: 12.4
 - Swift Version: 5.3

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: 1.10.1
 - Carthage: no
 - Swift Package Manager: no

### Project that demonstrates the issue

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by ikesyo** [comment]
Looks like this is resolved by Xcode 12.5: https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-release-notes

> XCTest now automatically includes specialized subclasses of Swift generic test classes when running tests on macOS 11.3, iOS 14.5, tvOS 14.5, watchOS 7.4, or later OS versions. This allows you to use generics to improve reusability of test classes. (23493200)
