### ISSUE TITLE
Feature request: Mark skipped tests as skipped in Xcode.

### ISSUE THREAD

**Issue by amomchilov** [Quick/Quick#1093]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Compare what happens when skipping a test in native `XCTest`:

```swift
import XCTest

class SampleTest: XCTestCase {
	func test_this_test_should_run() {
		
	}
	
	func test_this_test_is_skipped() throws {
		throw XCTSkip("Skipping this test")
	}
}
```

Versus what happens when you skip a test using Quick (e.g. using `xit`)::

```swift
import Quick

class SampleSpec: QuickSpec {
	override func spec() {
		it("this test should run") {

		}
		xit("this test is skipped") {
			fatalError("This should never be called")
		}
	}
}
```

### What did you expect to happen?

The Xcode sidebar should have shown the test as skipped, as it does when using `XCTest`:

![image](https://user-images.githubusercontent.com/5703449/130830845-60885d34-ac6a-4aaa-9a44-820ee2c0331d.png)

And the skipped line could have been highlighted, as it does when using `XCTest`:

<img width="592" alt="Screen Shot 2021-08-25 at 12 36 52 PM" src="https://user-images.githubusercontent.com/5703449/130830892-56235fb9-6e07-4bd0-a879-5e99a59657a0.png">

### What actually happened instead?

The Quick framework just pretends the test doesn't exist at all, rather than explicitly showing that it *does* exist, but was skipped:

![image](https://user-images.githubusercontent.com/5703449/130830742-7cc69acc-d611-4ded-8110-a71eb5e3d5a2.png)

And no highlights were made that the test was skipped:

<img width="438" alt="Screen Shot 2021-08-25 at 12 38 12 PM" src="https://user-images.githubusercontent.com/5703449/130830783-b69b26ba-f3f6-4516-b821-b508cc9e2923.png">

### Environment

List the software versions you're using:

- Quick: *4.0.0*
- Nimble: *9.2.0*
- Xcode Version: *13.0 (13A5201i)*
- Swift Version: *5.5*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Swift Package Manager *5.5.0*

**Comment by amomchilov** [comment]
I should note that you can't just `throw XCTSkip()` from your Quick spec, because the closures passed to `it`/`context`/`describe`/etc. are not marks `throw`s.

**Comment by ikesyo** [comment]
Related to #770

**Comment by amomchilov** [comment]
I've been playing around with this. There's a private API (`-[XCTestRun recordSkipWithDescription:sourceCodeContext:]`, which seems to have changed from [this version](https://github.com/LeoNatan/Apple-Runtime-Headers/blob/5e50ad05dfd7d7b69fc2e0e685765fc054166b3c/macOS/Developer/Frameworks/XCTest.framework/XCTestRun.h#L43)) that reports these test skips, which I got working in a dummy project. However, I haven't gotten it working in Quick, just yet.

**Comment by amomchilov** [comment]
Update:

I'm able to mark tests as skipped in a Quick Spec!

There seems to be a limitation of the `recordSkip*` private methods. They'll only know the grey `"Test Skipped - msg"` indicator in the source editor for statically defined test (those with the blue `t` logo in the Xcode test navigator sidebar).

Runtime defined tests (those with the purple `rT` logo in the Xcode test navigator sidebar), such as all those which Quick creates, will be marked as skipped in the sidebar, but will *not* show the grey indicator on the source line.

I'll open a PR soon.
