### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#11]
Right now Quick is mainly tested via functional tests. Add a more comprehensive unit test suite, using `XCTestCase`, for the classes and functions in `Core`.

**Comment by modocache** [comment]
This should be made possible thanks to #287.

**Comment by jeffh** [comment]
Hey @modocache,

Is this issue still relevant? What is the required work for this?

**Comment by modocache** [comment]
Not super relevant, but I was planning on tackling it after #287. Theoretically, decoupling Qiuck and XCTest would allow one to test how Quick behaves without mucking up the current test run.

This issue should probably be cleaned up for now, though--not much point in having an issue to "include unit tests once things are more testable." :stuck_out_tongue:
