### ISSUE TITLE
Make `beforeEach` a `throws` method. 

### ISSUE THREAD

**Issue by tahirmt** [Quick/Quick#1122]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I would like to be able to use throwing calls in `beforeEach` 
```
beforeEach {
    let someValue = try XCTUnwrap(someOptional)
    // do something with someValue
}
```

### What did you expect to happen?

Please replace this with what you expected to happen.

### What actually happened instead?

Please replace this with what happened instead.

### Environment

List the software versions you're using:

 - Quick: *4.0.0*
 - Nimble: *9.2.0*
 - Xcode Version: * 13.3 (13E113)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: * Xcode Default* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: *1.11.2* (Use `pod --version` in Terminal)

**Comment by tahirmt** [comment]
@younata any thoughts on this one? I was briefly looking into it but the hurdle I came across was that `beforeEach` et al functions share code with Objective-C and that breaks compatibility if we make the type a `throws` type. Not sure how to tackle that aside from creating objc duplicate functions.

**Comment by younata** [comment]
> @younata any thoughts on this one? I was briefly looking into it but the hurdle I came across was that `beforeEach` et al functions share code with Objective-C and that breaks compatibility if we make the type a `throws` type. Not sure how to tackle that aside from creating objc duplicate functions.

That's... more or less what I'm thinking this will require.
