### ISSUE TITLE
QuickSpec tests are not referenced in Xcode13.3

### ISSUE THREAD

**Issue by nnsnodnb** [Quick/Quick#1123]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

`QuickSpec` tests were not eligible for execution in Xcode 13.3.

<img width="550" src="https://user-images.githubusercontent.com/9856514/158536272-f530bbad-3d73-4461-848e-40bcb675f758.png">

All tests are correctly recognized when installed with the Swift Package Manager.
But when installed with CocoaPods, all tests are ignored.

### What did you expect to happen?

Tests are executed.

### What actually happened instead?

All tests were ignored.

### Environment

List the software versions you're using:

 - Quick: *4.0.0*
 - Nimble: *?.?.?* not included
 - Xcode Version: *13.3 (13E113)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *5.6* use `Xcode Default` (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: *1.11.3* (Use `pod --version` in Terminal)
 - Carthage: *?.?* (Use `carthage version` in Terminal) not included
 - Swift Package Manager *5.6.0 (swiftpm-???)* (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

[Sample.zip](https://github.com/Quick/Quick/files/8259688/Sample.zip)

**Comment by mimibuduo123** [comment]
Xcode13.3 testInvocations -> testBundleWillStart

**Comment by mimibuduo123** [comment]
< Xcode13.3 testBundleWillStart < testInvocations

**Comment by paweldudek** [comment]
We did a quick & dirty fix this way: https://github.com/toptal/Quick/commit/8c332c41770d87e62718531ed0951763c58f2345

But I also don't know what are the ramifications of building examples right before they're run (this also is slightly inefficient b/c the code to build examples is run before _every_ test - there's an internal check that prevents from duplicating tests for each class _but_ the check needs to be run for every test - not the best complexity here 😕). 

Would be nice for someone from Core team to chime in with direction, I can work out the details & submit a PR 🙌🏻

**Comment by ignotusverum** [comment]
Adding `Execute in parallel(if possible)` flag in test scheme options - for unknown reason fixes issue with execution 

<img width="368" alt="Screen Shot 2022-03-22 at 5 43 58 PM" src="https://user-images.githubusercontent.com/5115258/159581275-477016e4-be55-4cf4-9b2c-c086876c03c8.png">

**Comment by jesus-verse** [comment]
the @ignotusverum solution worked for me as well

**Comment by BobCatC** [comment]
Created a [PR with a fix](https://github.com/Quick/Quick/pull/1128) so reviewers are welcome 😄
There is also a question for @ikesyo , answer on which might help simplify the solution

**Comment by rbhuvizeli** [comment]
What do you think, when [it'll](https://github.com/Quick/Quick/pull/1128) be merged?
The Danger check failed. What should be done to merge that PR?

**Comment by tropicalappspoland** [comment]
Come on, this is critical issue :(

**Comment by danielbarela** [comment]
Why has this not been merged in?  We are unable to run tests in 13.3

**Comment by jessesquires** [comment]
> About Danger check failure: looks like it's a problem of access to this repo (which I don't have of course). There is some text like "forbidden, 403 access error when posting a comment to issue (pr)". If someone has any idea how to fix this check failure - write it here or in PR.

This is because Danger is run via GitHub Actions and your PR is a fork. Forks have different permissions/restrictions.

This is terrible design and a known flaw with GH Actions. 🤷🏼

**Comment by jessesquires** [comment]
Fixed in #1129

**Comment by BA00001** [comment]
what's the exact solution for this Xcode 13.3+ test with no progress on Code Coverage?

**Comment by BA00001** [comment]
> what's the exact solution for this Xcode 13.3+ test with no progress on Code Coverage?

@jessesquires so not yet released, am I right, it's in under development?

**Comment by jessesquires** [comment]
## Update

Hey all, as noted above, this fix has been merged. It will be included in the [v5.0.0 release](https://github.com/Quick/Quick/milestone/7) when that is ready. I'm working on getting that wrapped up as soon as I can.

In the meantime, you can point your `Podfile` to the commit on `main` that includes the fix, a0a5fc857cea079fbe973e4faa80b6ceaf17bd46.

```ruby
pod 'Quick', :git => 'https://github.com/Quick/Quick', :commit => 'a0a5fc8'
```

I recommend "Watching Releases" for this repo to be notified when `v5.0` is out.

<img width="321" alt="Screen Shot 2022-04-14 at 10 15 20 AM" src="https://user-images.githubusercontent.com/2301114/163440186-d0e2391b-8d8f-4d0d-a2ea-03ebcea07f42.png">

Once `v5.0` is released, you can revert your `Podfile` to `pod 'Quick', '~> 5.0'`.

**Comment by jessesquires** [comment]
https://github.com/Quick/Quick/releases/tag/v5.0.0

v5 is released. not yet in cocoapods but it will be soon.

in the meantime, you can now point your podfile to the `v5.0.0` tag.

**Comment by jessesquires** [comment]
Quick 5.0 is now in CocoaPods. Please update.
