### ISSUE TITLE
Tests cannot fail when running on Xcode 13.3

### ISSUE THREAD

**Issue by Spiritofthecore** [Quick/Quick#1131]
- [ ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Run any tests with Quick

### What did you expect to happen?

The test can fail or success.

### What actually happened instead?

The test always success.

### Environment

List the software versions you're using:

 - Quick: *3.0.1*
 - Nimble: *9.2.1*
 - Xcode Version: *13.3 (13E113)* 
 - Swift Version: *5.6* 

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Carthage: *0.38.0* 

### Project that demonstrates the issue

You can reproduce the issue on Xcode 13.3

**Comment by fegoulart** [comment]
Is your Mac M1 ?
