### ISSUE TITLE
Update Nimble dependency to v11

### ISSUE THREAD

**Issue by jessesquires** [Quick/Quick#1135]
~~Whenever this gets done: https://github.com/Quick/Nimble/milestone/11~~

**EDIT:**

Nimble v10 is out: https://github.com/Quick/Nimble/releases/tag/v10.0.0

However, I think it makes more sense to release Quick v6 with Nimble v11 — both of those releases are dropping old Xcodes, Swift versions, and OS versions.

Nimble v11 milestone:
https://github.com/Quick/Nimble/milestone/12

**Comment by jessesquires** [comment]
@younata Let me know what you think here.

I think it makes more sense to ship Quick v6 and Nimble v11 together — but I'm open to other possibilities.

**Comment by younata** [comment]
@jessesquires I agree with you on shipping Quick v6 and Nimble v11 together. That makes a lot of sense.
