### ISSUE TITLE
Xcode gutter diamond missing since upgrading to XCode 14

### ISSUE THREAD

**Issue by esilverberg** [Quick/Quick#1170]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
Upgraded from Xcode 13 to Xcode 14

### What did you expect to happen?
Gutter diamonds used to appear at the very top of the file, and I could use `fit` or `fdescribe` to focus my tests. I would also see failures on the line they occurred.

### What actually happened instead?
The gutter diamond is missing and the line that fails is no longer highlighted in red. Was hoping someone else experienced this issue and has a suggested resolution.

### Environment

 - Quick: 5.0.1
 - Nimble: 10.0.0
 - Xcode Version: Version 14.0 (14A309)
 - Swift Version: Xcode default:
 - CocoaPods: 1.11.2
 - Swift Package Manager 5.7.0

**Comment by younata** [comment]
The test gems aren't even showing up for XCTest-based tests on 14.0.

I'll file a report with Apple, and maybe this'll get fixed in a future beta of 14.1?

**Comment by esilverberg** [comment]
Thank you! Great we can close this report.
