### ISSUE TITLE
How to get rid of MainActor warning on all "it" tests?

### ISSUE THREAD

**Issue by Kalzem** [Quick/Quick#1180]
### What did you do?

Using Quick v6, I had to add a lot of @MainActor to it("...") tests such as

```swift
class TutorialManagerSpec: QuickSpec {
    override func spec() {
        describe("foo") {
            it("can do bar") { @MainActor in // <- Xcode Warning
                // Some test
            }
        }
    }
}
```

That's because of the architecture of the project which is based on singletons which must run on the main thread at all costs.

This generates an xcode warning for every test (so there are hundreds and hundreds of warnings).

> Converting function value of type '@ MainActor () -> ()' to '() throws -> Void' loses global actor 'MainActor'

Is there a specific syntax to get rid of this warning?

### Environment

List the software versions you're using:

 - Quick: 6.0.0
 - Nimble: 11.1.0
 - Xcode Version: 14.0.1
 - Swift Version: The one of 14.0.1
 - CocoaPods: 1.11.3

**Comment by younata** [comment]
That's odd. You shouldn't be getting those warnings with Quick 6. It might be some weird caching behavior? I'll look into it some more later.

---

Regardless, to improve your developer experience: Since you're compiling with swift 5.7 (Xcode 14), you can annotate the entire class as `@MainActor`, and your tests will all run on the main actor without needing tag each individual test with `@MainActor`.

That is, instead of writing the following:

```swift
class MySpec: QuickSpec {
    override func spec() {
        it("") { @MainActor in
            expect(Thread.isMainThread).to(beTrue())
        }
    }
}
```

You can instead write:

```swift
@MainActor
class MySpec: QuickSpec {
    override func spec() {
        it("runs on the main actor") {
            expect(Thread.isMainThread).to(beTrue())
        }
    }
}
```

**Comment by slava-semeniuk-ek** [comment]
It seems this doesn't work, since originally `func spec()` is not MainActor at `QuickSpec` class
```swift
@MainActor
class MySpec: QuickSpec {
    override func spec() {
        it("runs on the main actor") {
            expect(Thread.isMainThread).to(beTrue())
        }
    }
}
```

**Comment by bvirlet** [comment]
Hello, 

Is there a recommend solution for this, or should `func spec()` be MainActor in `QuickSpec`? 

Thank you!

**Comment by younata** [comment]
This should be resolved as of Quick 7. Please re-open if it isn't.
