### ISSUE TITLE
Testing with `Behavior<Context>` does not seem to support Swift concurrency

### ISSUE THREAD

**Issue by MariusDeReus** [Quick/Quick#1195]
- [x ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

We raised the deployment target of our big macOS project and started using Swift concurrency. We updated Quick and Nimble to use the latest (below mentioned) Quick and Nimble versions. 
This caused a lot of build errors of our unit test targets with thousands of unit tests. Luckily most of them were pretty easy to fix by adorning the involved QuickSpec subclasses as `@MainActor`.
However we can't fix the places where we use `itBehavesLike` with a `Behaviour<>` subclass. When one of the objects used in the Behavior subclass is a MainActor object (such as view controllers or other UI elements). 
Example:
```
final class MyTestBehavior: Behavior<MyContext> {
    override class func spec(_ aContext: @escaping () -> MyContext) {
        var sut: MyViewControllerSubclass!
        beforeEach {
             sut = MyViewControllerSubclass()   // error: Expression is 'async' but is not marked with 'await'
             sut = await NSView().   // error: Main actor-isolated property 'view' can not be mutated from a non-isolated context
        }
        it("etc") {
          expect(sut.property) == aContext().expected  // error: Main actor-isolated property 'property' can not be referenced from a non-isolated autoclosure
        }
    }
}
```

### What did you expect to happen?

Expected to be able to make this somehow compile and work

### What actually happened instead?

Was bombarded with compiler warnings. Tried several ways to fix:
- add 'await' statements -> solved the Expression is 'async' but is not marked with 'await'" error, but introduces "Main actor-isolated property 'view' can not be mutated from a non-isolated context" instead.
- Mark `MyTestBehavior` as @MainActor -> no effect
- Try to wrap the content of the function body in `await MainActor.run { <body content> }`. -> new error: "'async' call in a function that does not support concurrency"

Swift Concurrency is still pretty new to us, so we might have missed something, but I'm pretty sure that the framework needs some change to make this work. I suppose that to make this work the `spec` func needs to be async, or its closure argument needs to be non isolated or main actor annotated. But we cannot do that in our subclass because then it is not subclassing its super class' spec func any more.

### Environment

List the software versions you're using:

 - Quick: 6.1.0
 - Nimble: 11.2.1
 - Xcode Version: 14.2
 - Swift Version:  `Xcode Default`

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: 1.11.2

**Comment by younata** [comment]
I'm so sorry for this confusion. Annotating the class definition with `@MainActor` doesn't work for this. I wish I had a better solution. I'm currently working to redo how async specs work in Quick, which will restore the older, v5 behavior. This is [explained in (slightly) more detail on this PR](https://github.com/Quick/Quick/pull/1192).

In the meantime, every `beforeEach`, `afterEach` or `it` closure used in a `Behavior` will need to manually forced to run on the main actor. e.g.:

```swift
final class MyTestBehavior: Behavior<MyContext> {
    override class func spec(_ aContext: @escaping () -> MyContext) {
        var sut: MyViewControllerSubclass!
        beforeEach { @MainActor in
             sut = MyViewControllerSubclass()
             sut = await NSView()
        }
        it("etc") { @MainActor in
          expect(sut.property) == aContext().expected
        }
    }
}
```

Hope that helps!

**Comment by MariusDeReus** [comment]
hi @younata no worries, and thank you so much for your response. This gave me a good way out ;-)
