### ISSUE TITLE
`@MainActor` for QuickSpec subclass doesn't work when installing Quick via SPM

### ISSUE THREAD

**Issue by takehilo** [Quick/Quick#1197]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Installing Quick via SPM, `@MainActor` for QuickSpec subclass doesn't work (via CocoaPods it works).
All tests run on non-main thread.

```swift
@MainActor
final class SampleSpec: QuickSpec {
    override func spec() {
        it("test") {
            expect(Thread.isMainThread).to(beTrue())  // got <false>
        }
    }
}
```

`@MainActor` for `it`'s closure works expectedly.

```swift
final class SampleSpec: QuickSpec {
    override func spec() {
        it("test") { @MainActor in
            expect(Thread.isMainThread).to(beTrue())  // pass
        }
    }
}
```

### What did you expect to happen?

All tests run on main thread.

### Environment

List the software versions you're using:

 - Quick: *6.1.0*
 - Nimble: *11.2.1*
 - Xcode Version: *14.1 (14B47b)*
 - Swift Version: *5.7.1*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Swift Package Manager *5.7.1*

**Comment by younata** [comment]
This is a known issue. I don't have a good solution for it. I'm sorry.

**Comment by erudel** [comment]
I'm trying to find more information about this issue and could not find anything. Are there discussions or open bugs (in this project or another) elaborating why this doesn't work in SPM?

**Comment by younata** [comment]
@erudel 

Everything I'm seeing indicates that when [SE-0316](https://github.com/apple/swift-evolution/blob/main/proposals/0316-global-actors.md#using-global-actors-on-a-type) (which defines global actors, such as the main actor) gives the following criteria for when a class can be annotated with a global actor:

> A class can only be annotated with a global actor if it has no superclass, the superclass is annotated with the same global actor, or the superclass is NSObject. A subclass of a global-actor-annotated class must be isolated to the same global actor.

What it actually means is that, you can annotate a subclass with a global actor, but unless the above criteria is met, then only methods on that subclass will run on the global actor.

Additionally, I think the "superclass is NSObject" criteria is also misleading, and on Apple platforms means "the superclass is implemented in Objective-C".

My evidence for this is based on the fact that the SPM version of Quick has QuickSpec.spec defined in Swift, but the Cocoapods version of Quick has QuickSpec.spec defined in Objective-C. The following sample code should also demonstrate the issue. (which I wrote off the top of my head and have not verified if it compiles - I imagine there's weird completionHandler -> async in subclass thing that's probably invalid with the compiler. Regardless, you get the idea, I hope):

```objective-c
@interface ObjcBaseClass: NSObject
- (void)someMethod:(void (^)(void))completionHandler;
@end

@implementation ObjcBaseClass
- (void)someMethod:(void (^)(void))completionHandler { completionHandler(); }
@end
```

```swift
class SwiftBaseClass {
    func someMethod() async {}
}

@MainActor class SwiftSubClass: SwiftBaseClass {
    override func someMethod() async {
        assert(NSThread.isMainThread)  // this assert will almost certainly fail.
    }
}

@MainActor class ObjcSubClass: ObjcBaseClass {
    override func someMethod() {
        assert(NSThread.isMainThread)  // this assert will never fail.
    }
}
```

I have not filed any feedbacks/swift bugs based off this observation. I assume that the cocoapods version of Quick is relying on undefined behavior, so a feedback wouldn't be all that helpful anyway.

**Comment by erudel** [comment]
Thank you very much for the detailed explanation and the link @younata , I wasn't aware of the difference in the implementation used between SPM and Cocoapods but now it makes perfect sense.
