### ISSUE TITLE
Would it be possible to hide the new/old test naming behind a feature flag?

### ISSUE THREAD

**Issue by stonko1994** [Quick/Quick#1208]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

When testing Quick 7 betas mainly for the async/await functionality, we figured out that there is a new strategy for creating test names. Ref https://github.com/Quick/Quick/pull/1207

> There's a mild chance that this will break any scripts relying on mangled test names. I'm ok with that so long as we call it out in the release notes.

Even though you mention that you are fine with the breaking change, would it be possible to re-enable the old naming behind a feature flag?

**Why do we rely on the test names?**
We do have a huge collection of system tests (end-to-end tests), from which we do save the results to a database. As an identifier, we take the hash of the test name (as this is the only unique thing for those tests ATM).

We need this historical test data in order to automatically detect flakiness and regressions. (_One could say that there should not be any flakiness and yes we are working on it but we are not there yet - video playback served through a network is involved there_).

### What did you expect to happen?

Ideally, there would be a feature flag that re-enables the old test naming scheme.

Alternatively, it could be a feature to define the strategy of how the final test name should be computed.

### What actually happened instead?

`-`

### Environment

List the software versions you're using:

 - Quick: `7.0.0-beta.2`
 - Nimble: `-`
 - Xcode Version: `13.4`
 - Swift Version: `5.8`

**Comment by younata** [comment]
I really appreciate the feedback here!

Sure, I'll figure out some mechanism to switch on/off this behavior.

**Comment by younata** [comment]
Hey @stonko1994! https://github.com/Quick/Quick/pull/1211 lets you set an environment variable to switch back to the legacy test selector names. Does this work for your use case?

**Comment by stonko1994** [comment]
Awesome, thank you 🙌. I quickly tested the PR in our project and works as expected. The ENV variable approach works for us 🙂
