### ISSUE TITLE
XCTestAssertions do not work within a QuickSpec written in Objective-C

### ISSUE THREAD

**Issue by krzysztofzablocki** [Quick/Quick#121]
When using XCTest assertions or 3rd Party libraries(OCMock/Mockito), failures are not handled properly on QuickSpec.
the proper method is getting called 
````
- (void)recordFailureWithDescription:(NSString *)description inFile:(NSString *)filePath atLine:(NSUInteger)lineNumber expected:(BOOL)expected;
````
but Xcode still doesn't show test as failed.

Running through debugger I noticed that when running through nimble expectation example is set correctly, but if run from any other lib or XCTest we end up with empty example, might be something related to that?

To reproduce you could just add 
````
XCTFail(@"Fail!");
````

**Comment by modocache** [comment]
Now that #304 has been merged, I think this issue is the biggest blocker for [Quick v1.0.0](https://github.com/Quick/Quick/milestones/v1.0.0) at the moment. I'd love to get to the bottom of this...!

**Comment by orta** [comment]
For additional info, this in Specta fails correctly:

```
  it(@"Fails via XCTFail", ^{
    XCTFail(@"fail");
  });
```

**Comment by modocache** [comment]
I believe I've isolated the difference between how Quick and Specta behave to [this line](https://github.com/specta/specta/blob/42b8e0d8e28994abbf2012c76d980668b575a10d/Specta/Specta/SPTSpec.m#L201), which routes the failure recording to the current spec's test run. Commenting out that line exhibits the same behavior as Quick.

We may need to store a global pointing to the current spec being run, like Specta does. Still looking into it...
