### ISSUE TITLE
AsyncSpecs not run in bulk on Quick 7 (but run individuately)

### ISSUE THREAD

**Issue by isaac-weisberg** [Quick/Quick#1226]
- [ ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I have some tests in Quick 5. They had this pattern where there was 1 single subclass of QuickSpec called `BaseSpec`, and then every other Spec is a subclass of this `BaseSpec`.

Now, I have upgraded my tests to Quick 7 - thanks for thorough migration guide in the release notes. 

It's all cool, my tests used `async`/`await`, so:
- I made `BaseSpec` derive from `AsyncSpec`. 
- My superclass `spec` method I had, I made `class`. 
- Derived classes used to override this method - made them `class override`
- My members that were stored in the `BaseClass`, I made them static (just a couple of DI things).

And that's it, the project compiles.

However, now, when I run action "Test" (Cmd+U), none of my async test are actually run. 
They don't light up as green in Xcode summary, the result is just empty. 
Same outcome happens if I click "Run all tests on a target" in the inspector on the left. 

In these cases, nor `spec`, nor inner `describe` closures are run.

However: 
- if in project inspector, I tell Xcode to run a particular `Spec`, a particular suite of tests, **then everything works**!
- if I make my tests that use `BaseSpec` class to directly derive from `AsyncSpec`, then it **still doesn't work**!

What happened? How comes my AsyncSpecs are not run in bulk?

### Environment

List the software versions you're using:

 - Quick: 7.0.2
 - Nimble: 12.0.1
 - Xcode Version: 14.1
 - Swift Version: Xcode Default
 - CocoaPods: 1.11.3

**Comment by isaac-weisberg** [comment]
Aaaand of course, once I have created an empty project that would be able to reproduce this, then it just works.

**Comment by isaac-weisberg** [comment]
I launched this code on coworkers machine and it just works.

I love Xcode.

**Comment by younata** [comment]
My apologies for the frustration. I assume that clearing derived data fixed the issue?

**Comment by isaac-weisberg** [comment]
Nah, I cleaned derived data 6 times, this didn't influence anything...

I fixed it by going to the bathroom...

After all, if AsyncSpec tests were not discovered, it's not supposed to be a bug with Quick. Rather, I should've asked this question on the Xcode forums... Like, how comes, an XCTestCase is just not discovered...

**Comment by isaac-weisberg** [comment]
Thank you for your support...

**Comment by younata** [comment]
> After all, if AsyncSpec tests were not discovered, it's not supposed to be a bug with Quick.

Not necessarily. We could have a bug in the code which generating the tests XCTest runs. I appreciate the bug report here.

> Thank you for your support...

Again, I'm really sorry for the issues you dealt with. I'm happy it's working now, but still.
