### ISSUE TITLE
Make `xitBehavesLike` with a `String` as a name publicly available (sync and async)

### ISSUE THREAD

**Issue by stonko1994** [Quick/Quick#1227]
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I was trying to quickly `xit` a `itBehavesLike` function which uses the `itBehavesLike(_ name: String)` signature. But it turned out that this method overload does not exist.

### What did you expect to happen?

That the `xitBehavesLike(_ name: String)` is available on the `SyncDSLUser` and `AsyncDSLUser`.

### Environment

List the software versions you're using:

 - Quick: *7.0.1*
 - Nimble: *N/A*
 - Xcode Version: *N/A*
 - Swift Version: *N/A*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: *N/A*
 - Carthage: *N/A*
 - Swift Package Manager *N/A*

**Comment by younata** [comment]
Thanks for pointing out the oversight!

`itBehavesLike(_ name: String)` is not available to `AsyncDSLUser`. Personally, I'd like to remove the String-based `itBehavesLike` as I that using `itBehavesLike` with a `Behavior` is a better pattern (compile-time enforcement of the name, type-safety for the values passed to the context). This is why I decided to not create an `itBehavesLike(_ name: String)` for Async specs. That said, I don't yet have a plan to remove `itBehavesLike(_ name: String)`. Any plan to do that will need to provide a solution for Objective-C users, where `Behavior` is unavailable there.
