### ISSUE TITLE
Mutation of captured var 'ocean' in concurrently-executing code

### ISSUE THREAD

**Issue by lukeistutoring** [Quick/Quick#1237]
- [ x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Created `AsynchronousSpec` according to example in https://github.com/Quick/Quick/discussions/1217

### What did you expect to happen?

Test to compile and run

### What actually happened instead?

Test fails to compile with `Mutation of captured var 'ocean' in concurrently-executing code`

### Environment

List the software versions you're using:

 - Quick: *7.2.0*
 - Nimble: *12.2.0*
 - Xcode Version: *14.3.1 (14E300c)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *Xcode Default* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: *1.21.1* (Use `pod --version` in Terminal)
 - Carthage: *?.?* (Use `carthage version` in Terminal)
 - Swift Package Manager *?.?.? (swiftpm-???)* (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

```
import Quick
import Nimble

class AsynchronousSpec: AsyncSpec {
    override class func spec() {
        it("runs the test in an async context") {
            var ocean: [String] = []
            DispatchQueue.main.async {
                ocean.append("dolphins")
                ocean.append("whales")
            }
            await expect(ocean).toEventually(contain("dolphins", "whales"))
        }
    }
}
```

**Comment by younata** [comment]
Yep. That's correct. The documentation will have to be updated.
