### ISSUE TITLE
Add visionOS support

### ISSUE THREAD

**Issue by stonko1994** [Quick/Quick#1246]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Trying to run unit tests on visionOS.

### What did you expect to happen?

Build succeeded and starting the tests.

### What actually happened instead?

The build does not succeed due to the missing support for visionOS from Quick (and `Nimble` and `CwlPreconditionTesting`).

### Environment

List the software versions you're using:

 - Quick: `N/A`
 - Nimble: `N/A`
 - Xcode Version: *15.1 beta* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *5.9* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: *1.13.0* (Use `pod --version` in Terminal)
 - Carthage: `N/A` (Use `carthage version` in Terminal)
 - Swift Package Manager `N/A` (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

- `N/A`

The project should be [short, self-contained, and correct example](http://sscce.org/).

---

I was playing around a bit with this already in a fork, and it seems to be easily possible to enable visionOS support. The question is if Quick will become a multiplatform target similar to Nimble or if new targets for `visionOS` and tests should be created.

Once the dependencies PR are merged I would be open for contributing our fork back.
- https://github.com/Quick/Nimble/pull/1083
- https://github.com/mattgallagher/CwlPreconditionTesting/pull/31

**Comment by younata** [comment]
> The question is if Quick will become a multiplatform target similar to Nimble.

[It will](https://github.com/Quick/Quick/pull/1222), I just haven't merged that PR yet.

**Comment by younata** [comment]
Sorry about that delay. I needed to find time to update that PR, which I was able to find today.

BTW, I really appreciate the work you're putting forth to support visionOS for Quick and Nimble!
