### ISSUE TITLE
When testing a class with `@MainActor` annotation the `QuickSpec` doesn't work

### ISSUE THREAD

**Issue by tahirmt** [Quick/Quick#1255]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I'm trying to test a class marked with `@MainActor` but in the spec file that subclasses `QuickSpec` all the `it` blocks are not actor isolated so they throw an error. If I mark the whole spec class with `@MainActor` then the `it` and `beforeEach` etc are still not actor isolated. If I mark each of the closures with `@MainActor in` then I get a warning `Converting function value of type '@MainActor () throws -> Void' to '() throws -> Void' loses global actor 'MainActor'`. 

While the `QuickSepc` is supposed to run on the main thread, this causes a huge problem with testing `@MainActor` classes.

### What did you expect to happen?

The `QuickSpec` is already marked with `@MainActor` so I don't have to do anything.

### What actually happened instead?

There's tons of warnings/errors as outlined above

### Environment

List the software versions you're using:

 - Quick: *7.3.0*
 - Nimble: *13.0.0*
 - Xcode Version: *15.0.1 (15A507)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *Xcode Default* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Swift Package Manager *5.9.0* (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by desusai7** [comment]
@younata, we do not even need to use `@MainActor` when we are subclassing `QuickSpec` right ?

As it always run on Main thread in version `7`

**Comment by younata** [comment]
My earlier comment did not age well.

Yesterday, I merged https://github.com/Quick/Quick/pull/1289, which does precisely what you're asking for.
