### ISSUE TITLE
Sometimes TestState crashes for AsyncSpec

### ISSUE THREAD

**Issue by tahirmt** [Quick/Quick#1258]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Use `@TestState` inside of `AsyncSpec`

### What did you expect to happen?

`TestState` works es expected

### What actually happened instead?

There is a crash that doesn't always happen but sometimes running full suite `AsyncSpec.current` line crashes with `Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`

### Environment

List the software versions you're using:

 - Quick: *7.3.0*
 - Nimble: *13.0.0*
 - Xcode Version: *15.1* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *Xcode Default* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: *?.?.?* (Use `pod --version` in Terminal)
 - Carthage: *?.?* (Use `carthage version` in Terminal)
 - Swift Package Manager *5.9.0 (swiftpm-???)* (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

I don't have a sample project (yet) but I will update it if I can reproduce it in isolation.

**Comment by younata** [comment]
I have also noticed this in my own usage. I'm still investigating why. Thank you for creating an issue documenting the behavior!
