### ISSUE TITLE
Release 7.3.1 is not available through cocoapods source repo/CDN

### ISSUE THREAD

**Issue by stonko1994** [Quick/Quick#1262]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Trying to update to `7.3.1` using Cocoapods

### What did you expect to happen?

`-`

### What actually happened instead?

`pod install --repo-update` results in an error stating that version `7.3.1` of Quick does not exist.
```
[!] CocoaPods could not find compatible versions for pod "Quick":
  In Podfile:
    Quick (~> 7.3.1)

None of your spec sources contain a spec satisfying the dependency: `Quick (~> 7.3.1)`.
```

### Environment

List the software versions you're using:

 - Quick: `N/A`
 - Nimble: `N/A`
 - Xcode Version: `N/A` (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: `N/A` (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: *1.13.0* (Use `pod --version` in Terminal)
 - Carthage: `N/A` (Use `carthage version` in Terminal)
 - Swift Package Manager `N/A` (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by younata** [comment]
It's because cocoapods doesn't support visionOS yet. https://github.com/mattgallagher/CwlPreconditionTesting/issues/36

**Comment by younata** [comment]
Whoops. Thanks for pointing out that mistake.
