### ISSUE TITLE
quick/nimble test case grouping question

### ISSUE THREAD

**Issue by kickbell** [Quick/Quick#1282]
hello. I have a question. 

I know that while using Quick, I can run BDD and group test cases with describe-context-it. 

That is, I'm expecting Xcode's Test Navigator to look something like the image below 

![image](https://github.com/Quick/Quick/assets/85085822/efada929-16fb-4eef-a95f-4e561ed83bae)

However, it's not displaying hierarchically like the image below. What am I doing wrong? Or is this normal behavior? 

![image](https://github.com/Quick/Quick/assets/85085822/c82d4870-fa9f-4c55-b83b-e4bd0dc58233)

### Environment

List the software versions you're using:

 - Quick: 7.0.0
 - Nimble: 10.0.0
 - Xcode Version: 15.3
 - Swift Version: 5+

**Comment by younata** [comment]
You're not doing anything wrong. Your second image (showing everything in a list) is the normal, expected behavior.

Though, now that I'm reminded that you can group tests like your first image, this might change in a future release.

**Comment by kickbell** [comment]
Ah, I see, thanks for the quick reply. 

Have a nice day~!
