### ISSUE TITLE
Optional Type must be unwrapped Error when using Quick SPM 7.5.0

### ISSUE THREAD

**Issue by gaurav-Lilly** [Quick/Quick#1290]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Replaced Quick CocoaPod with SPM Quick 7.5.0

### What did you expect to happen?

Unit Tests to pass and work as earlier (just how they use to work with Cocoapods)

### What actually happened instead?

Started getting build error in all the test case classes.Attached is the screenshot.All the test case use to pass and worked perfectly when i was using cocoapod for Quick and Nimble. All these errors start appearing once i removed the pods and installed the SPM package for the both. I even tried fixing the errors as suggested using optional chaining, but then it was throwing "cannot call functions on optional instance."

Even tried making func as class func, but still build error.

### Environment

List the software versions you're using:

 - Quick: *7.5.0*
 - Nimble: *13.1.2*
 - Xcode Version: *15.4* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *5.10.0* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Swift Package Manager *5.10.0" 
<img width="1381" alt="Screenshot 2024-07-02 at 3 46 14 AM" src="https://github.com/Quick/Quick/assets/56674079/1839f345-4e7f-40cf-b576-530278b8d03d">
(swiftpm-???)* (Use `swift build --version` in Terminal)

**Comment by gaurav-Lilly** [comment]
@younata : Any thoughts ?

**Comment by younata** [comment]
I've never seen this before.

Not really related to your issue, but your pattern of creating an instance of the test class to then call test methods on in Nimble is nonstandard, and, I assume, a holdover from before you adopted Quick? I would advise you to prioritize migrating away from that.

I wonder if that fact that [QuickSpec-init](https://github.com/Quick/Quick/blob/main/Sources/QuickObjCRuntime/include/QuickSpecBase.h) in the SPM distribution's objective-c runtime is not tagged with NS_ASSUME_NONNULL begin/end might be contributing to this? You'd be getting back a type of `PutUserEventTaskTests!` (note the force-unwrap) thanks to that. But that same force-unwrap should be preventing this issue.

As a stop-gap, you can try out the `add_nullability_annotations` branch, which _might_ address your issue? I have a [PR](https://github.com/Quick/Quick/pull/1291) up for that, and I'll be releasing a version of Quick with that sometime, assuming it works for you.
