### ISSUE TITLE
Provide a way to define a setup for a context

### ISSUE THREAD

**Issue by rbeeger** [Quick/Quick#138]
When I define a context in a spec like context("after adding 1") I want to change the test object so that it matches that context.
I cannot do it as the first thing inside the context-closure because it gets executed as soon as Quick analyzes the spec and the change then actually happens before any tests in the spec are run.
I cannot do it with beforeSuite() because that also gets executed way to early and not at the time when the context is entered.
My workaround now is to do the setup in the first it, but that's not the place where it should be.
I think there should be a beforeAll that is run before any it of the context.

**Comment by paulz** [comment]
we have a case for Application tests, or sometimes we call `AppSpecs` where setup involves more expensive operations. here is how we define `beforeAll` and `afterAll`

```
@testable import Quick

public func beforeAll(_ closure: @escaping BeforeExampleClosure) {
    var firstRun = true
    beforeEach {
        if firstRun {
            closure()
            firstRun = false
        }
    }
}
public func afterAll(_ closure: @escaping BeforeExampleClosure) {
    let group = World.sharedWorld.currentExampleGroup!
    var examplesCount = 0
    afterEach {
        examplesCount += 1
        if examplesCount == group.examples.count {
            closure()
        }
    }
}
```
