### ISSUE TITLE
Quick does not work on physical devices

### ISSUE THREAD

**Issue by jbosse** [Quick/Quick#140]
Well, the codesign issue of #79 is resolved but it seems to have made room for a new problem.

I am getting the following even when starting with an new iOS project I created to make sure it wasn't something else.

> Ld /Users/jbosse/Library/Developer/Xcode/DerivedData/Sample-bvrevcrvgjvtuigbogtgeilpdfcl/Build/Intermediates/Quick.build/Debug-iphoneos/Quick-iOS.build/Objects-normal/armv7/Quick normal armv7
>     cd /Users/jbosse/Dev/Sample/Vendor/Quick/Quick
>     export IPHONEOS_DEPLOYMENT_TARGET=8.0
>     export PATH="/Applications/Xcode6-Beta7.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode6-Beta7.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
>     /Applications/Xcode6-Beta7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -dynamiclib -isysroot /Applications/Xcode6-Beta7.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk -L/Users/jbosse/Library/Developer/Xcode/DerivedData/Sample-bvrevcrvgjvtuigbogtgeilpdfcl/Build/Products/Debug-iphoneos -F/Users/jbosse/Library/Developer/Xcode/DerivedData/Sample-bvrevcrvgjvtuigbogtgeilpdfcl/Build/Products/Debug-iphoneos -F/Applications/Xcode6-Beta7.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk/Developer/Library/Frameworks -F/Applications/Xcode6-Beta7.app/Contents/Developer/Library/Frameworks -F/Applications/Xcode6-Beta7.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -filelist /Users/jbosse/Library/Developer/Xcode/DerivedData/Sample-bvrevcrvgjvtuigbogtgeilpdfcl/Build/Intermediates/Quick.build/Debug-iphoneos/Quick-iOS.build/Objects-normal/armv7/Quick.LinkFileList -install_name @rpath/Quick.framework/Quick -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -lswiftCore -L/Applications/Xcode6-Beta7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/jbosse/Library/Developer/Xcode/DerivedData/Sample-bvrevcrvgjvtuigbogtgeilpdfcl/Build/Intermediates/Quick.build/Debug-iphoneos/Quick-iOS.build/Objects-normal/armv7/Quick.swiftmodule -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=8.0 -framework XCTest -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/jbosse/Library/Developer/Xcode/DerivedData/Sample-bvrevcrvgjvtuigbogtgeilpdfcl/Build/Intermediates/Quick.build/Debug-iphoneos/Quick-iOS.build/Objects-normal/armv7/Quick_dependency_info.dat -o /Users/jbosse/Library/Developer/Xcode/DerivedData/Sample-bvrevcrvgjvtuigbogtgeilpdfcl/Build/Intermediates/Quick.build/Debug-iphoneos/Quick-iOS.build/Objects-normal/armv7/Quick
> 
> ld: warning: ignoring file /Applications/Xcode6-Beta7.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/XCTest, missing required architecture armv7 in file /Applications/Xcode6-Beta7.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/XCTest (2 slices)
> Undefined symbols for architecture armv7:
>   "_OBJC_METACLASS_$_XCTestCase", referenced from:
>       _OBJC_METACLASS_$_QuickSpec in QuickSpec.o
>   "_OBJC_CLASS_$_XCTestCase", referenced from:
>       _OBJC_CLASS_$_QuickSpec in QuickSpec.o
> ld: symbol(s) not found for architecture armv7
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mkauppila** [comment]
I've been looking at this issue lately. With Xcode 6.3 (6D520o) along with latest
Quick (v0.3.0) and Nimble (v0.4.0), the inital error I got when trying to run the tests on device running iOS 8.1 (12B411) was:

```
2015-02-21 13:29:38.576 QuickDeviceTest[450:220922] Error loading /private/var/mobile/Containers/Data/Application/250CAFEC-6BE1-4AC6-9C01-1948331328E2/tmp/QuickDeviceTestTests.xctest/QuickDeviceTestTests:  dlopen(/private/var/mobile/Containers/Data/Application/250CAFEC-6BE1-4AC6-9C01-1948331328E2/tmp/QuickDeviceTestTests.xctest/QuickDeviceTestTests, 262): Library not loaded: @rpath/Quick.framework/Quick
  Referenced from: /private/var/mobile/Containers/Data/Application/250CAFEC-6BE1-4AC6-9C01-1948331328E2/tmp/QuickDeviceTestTests.xctest/QuickDeviceTestTests
  Reason: image not found
DevToolsBundleInjection: Error loading bundle '/private/var/mobile/Containers/Data/Application/250CAFEC-6BE1-4AC6-9C01-1948331328E2/tmp/QuickDeviceTestTests.xctest'
```

After adding Quick and Nimble frameworks to the host application target as `Embedded Binaries`, it's possible to run the tests on a device. To me it feels wrong to add test frameworks to the actual app target  but it's not possible to add embedded binaries to the test target. It might be worth filing a radar to Apple about adding embedded binaries to test target? The sample app can be downloaded from [here](https://www.dropbox.com/s/24l10srl3gwuszn/QuickDeviceTest.zip?dl=0).

I also verified that the same technique works with Xcode 6.1.1 (6A2008a) using Quick (v0.2.2)
and Nimble (v0.3.0). See the `xcode.6.1` branch in the sample app's repo. 

Maybe we should add instructions about this to the readme? Maybe a new subsection to
[How to Install Quick](https://github.com/Quick/Quick#how-to-install-quick) or as a new section after all the how to install Quick using X sections? What do you guys think?

**Comment by modocache** [comment]
Instructions added in #254. Thanks all!
