### ISSUE TITLE
Tests Failing Without Running in Xcode 6 RC

### ISSUE THREAD

**Issue by snown** [Quick/Quick#141]
When I run my tests after installing Quick and Nimble I get a Tests Failed message with the following log:

`Test target Tests encountered an error (Test session exited(82) without checking in. Executable cannot be loaded for some other reason, such as a problem with a library it depends on or a code signature/entitlements mismatch. Retry after a Clean build. If you believe this error represents a bug, please attach the log file at /var/folders/38/fm3x411100v9lp48n_py3dlh0000gn/T/com.apple.dt.XCTest-status/Session-2014-09-10_11:39:20-JbO0b7.log)`

I did try a clean build to no avail.

Here is the log file referenced above: [fm3x411100v9lp48n_py3dlh0000gn/T/com.apple.dt.XCTest-status/Session-2014-09-10_11:39:20-JbO0b7.log](https://www.dropbox.com/s/j2eufgc6nhxygoz/Session-2014-09-10_11%3A39%3A20-JbO0b7.log?dl=0)

Thanks for any insight.

**Comment by codeblooded** [comment]
@modocache I think this may still be an issue. I deleted the DerivedData folder in my recent app, and the same error was shown.  I noticed @52doho's comment about importing UIKit, but, unfortunately, the error is still there.  I'm attaching the message:

```
IDEBundleInjection.c: Error 3587 loading bundle '/Users/ben/Library/Developer/Xcode/DerivedData/TimeMath-cwdbxiewgonhqvfyglhwqjyahhia/Build/Products/Debug-iphonesimulator/TimeMathTests.xctest': The bundle “TimeMathTests” couldn’t be loaded because it is damaged or missing necessary resources.
DevToolsBundleInjection environment:
XCInjectDiagnostics: (null)
XCInjectBundleInto: /Users/ben/Library/Developer/Xcode/DerivedData/TimeMath-cwdbxiewgonhqvfyglhwqjyahhia/Build/Products/Debug-iphonesimulator/TimeMath.app/TimeMath
XCInjectBundle: /Users/ben/Library/Developer/Xcode/DerivedData/TimeMath-cwdbxiewgonhqvfyglhwqjyahhia/Build/Products/Debug-iphonesimulator/TimeMathTests.xctest
TestBundleLocation: /Users/ben/Library/Developer/Xcode/DerivedData/TimeMath-cwdbxiewgonhqvfyglhwqjyahhia/Build/Products/Debug-iphonesimulator/TimeMathTests.xctest
TMPDIR: /Users/ben/Library/Developer/CoreSimulator/Devices/5FB25F15-A1AF-4BE2-BE22-0B4F28652BB9/data/Containers/Data/Application/86AF197D-3E0C-45EF-87AB-6158543A0FFB/tmp
DYLD_LIBRARY_PATH: /Users/ben/Library/Developer/Xcode/DerivedData/TimeMath-cwdbxiewgonhqvfyglhwqjyahhia/Build/Products/Debug-iphonesimulator
DYLD_INSERT_LIBRARIES: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/IDEBundleInjection.framework/IDEBundleInjection
DYLD_FRAMEWORK_PATH: /Users/ben/Library/Developer/Xcode/DerivedData/TimeMath-cwdbxiewgonhqvfyglhwqjyahhia/Build/Products/Debug-iphonesimulator
DYLD_FALLBACK_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib
DYLD_FALLBACK_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks


*** Test session exited(82) without checking in. Executable cannot be loaded for some other reason, such as a problem with a library it depends on or a code signature/entitlements mismatch. Retry after a Clean build. If you believe this error represents a bug, please attach the log file at /var/folders/k6/zlppzhg51fqf_9yjqw3r0ymh0000gn/T/com.apple.dt.XCTest-status/Session-2015-02-08_01:57:50-FHMj8N.log
```

**Comment by marciok** [comment]
Hi @codeblooded did you try to:
 1. Delete all Quick and Nimble references from your project;
 2. Delete the app from the simulator;
 3. Include them again;
 4. Write a passing test; 

That solved the problem for me.

**Comment by paulyoung** [comment]
Adding `import UIKit` / `import AppKit` was the solution in my case.
