### ISSUE TITLE
Add explicit notes on what versions of Xcode and iOS Quick supports

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#146]
I think the README used to mention that Quick worked on Xcode 6.0 beta 4. It now works with both Xcode 6.0 and Xcode 6.1b2.

Because Quick uses Swift, I don't think it can support any versions of iOS prior to 8.0.

All of this is probably very important to people considering using Quick to test their projects--it should be clear in the README what platforms are and are not supported. The README should list all supported versions of Xcode, OS X, and iOS.

**Comment by istx25** [comment]
If I can have an updated list of which versions we support, I can get this finished. Not sure if I have to manually test each or if there are scripts that can do the work for me. Ideas?

**Comment by modocache** [comment]
I think we should aim to support:

1. The latest official release of Xcode on the latest official release of macOS
2. The latest beta version of Xcode on the latest official release of macOS
3. The latest beta version of Xcode on the latest beta version of macOS

But in practice this is pretty difficult, since most people don't have all three environments at their disposal. For example, people who run official releases only (like me) can only help with (1), and contributors on beta macOS can only help with (3).

Keeping in mind how hard it is to test multiple versions, I think we should never promise to support:

- Versions of Xcode older than the official release
- Versions of macOS older than the official release
- Beta versions of Xcode and macOS older than the latest beta -- in other words, if Xcode 8 beta 6 is the latest, we don't support Xcode 8 beta 5

In the future, it might be nice to put specific people in charge of each of the 3 items above -- a designated person in charge of making sure Quick works on the latest Xcode beta and current macOS, for example.

**Comment by istx25** [comment]
This issue seems to be done with the addition of https://github.com/Quick/Quick#swift-version.
