### ISSUE TITLE
it should receive example metadata

### ISSUE THREAD

**Issue by ashfurrow** [Quick/Quick#148]
In `it` calls, the closure should (optionally) receive example metadata in the same way that `beforeEach` does. 

I don't see this being a contentious API change, and is non-breaking, so I'm going to begin work on it and get back to you with a PR for feedback.

**Comment by modocache** [comment]
For the record, I still think this is worth doing--I just keep putting it on the back burner... :no_mouth:

**Comment by ashfurrow** [comment]
It happens – don't let it get you down!

**Comment by istx25** [comment]
What's the status on this @ashfurrow? :)

**Comment by ashfurrow** [comment]
We were able to fix [my issue](https://github.com/ashfurrow/Nimble-Snapshots/issues/6) without this, so it fell off my radar. I can take a look at making a PR after Labour Day.

**Comment by istx25** [comment]
Bringing attention back to this issue since it's after Labour Day. 🐱 @ashfurrow Do you have more free time these days?

**Comment by ashfurrow** [comment]
I regret to say that I haven't had time to look at this, and likely won't until the holidays. I'll remove myself as an assignee in case someone else wants to tackle it, but I'll put a calendar reminder to look at it over xmas 👍

**Comment by istx25** [comment]
No problem. Thanks!

**Comment by istx25** [comment]
I know I'm a little late (not xmas) but just in case you're looking for something to do during the holiday/new years season, @ashfurrow. :D No worries if not though.

**Comment by ashfurrow** [comment]
I'm afraid I never got to this, my schedule is pretty busy coming up so I don't think I'll be able to tackle it in the near future.
