### ISSUE TITLE
Provide option to randomize test order

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#152]
It's probably impossible to randomize the order of the specs--XCTest decides the order XCTestCase subclasses are traversed. But users should have the option to randomize the order in which individual examples within those specs are called. Randomizing the order encourages users to write better examples that work independent of the order of execution.

Randomization is simple, really: just shuffle the array of invocations returned here: https://github.com/Quick/Quick/blob/f656a4ee92ce0089199233a10a6688aecce5f511/Quick/Quick/QuickSpec.m#L73

The tricky part is deciding:
##### 1. Should examples be randomized by default?

My initial vote was no. Randomizing by default would be very confusing to beginners, who almost certainly do not expect that behavior. This strikes me as more of a power user feature.

But then again, it may be best to read and digest the discussion in https://github.com/rspec/rspec-core/issues/635 before coming to a conclusion.
##### 2. How can users turn randomization on/off?
- A command line argument would mean users can only toggle when running the specs via the command line.
- A macro would mean users can only toggle via a change to their source code.
- Perhaps users can override a `BOOL` getter on `QuickSpec` to return true/false to indicate whether they want randomization. But that would mean randomization would be on a per-spec basis, and seems too granular a level of control.
##### 3. How do users specify a seed?

Test output should include the seed used to randomize the order of the examples. Users should be able to specify that seed when running the tests in order to get them to run in the exact same order. This will help them debug unexpected failures.

---

Perhaps the solution to all these problems is to provide a configuration object, [kind of](https://www.relishapp.com/rspec/rspec-core/docs/configuration/overriding-global-ordering#registering-a-custom-ordering) like [RSpec](http://www.rubydoc.info/github/rspec/rspec-core/RSpec/Core/Configuration):

``` swift
Quick.configure { (configuration: QuickConfiguration) in  // Something like this
  configuration.order = SpecOrdering.random  // This API is totally up for debate
  configuration.seed = 1234
}
```

A configuration object would be useful for much more than just spec ordering, too! :cocktail: :sparkles: 

In order to make sure the configuration is read before any examples are run, it may have to be a class that users inherit from, like how shared examples were implemented in #81. Not a huge fan of a proliferation of these kinds of classes, but c'est la vie.

Alternatively, we could just completely _replace_ shared examples with a configuration object:

``` swift
Quick.configure { (configuration: QuickConfiguration) in
  configuration.registerSharedExamples("something edible") { /* ... */ }
}
```

But I'm not sure whether I'm in love with that idea.

**Comment by istx25** [comment]
From what I've read in this issue and seen with the commits, I believe the work that needed to happen with this issue has been completed so I am going to close it. Let me know if not and we can reopen it.

**Comment by jeffh** [comment]
I don't think this is actually implemented. There's a bunch of supporting features for it, but not actually the shuffling of tests.

**Comment by istx25** [comment]
Oh, my bad. We can open the issue again.

**Comment by younata** [comment]
Given that `randomizeTestOrder` is now a configurable option in XCTest. I don't think it's necessary that we do this. I'm going to close it. If there's enough interest in doing this, then we should reconsider it.
