### ISSUE TITLE
Xcode 6.1 OSX 10.9.5 can't see result.

### ISSUE THREAD

**Issue by objczl** [Quick/Quick#157]
![2014-10-21 7 30 27 pm](https://cloud.githubusercontent.com/assets/4112633/4717514/ae271c0a-5915-11e4-8594-55592da26d2f.png)

can't see result.

**Comment by istx25** [comment]
From what I've seen, this "bug" was more a problem with Xcode than it is with Quick. Closing for now. If anyone has/is experiencing this issue today, please file a new issue with updated steps to reproduce.
