### ISSUE TITLE
Library not loaded: @rpath/Quick.framework/Quick / @rpath/Nimble.framework/Nimble

### ISSUE THREAD

**Issue by nikita-leonov** [Quick/Quick#159]
Current installation instructions does not provide all information required for a comfortable use of Quick & Nimble. Running of unit tests from command line with Quick / Nimble as dependency without prior compilation of frameworks will cause error with text "Library not loaded: @rpath/Quick.framework/Quick". 
Issue is actual for Quick users https://github.com/facebook/xctool/issues/415 now. Similar issue was recently actual for Alamofire users https://github.com/Alamofire/Alamofire/issues/101
issue was fixed as result following string appeared in documentation (https://github.com/Alamofire/Alamofire):
- Expand the "Target Dependencies" group, and add Alamofire.framework.
- Click on the + button at the top left of the panel and select "New Copy Files Phase". Rename this new phase to "Copy Frameworks", set the "Destination" to "Frameworks", and add Alamofire.framework.

Similar additions for Nimble & Quick installation instructions need to be add.

**Comment by iwasrobbed** [comment]
Leaving here as an FYI: In Objective-C, this can also be caused by not having a `.swift` file in your test target. For more information, read: https://github.com/Quick/Quick/blob/master/Documentation/en-us/QuickInObjectiveC.md#your-test-target-must-include-at-least-one-swift-file
