### ISSUE TITLE
Crash on report screen when reviewing quick specs

### ISSUE THREAD

**Issue by akatz** [Quick/Quick#160]
After a spec run, using the arrow button on the test reporter crashes xcode

![](https://www.evernote.com/shard/s205/sh/ef33173f-c5b4-43ac-990b-13788abee744/7f53a9dfdcbb32a2a5ff635e9cbdcd20/deep/0/Screenshot-2014-10-22-00.59.04.png)

**Comment by jeffh** [comment]
Xcode 7 doesn't seem to crash anymore with this. It doesn't properly jump to source, but I don't think we can do anything since this is something Xcode controls. Closing.
