### ISSUE TITLE
Add configuration object; provide hooks around each example

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#163]
We want this: http://www.rubydoc.info/github/rspec/rspec-core/RSpec/Core/Configuration

#152 contains a discussion of some of the motivations. Moreover, there's [this request](https://twitter.com/jspahrsummers/status/525374341358579712) by @jspahrsummers:

> I have shared teardown logic that needs to happen between every Quick example, across specs. Where’s a good place to put that?

Currently, there's [no good way](https://twitter.com/jspahrsummers/status/525375263149146113) to do that.

**Comment by codeblooded** [comment]
@modocache is there a specific way you would like this documented?  How in-depth would you like it to go with explanations for the various options?

**Comment by modocache** [comment]
Good question! :100: 

I think it'd be great to have an explanation of how `QuickConfiguration` can be used to configure Quick's overall behavior, and a blurb that "for example, you can register a `beforeEach` closure that runs prior to every example by writing xyz...", along with some code samples.

I favor having in-depth documentation. The README is getting awful long, though, so I'm beginning to think it may be a good idea to split documentation up, sort of like [ReactiveCocoa's `Documentation` folder](https://github.com/ReactiveCocoa/ReactiveCocoa/tree/a6bc3a918de10c0310f10185fd5eca72d285742c/Documentation). In that case, we'll keep the README short, but with links to the relevant sections. One such section could be an in-depth look at `QuickConfiguration`. But for now, I'm fine with a lot of text in the README. :+1: :sparkles:

**Comment by modocache** [comment]
Closed thanks to #230--thanks, @codeblooded!
