### ISSUE TITLE
README: Add note that a test target that uses Quick must contain at least one Swift file (and file Apple radar)

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#164]
Most GitHub projects that use Quick only contain tests in Objective-C. They're forced to do the following in order to use Quick: https://github.com/github/Archimedes/commit/64602a1003372da0be9a42b181ed2ce27358a1d0#diff-ef5d79a2166fc30bc747d6b89af5785eR14

Add a note to the README that this is necessary. Also, investigate whether there's a better way to get things to work.

**Comment by phatblat** [comment]
Did you ever get around to filing a radar for this? I'll happily dup. Seems like there should be a build setting to tell Xcode to "link it anyway", if it can't be made to figure it out automatically.

**Comment by modocache** [comment]
Based on [the comment in this repo](https://github.com/github/Archimedes/commit/64602a1003372da0be9a42b181ed2ce27358a1d0#diff-ef5d79a2166fc30bc747d6b89af5785eR14), I bet the GitHub team has filed one! If I could find the openradar link I'd dupe it.
