### ISSUE TITLE
Could not get Quick running in Xcode 6.1 on 10.10 Yosemite

### ISSUE THREAD

**Issue by nmtitov** [Quick/Quick#180]
Hello, I am trying to install Quick and Nimble, still no luck.
1. I clone git repos to my machine
2. Add Quick and Nimble projects to Tests target
3. For Tests target add Quick and Nimble projects to "Link Binary With Libraries" phase
4. Hit cmd+U and boom: "The bundle “QuickTestTests” couldn’t be loaded because it is damaged or missing necessary resources. <...> Executable cannot be loaded for some other reason, such as a problem with a library it depends on or a code signature/entitlements mismatch."

Here are error logs
https://gist.github.com/nt9/1e11b2644a5d5a77e173 (Xcode output)
https://gist.github.com/nt9/aed3c6dfd19341ce0bbf (log file)

If I remove libraries from "Link Binary With Libraries" phase everything is ok. If I add anything — I get the error. Would be great if someone could help :)

**Comment by AAAboutajedyne** [comment]
Hello, even if i add the "SwiftSpec.swift" file to the project created by @nmtitov I get always the same build error "No such module Quick".
<img width="1398" alt="build-error no such module quick" src="https://cloud.githubusercontent.com/assets/26308931/23801672/e4ca6a0e-05a8-11e7-8706-93cdb0b41191.png">


I'm working on an Objective-C project, using Xcode 8.2.1, I don't think the fact that I'm declining the proposition of xCode to convert the "Nimble" & "Quick" to Swift 3.0 causes the problem.

Thank you in advance for your collaboration.
