### ISSUE TITLE
Create +ObjC versions of all functional tests written in Swift

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#200]
All API's should have first-class tests in both languages. Wouldn't want to break something in one but not the other!

- [x] ItTests+ObjC.m
- [x] BeforeEachTests+ObjC.m
- [x] AfterEachTests+ObjC.m
- [x] PendingTests+ObjC.m
- [x] BeforeSuiteTests+ObjC.m
- [x] AfterSuiteTests+ObjC.m
- [x] SharedExamples+BeforeEachTests+ObjC.m

Blocks #193.

**Comment by modocache** [comment]
![](http://i3.kym-cdn.com/photos/images/facebook/000/073/178/President-George-W.-Bush-Mission-Accomplished.jpg)

We did it, @mkauppila! :cherry_blossom:

**Comment by paulyoung** [comment]
:boom:

**Comment by mkauppila** [comment]
Oh, nice :cake: @modocache What an image :smiley: So it's time to move to the next issue :fireworks: :birthday:

**Comment by modocache** [comment]
@mkauppila Yes please! I think the next biggest issue to tackle is #140. :point_up: :bulb:

**Comment by mkauppila** [comment]
Yes, that would be nice a issue to solve. I'll take a look at it. Maybe I can solve it :D
