### ISSUE TITLE
README: Add instructions on testing view controllers defined using UIStoryboard

### ISSUE THREAD

**Issue by pawurb** [Quick/Quick#212]
Hello. I am starting to test my project with Quick. I have a problem with running a test of my viewController. It has couple of UI elements attached from storyboard. It appears that when I run the spec they are not instantiated and appear as nil. I called ``view`` method as written in docs and ``viewDidLoad`` does get called. Do I need to explicitly trigger loading of controller from my storyboard or something ? I am using swift. I successfully ran some unit tests so the framework is configured correctly.  Storyboard is added to test target. Any help will be appreciated.

**Comment by modocache** [comment]
Instructions added in #254. Thanks, @pawurb! :cherry_blossom:
