### ISSUE TITLE
CI: Build OSX and iOS apps that use Quick

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#238]
Continuous integration should build two apps, in addition to Quick itself. By verifying that these apps build when using Quick, we can merge pull requests that may introduce integration errors without pulling down the changes and testing them ourselves.

**Comment by modocache** [comment]
In addition to vanilla Xcode projects, CI should build apps that use Carthage/CocoaPods to link a local copy of Quick against an app that includes unit tests written using Quick.

Here's the matrix:

1. CocoaPods + OS X
2. CocoaPods + iOS
3. Carthage + OS X
4. Carthage + iOS
5. Nothing + OS X
6. Nothing + iOS

The idea is that we're always sure CocoaPods/Carthage/whatever works as we develop.

**Comment by jeffh** [comment]
Interesting WIP that's for Nimble: http://github.com/jeffh/NATs




—

**Comment by istx25** [comment]
What's the progress on this?

**Comment by jeffh** [comment]
This still needs work. I haven't updated that repo in awhile...

**Comment by ikesyo** [comment]
Closing this as part of issue cleanup.
