### ISSUE TITLE
Black box testing

### ISSUE THREAD

**Issue by 0x1mason** [Quick/Quick#241]
Can Quick be used for black box testing?  E.g., can you use it to write functional tests for a UI for which you don't have the source code?

**Comment by modocache** [comment]
Quick doesn't have any features that specifically support this, no. Sorry, @0x1mason--but if you find a tool for black-box testing iOS apps, please let me know! :bow:

**Comment by 0x1mason** [comment]
:+1:  I work on the [Appium](http://appium.io/) project, which enables black-box testing, but it relies on Instruments under the hood.  Always looking for the perfect tool.

Thanks for your help!

**Comment by modocache** [comment]
Oh cool! Yeah, my go-to for those sorts of tests has been [KIF](https://github.com/kif-framework/KIF). I assume Appium also relies on accessibility identifiers? I'll check it out!

KIF does [integrate with Specta](https://github.com/kif-framework/KIF#use-with-other-testing-frameworks), and there are projects that allow it to [integrate with the Kiwi testing framework](https://github.com/IndieGoGo/KIF-Kiwi) as well. Is this the sort of thing you're looking for?
