### ISSUE TITLE
Support Swift 1.2

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#243]
@Quick/contributors We need to support Swift 1.2, pronto! As far as I can tell, our choices are:

1. Support Swift 1.2 on the main branch, and create a new, backwards-incompatible tag (v0.4.0 by my count). Cut a branch, `swift-1.1`, to continue to support old versions of Swift.
2. Do the opposite: cut a branch for `swift-1.2`, and support Swift 1.0 on the main branch. We'll cut a tag once 1.2 is officially released.

Nimble should take the same approach. Thoughts, @jeffh?

I'm in favor of option 1. We'll have Travis track the health of the `swift-1.1` branch, since it may be a while before they support Xcode 6.3. If anyone can suggest a CI service that updates faster, please file a separate issue.

If anyone's interested in making this change, please submit a pull request! Otherwise, expect to see one from me within the next 12 hours. :100: :sparkles:

**Comment by mprudhom** [comment]
FYI, I got Quick & Nimble working with Swift 1.2 without too many problems. I didn't port the test cases over, so I haven't made a pull request, but the conversion is mostly trivial.

The bad news is that the `@autoclosure` attribute now implies a new `@noescape` attribute, which forbids the closure from being retained anywhere. So I needed to break expect into two functions: an immediate evaluation version and a delayed-capable version (that accepts a full closure), like so:

```swift
/// Make an expectation on a given actual concrete value. The value given is eagerly evaluated.
public func expect<T>(value: T?, file: String = __FILE__, line: UInt = __LINE__) -> Expectation<T> {
    return Expectation(
        expression: Expression(
            expression: { value },
            location: SourceLocation(file: file, line: line)))
}

/// Make an expectation on a given actual expression. The value given is lazily evaluated.
public func expect<T>(expression: () -> T?, file: String = __FILE__, line: UInt = __LINE__) -> Expectation<T> {
    return Expectation(
        expression: Expression(
            expression: expression,
            location: SourceLocation(file: file, line: line)))
}

``` 

It might make sense to remove the closure version of `expect()` and have a single function that merges `expect()` and `toEventually()` so people don't accidentally use the non-closure version like so:

```swift
var connected: Bool = false
// do something that eventually sets connected to true
expect(connected).toEventually(equal(true), timeout: 5.0) // 'connected' is not a closure, so will always be false!
```

So this:

```swift
expect({ connected }).toEventually(equal(true), timeout: 5.0)
```

Would become:

```swift
eventually({ connected }, timeout: 5.0).will(equal(true))
```

**Comment by sharplet** [comment]
What about having `expect(value)` and `expect { closure }` return different types, and only have the latter respond to `toEventually`?

**Comment by mprudhom** [comment]
That sounds like a good idea to me (although I should add I am very unfamiliar with the codebase and the design decisions that went into it).

One nice thing about having expect (or whatever the functions name is) accept a timeout parameter and return a different type (e.g., an `EventualExpectation`) is that the existing operator overloading could work with the delayed evaluation. E.g.:

```swift
expect(connected) == false
startConnectionProcess() // or whatever
expect({ connected }, timeout: 5.0) == true
```

**Comment by modocache** [comment]
> What about having `expect(value)` and `expect { closure }` return different types, and only have the latter respond to `toEventually`?

Interesting piece of trivia: this is how I had originally implemented `expect`: https://github.com/Quick/Quick/blob/173b345bb7677dcb390501706274f841e87b6e4b/Quick/Expectations/DSL.swift

In any case, I think this approach is better than defining a new `eventually` top-level DSL function, but will certainly defer to @jeffh. :eyes: 

@mprudhom I'd love to see a pull request of what you have now--I may end up using it as a starting point for closing this issue! :+1:

**Comment by mprudhom** [comment]
OK, I'll try to get the tests working and submit a pull request in an hour or so.

**Comment by modocache** [comment]
@mprudhom Or even before the tests start passing! I'd love to see what you have now :cherry_blossom:

**Comment by mprudhom** [comment]
OK, I've submitted pull requests at:

https://github.com/Quick/Quick/pull/244
https://github.com/Quick/Nimble/pull/86

It builds on OS X and most (but not all) of the tests pass. The bulk of the changes were actually moving closure arguments behind default parameters (seems to be a new undocumented requirement for trailing closure syntax) and some more explicit casting using as! and some more explicit coercions between Foundation and Swift types (again, undocumented in the release notes),

I hope you find it useful!

**Comment by modocache** [comment]
Awesome, thanks a lot, @mprudhom! :100: :sparkles:

I've used your commits in #245 and https://github.com/Quick/Nimble/pull/88. I'd like to merge those into the master branches of their respective repositories, provided that:

- [ ] We cut a `swift-1.1` branch from the current HEAD of the `master` branch.
- [ ] The README in each project displays a Travis CI badge for the `swift-1.1` branch, **not** the `master` branch, since the Travis CI will not be able to build Swift 1.2 code until Xcode 6.3 is no longer in beta.
- [ ] `README.md` and `CONTRIBUTING.md` explain the `swift-1.1` and `master` branches--that `swift-1.1` will only include minor updates, and that `master` will be built on the assumption that users are running Swift 1.2.

**Comment by jeffh** [comment]
Hey sorry, for the late reply.

@modocache, I agree with keeping master on par with Swift 1.2.

I think having a separate return type for using `toEventually` will cause more breakages. It would also restrict matchers that would like to use closures (eg - raiseException matcher). It shouldn't be too difficult to check for the incoming type to be a closure for `toEventually` to check.

**Comment by modocache** [comment]
@jeffh Nice, thanks for the quick response! :+1: 

I've cut `swift-1.1` and `swift-1.2` branches on each project--both Quick and Nimble. I think Quick is in a good place, so it's ready to be merged as soon its Nimble submodule reference has been updated.

I'll leave Nimble up to you--feel free to push changes to the `swift-1.2` branch as you see fit. To be honest, I've never really understood `@autoclosure` in Swift! :stuck_out_tongue: 

Let me know once you're ready and we'll switch Quick/Nimble master to support Swift 1.2, and cut new tags for each! :rocket:

**Comment by modocache** [comment]
Swift 1.2 support was released in https://github.com/Quick/Quick/releases/tag/v0.3.0. Thanks, everybody!
