### ISSUE TITLE
"Empty test suite." message

### ISSUE THREAD

**Issue by NebulaFox** [Quick/Quick#247]
Just concerned that message keeps cropping up when tests fail or pass. Should I be worried?

Output:

    /Users/user/Library/Caches/appCode31/DerivedData/Foo-9d2180e8/Build/Products/Debug-iphonesimulator/Foo.app -XCTest All
    Testing started at 14:51 ...
    Simulator session started with process 23928

    Empty test suite.

    Process finished with exit code 0

The IDE does say it has run all my tests

Xcode 6.1.1
AppCode 3.1.2
Mac OS 10.10.1

**Comment by jeffh** [comment]
This doesn't seem right, does the test suite fail if you explicitly insert an error?

**Comment by NebulaFox** [comment]
Yes the test suit fails when I explicitly insert an error, but I still get the "Empty test suite" message

**Comment by manumax** [comment]
I tried the scenario using AppCode. In my case "Empty test suite" was referring to a test case called `Quick.framework` (see image attached below). My opinion is that, while searching for testcases to run, it ends up thinking that `QuickSpec`, which extends `XCTestCase`, is an actual test case with no tests to run. 

![quick_247](https://cloud.githubusercontent.com/assets/6240851/7635905/29112a9c-fa64-11e4-8a65-e60f4507d258.png)

**Comment by manumax** [comment]
Just to add that I think it is related to #177

**Comment by jeffh** [comment]
Yeah, this is probably just release to #117, so I'll close this as a duplicate.

Thanks for filing the issue :+1:.
