### ISSUE TITLE
Deliver failures on the main thread?

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#248]
Does Quick need something like https://github.com/specta/specta/pull/133?

**Comment by paulyoung** [comment]
Possibly related to #132?

**Comment by modocache** [comment]
Most certainly related, but it seems like that issue is just a question as to how to write asynchronous tests.

Looking at the Specta PR, it seems like the problem centers around how Specta stores its globals in thread-local dictionaries. Quick doesn't do this, so it's possible we won't need to make any changes.
