### ISSUE TITLE
Support escaping autoclosure syntax for expect

### ISSUE THREAD

**Issue by mprudhom** [Quick/Quick#251]
It looks like escaping autoclosure syntax is back in Xcode 6.3 beta 2 with the new syntax `@autoclosure(escaping)`. Should we re-implement the `expect()` function with the new syntax (that was removed in https://github.com/Quick/Quick/issues/243)? This would allow Quick+Swift 1.2 to be API compatible with Quick+Swift 1.1.

**Comment by jeffh** [comment]
Yes please! :+1:

**Comment by modocache** [comment]
+1 from me!

**Comment by modocache** [comment]
Closed, thanks to #103. Thanks, @jeffh! :+1:
