### ISSUE TITLE
Explain in more detail why it's not a good idea to add source files to test target

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#256]
Relevant links are at https://github.com/bredfield/RealmTest/pull/1.

**Comment by jeffh** [comment]
This also applies to objective-c, where you'll get two classes of the *same name*. Instance equality failure fun ensues.

**Comment by istx25** [comment]
I'll try to get on this in the coming weeks.

**Comment by ikesyo** [comment]
Closing this as part of issue cleanup.
