### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by LightD** [Quick/Quick#263]
So I'm trying to use CircleCI, and I need to write a custom script for run quick tests.. what do I need to run Quick tests using XCTool for example??

**Comment by modocache** [comment]
Thanks for the question, @LightD! :sparkles: 

The method to run "Quick tests" is no different from running tests defined using `XCTestCase`. For example, to run unit tests for a project called `Foo.xcodeproj` from the command line, one would usually write:

```
xcodebuild -project Foo.xcodeproj test
```

For `Foo.xcworkspace`, that might look like the following (make sure the "scheme" is "shared"):

```
xcodebuild -workspace Foo.xcworkspace -scheme Foo test
```

I've never used xctool before, but I assume it has an easy way to run unit tests. Whatever that is, it's the same when using Quick.

Also, keep in mind that you can have a test suite that contains both `QuickSpec` tests and `XCTestCase` specs. They're all run when you run the tests. :+1:

**Comment by LightD** [comment]
Thanks for the quick response @modocache! :grin: 

You're right.. everything worked just fine.. and I tested more with xctool and all went great.. for some reason though CircleCI can't detect that there's a TestSuite and it's saying that there's no tests.. but I guess that's a questions that's out of this scope's issue.. 

You were a great help.. and this is awesome library :+1:

**Comment by modocache** [comment]
OK, let me know how it goes! One hypothesis: are you trying to run .ocunit tests? If your test bundle has a .ocunit wrapper extension (you can check in your project's project file, search for "Wrapper Extension"), but the tests are written in XCTest or Quick, those tests won't be detected or run.

Good luck! :tophat:
