### ISSUE TITLE
Missing argument for parameter

### ISSUE THREAD

**Issue by muratgurel** [Quick/Quick#264]
I am using Carthage to integrate Quick and Nimble. I tried to run the tests in the readme file, but Xcode gives the following error:

```
"Missing argument for parameter #5 in call"
```

Xcode Version: Version 6.2 (6C131e)
iOS Version: 8.2
Quick Version: v0.3.0

![screen shot 2015-03-19 at 12 17 52](https://cloud.githubusercontent.com/assets/2019092/6728474/ad0ab632-ce32-11e4-8486-6bf281ca3a84.png)

**Comment by modocache** [comment]
Quick v0.3.0 is built for Swift 1.2, which is included in Xcode 6.3. To use Quick with Swift 1.1, use v0.2.*.

Can you confirm it works after trying Xcode 6.2/Quick 0.2.*, or Xcode 6.3/Quick 0.3.0?

**Comment by modocache** [comment]
I'm pretty sure this isn't an issue anymore. I'm using Xcode 6.3 and 6.4 with the latest version of Quick. Thanks for the report, @muratgurel! :+1:

**Comment by selcukyucel** [comment]
Hi,
I am using;
Xcode: 6.3.2
Quick: 0.4.1

it("does this", flags: flags, { () -> () in })

and getting the same error: "Missing argument for parameter #5 in call"

Thanks

**Comment by ikesyo** [comment]
@selcukyucel There isn't Quick v0.4.1. Is that v0.4.0? If so, that is for Xcode 7/Swift 2. For Xcode 6.3/Swift 1.2, you should use v0.3.1.

**Comment by selcukyucel** [comment]
@ikesyo  Sorry my fault Nimble is 0.4.1, Quick pod line is 
pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'master'

I changed the "it" line like > it (description, closure) no error
but when I use the version with flag > it(description, flags, closure)
I got error missing argument error. 

Thanks
