### ISSUE TITLE
Compiling error: BeLessThan.swift:32:53: Expected type after 'as'

### ISSUE THREAD

**Issue by bagusflyer** [Quick/Quick#269]
I'm trying to use CocoaPods to install Quick and Nimble. Here is my Podfile:

````
platform :ios, "8.0"

target 'TestDemo' do

    use_frameworks!

    pod 'Quick'
    pod 'Nimble'

end
````

I got 23 compile errors, the error message is something like:

> BeLessThan.swift:32:53: Expected type after 'as'

**Comment by modocache** [comment]
Are you using Swift 1.2? If that's the case, please use Quick v0.3.0 (sorry, not on CocoaPods yet--@ashfurrow?) and Nimble v0.4.0--or master on both of those libraries.

If you're using Swift 1.1, use Quick v0.2.* and Nimble v0.3.*.

**Comment by bagusflyer** [comment]
I'm using Quick 0.2.2, Nimble 0.4.0. But how can I know my Swift version? Thanks

**Comment by ashfurrow** [comment]
What version of Xcode are you using?

**Comment by bagusflyer** [comment]
6.2

**Comment by modocache** [comment]
Sorry for the confusing comment! Xcode 6.2 uses Swift 1.1, so you'll need to use Nimble v0.3.0. Let us know if that works!

**Comment by bagusflyer** [comment]
I can compile it when I use Nimble 0.3.0. But the app (newly created project) crashes with the following error:

> dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/zhouhao/Library/Developer/CoreSimulator/Devices/1B4A56C0-A0F5-4B88-86A2-8894809ED8DE/data/Containers/Bundle/Application/EB7CE6E3-4869-4D3C-8F78-3B368212B2D5/TestDemo.app/Frameworks/Nimble.framework/Nimble
  Reason: image not found

**Comment by ashfurrow** [comment]
Strange – looks like it's trying to load Nimble from your app and not the test bundle. What does your podfile look like?

**Comment by bagusflyer** [comment]
Yes. You're right. It's in my app. I've changed the Podfile. It works now. Thanks

**Comment by modocache** [comment]
@ashfurrow, I've been meaning to do so myself, but could you check if Quick v0.3.0 is on CocoaPods trunk?

If you can't no worries, I plan on getting to it once I get back to New York! :wave:

**Comment by ashfurrow** [comment]
Will do!

**Comment by ashfurrow** [comment]
Ah, sorry for not getting to that yesterday – was taking a personal day off.
