### ISSUE TITLE
Trouble testing a watchkit extension

### ISSUE THREAD

**Issue by treybean** [Quick/Quick#273]
We use Quick + Nimble on our main app. We just added a WatchKit target, though, and are having trouble getting access to the extension's classes to test. We follow the recommendation to not make our app's classes part of the MyAppTests target (and import the app's module) and plan to do the same for testing the watchkit extension. Right now, with a pretty unmodified watchkit target, we added a new spec class to the MyAppTests target, InterfaceControllerSpecs.swift

```swift
import MyApp_WatchKit_Extension
import Quick
import Nimble

class InterfaceControllerSpecs: QuickSpec {
    override func spec() {
        fit("should work") {
            var interfaceController = InterfaceController()
            expect(interfaceController.description).toNot(beNil())
        }
    }
}
```

As you can see, pretty basic. :) This won't compile, though. I get the following build error:

* Apple Mach-O Linker Error
  
  Undefined symbols for architecture x86_64:
  "__TFC26MyApp_WatchKit_Extension19InterfaceControllerCfMS0_FT_S0_", referenced from:
      __TFFC12MyAppTests24InterfaceControllerSpecs4specFS0_FT_T_U_FT_T_ in InterfaceControllerSpecs.o
  "__TMaC26MyApp_WatchKit_Extension19InterfaceController", referenced from:
      __TFFC12MyAppTests24InterfaceControllerSpecs4specFS0_FT_T_U_FT_T_ in InterfaceControllerSpecs.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

When I comment out the ``` var interfaceController = InterfaceController()``` line, it compiles fine. Am I doing something stupid here or is there a different way to test watchkit extensions? Does Quick support that?

**Comment by jeffh** [comment]
Hey @treybean.

Unfortunately, WatchKit is extremely difficult to test since creation of instances inheriting WatchKit aren't generated (hence why you see missing symbols when trying to test them). The storyboard does some special code generation to make it's API conform to what is specified in source. Crazy, magical, and untestable :(

There's [PivotalCoreKit](https://github.com/pivotal/PivotalCoreKit/) which provides fakes an stubs to Apple libraries. PCK does provide WatchKit fakes that allow you to write tests (Robolectric-style). Sadly, I don't think PCK has support for Swift just yet, but feel free to file issues on that project.

**Comment by modocache** [comment]
@jeffh That's awesome! I'll definitely check it out.

I seem to recall @irace attempting to test WatchKit apps, although his takeaway may also have been that it's not possible at this time with Xcode/XCTest (and, by extension, Quick).

**Comment by irace** [comment]
Not me – I've done zero WatchKit development.

**Comment by modocache** [comment]
Oh whoops! Never mind, sorry for the ping.

@treybean, I think the best approach is to split as much of the logic out into a [separate framework target](https://twitter.com/joar_at_work/status/582922468379099136), then test that. The fact that WatchKit apps themselves are untestable is, in my opinion, [radar-worthy](https://twitter.com/joar_at_work/status/582922758159380481). :fish:

**Comment by modocache** [comment]
Closing this, as there isn't much we can do besides file radars. Sorry, @treybean! :bow:

**Comment by treybean** [comment]
Now worries! Makes sense. I figured this was the case, but wanted to make sure I wasn't missing something. Thanks for the confirmation and tips on where to go from here!
