### ISSUE TITLE
Umbrella header 'Quick.h' not found

### ISSUE THREAD

**Issue by msanders** [Quick/Quick#274]
Hi, I keep running into this error when trying to integrate Quick and Nimble into my project. Happens on both Xcode 6.3 and 6.2.

Here's what my Podfile looks like:

    target 'MyTargetTests', :exclusive => true do
        use_frameworks!
        pod 'Nimble', '~> 0.4.0'
        pod 'Quick'
    end

The spec is simply:

    import Quick

Any idea what's going wrong?

**Comment by jeffh** [comment]
Hey @msanders, it looks pretty strange going on there. Other than manually cleaning out derived data, I'm not sure what else to try based on the information here.

Xcode 6.2, would require Nimble `~> 0.3.0` and Quick `~> 0.2.0` in the podfile.

Do you have a sample project that I can try and troubleshoot on?

**Comment by j2emanue** [comment]
im getting the same error.

**Comment by modocache** [comment]
@msanders and @j2emanue, are either of you still experiencing an issue? If so, can you tell us your Xcode version, and the contents of your Podfile?

**Comment by msanders** [comment]
@modocache sorry for the lack of info - we ended up switching to Carthage instead of Cocoapods for Quick/Nimble and that fixed the issue for us.

**Comment by modocache** [comment]
@msanders Thanks for the update! I recall trying CocoaPods the other day and it worked fine, so I think we can close this issue. :+1:
