### ISSUE TITLE
Could not install Quick with Carthage

### ISSUE THREAD

**Issue by rotespferd** [Quick/Quick#275]
I want to install Quick with Carthage. My setup ist:
- OSX 10.10
- Xcode Version 6.3 (6D554n)
- Swift 1.2
- Carthage 0.6.3

My Cartfile content is
```
github "ReactiveCocoa/ReactiveCocoa"
github "realm/realm-cocoa" >= 0.89.2
```

My Cartfile.private content is
```
github "Quick/Nimble"
github "Quick/Quick" "v0.3.0"
```

When I run *carthage update* the output is

```
*** Fetching ReactiveCocoa
*** Fetching realm-cocoa
*** Fetching Nimble
*** Fetching Quick
fatal: Not a git repository (or any of the parent directories): .git
```

When I remove Quick from the Cartfile.private everything works fine.

**Comment by modocache** [comment]
Thanks for the heads up, @rotespferd!

```
fatal: Not a git repository (or any of the parent directories): .git
```

Any idea what this error message is supposed to mean?

I don't know much about Carthage, but your Cartfile syntax looks different from some others I've seen, like https://github.com/SwiftGit2/SwiftGit2/blob/3a7f826c51a86206dfec625d060ea35bef919c2f/Cartfile.private. Is `v0.3.0` supposed to be in quotes like that?

**Comment by gfontenot** [comment]
`"v0.3.0"` will point to the `v0.3.0` tag directly, instead of to the `0.3.0` _release_. Subtle, but maybe important distinction.

I feel like I've seen this before, fwiw, and I don't believe it's a Quick issue at all. You might open an issue (or search for an existing issue) on Carthage.

**Comment by rotespferd** [comment]
Thank you for the hints. I also try any of the following variants
```
github "Quick/Quick" "0.3.0"
github "Quick/Quick"
github "Quick/Quick" == 0.3.0
github "Quick/Quick" >= 0.3.0
```
They also did not work.

**Comment by modocache** [comment]
> I don't believe it's a Quick issue at all

I'm inclined to agree; I just tried using [SwiftGit2's Cartfile] to download and build Quick, and everything worked as expected. Maybe one of the Carthage folks, like @jspahrsummers, could help us diagnose this?

**Comment by rotespferd** [comment]
It was a bug in Carthage as you can see in Carthage/Carthage#407. I had to delete the Carthage repository cache in ```~/Library/Caches/org.carthage.CarthageKit```. After that everything works fine.

**Comment by jeffh** [comment]
Thank you @rotespferd for closing the loop :smile:. Closing this issue.
