### ISSUE TITLE
 no such module 'Quick'

### ISSUE THREAD

**Issue by priteshshah1983** [Quick/Quick#282]
I have a static-library project written in Objective-C. Currently, it does not have any Swift files. I was hoping to use Quick for writing some tests for my Objective-C classes. I used CocoaPods to install Quick and Nimble using:
````ruby
target :SDKTests do
  use_frameworks!
  pod 'Quick'
  pod 'Nimble'
  pod 'Kiwi', '~> 2.3'
end
````

I'm using CocoaPods version ````0.36.3```` with Xcode version ````Version 6.3 (6D570)````

But, I get ```` no such module 'Quick'```` when I try to run the tests. Can you please help?

Please note that I have no Swift files in this project other than this test class (not sure if it matters).

**Comment by paulyoung** [comment]
Could this be the issue described in #164?

**Comment by priteshshah1983** [comment]
I might be wrong, but AFAIK Apple does not allow adding Swift files to static library targets. Are you suggesting I add a Swift file to the test target?

**Comment by priteshshah1983** [comment]
It seems like it could be related to this issue: https://github.com/Quick/Quick/issues/195

I am also using custom build configurations as described in the issue. But, I got the impression that this would be taken care of by CocoaPods.

**Comment by priteshshah1983** [comment]
It was the custom build configuration as suspected. I will dig more into it but for now, switching to the default CocoaPods ````Pods-SDKTests.debug```` configuration for the test target fixes the issue.

**Comment by priteshshah1983** [comment]
I just found out that my custom build configuration was overwriting the ````FRAMEWORK_SEARCH_PATHS```` set by CocoaPods. I fixed that and everything is great now.
