### ISSUE TITLE
run tests one at a time

### ISSUE THREAD

**Issue by tsaizhenling** [Quick/Quick#286]
I have a few tests i'd like to implement using quick. so my tests are something like 

```
//do something...
expect(self.getCenterController().viewControllers.last as! UIViewController).toEventually(beAKindOf(HomeViewController))
```

 they will result in the app navigating to various pages, so it's neccessary that the tests execute one at a time. how can i achieve this?

**Comment by jeffh** [comment]
Hey @tsaizhenling,

Could you elaborate on your question? I don't quite understand the issue at hand. What are you seeing that isn't expected?

**Comment by tsaizhenling** [comment]
consider the following 2 tests. where goToWishlistPage() and goToHomePage() are asynchronous operations.

```
describe("test 1") {
    goToHomePage()
    it ("goes to home page") {
        expect(self.getCenterController().viewControllers.last as! UIViewController).toEventually(beAKindOf(HomeViewController))
    }
}

describe("test 2") {
    goToWishlistPage()
    it ("goes to wishlist page") {
        expect(self.getCenterController().viewControllers.last as! UIViewController).toEventually(beAKindOf(WishListViewController))
    }
}
```

my problem is that the test cases are not evaluated before the next test case is executed.
so we have an execution order of
```
goToHomePage()
goToWishlistPage()
expect(self.getCenterController().viewControllers.last as! UIViewController).toEventually(beAKindOf(HomeViewController))
expect(self.getCenterController().viewControllers.last as! UIViewController).toEventually(beAKindOf(WishListViewController))
```
and hence the first test will always fail

**Comment by tsaizhenling** [comment]
to be more verbose, i was expecting test 1 to pass/fail, before anything in test 2 is executed

**Comment by jeffh** [comment]
`goToHomePage` and `goToWishlistPage` both need to be inside a `beforeEach` closure:

```swift
describe("test 2") {
    beforeEach {
        goToWishlistPage()
    }
    it("goes to wishlist page") {
        // ...
    }
}
```

Not placing this inside a `beforeEach` runs it while tests are gathered by Quick, and not before each `it`. There's discussions of allowing some form like you wrote above, but that currently isn't in Quick.

**Comment by tsaizhenling** [comment]
thanks for clarifying. closing this issue

**Comment by jeffh** [comment]
No problem! 😃
