### ISSUE TITLE
[RFC] A tale of two user-facing frameworks

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#288]
#287 separates the core Quick functionality into a separate framework, QuickCore.framework. The first commit in that pull request also mentions:

> I'm hoping that in a later commit, Quick.framework will be split up into two user-facing frameworks:
> 
> 1. Quick.framework, for clients writing tests in Swift.
> 2. Objective-Quick.framework, for clients writing tests in Objective-C.

Doing so would introduce two breaking changes to the Quick API:

1. Objective-C users would have to link against Objective-Quick.framework, not Quick.framework.
2. Quick.framework would define `QuickSpec` in Swift, and thus need to change `QuickSpec.spec()` from an instance method to a class method. Early users may recall that it used to be a class method until a7fc644662cbd3b6cbf14152182dd2bbc39124d5, when it was changed to an instance method so that `XCTAssert` macros would work in Objective-C. We would no longer need to support Objective-C in Quick.framework. On the other hand, `QuickSpec.swift` would not be able to perform [this runtime trickery in `QuickSpec.m`](https://github.com/Quick/Quick/blob/cb805a2798a65eeaf98066698e93b61eb0613ac8/Quick/QuickSpec.m#L30).

My question is whether other @Quick/contributors think it's worth it to split Quick.framework into two user-facing frameworks, one implemented in Swift, and one in Objective-C. I'm in favor of it, of course, but I may be overlooking something. Here's how it breaks down in my head:

### Cons

- We'd introduce the above breaking changes.
- We'd have to maintain duplicate implementations of `QuickSpec` and `QuickConfiguration`--the layer that test writers use to write specs. The idea is to keep those implementations as thin as possible, but there'd still be one for Swift and one for Objective-C.

### Pros

- We can be more flexible when adapting to needs of Swift or Objective-C consumers.
- For Swift consumers, we can provide a framework written entirely in Swift.

**Comment by jeffh** [comment]
I like the idea of separating it. But I do have a couple questions off the top of my head:

- How will Quick handle mixed language projects (Swift and Objective-C)? Could there be problems with the same names? I haven't actually tried it out. It's just some theoretical problem in my head.
- Will both QuickSpec variants try to maintain feature parity? The runtime trickery is possible in Objective-C :cry:.
- Also, is there a benefit for a framework entirely in Swift for Swift consumers? Other than the nice warm fuzzy feeling :wink:

I'll need to sleep on it some more :zzz:, but it sounds like a great idea.

**Comment by ashfurrow** [comment]
Makes sense. I think Jeff's concerns are great, but I don't have any further ones.

**Comment by modocache** [comment]
> How will Quick handle mixed language projects (Swift and Objective-C)? Could there be problems with the same names?

I was originally thinking that we could use the same names, since in any given file users would import one or the other, but not both. It's possible that just by linking both frameworks to a test target (which we absolutely *do* want to support, since plenty of people have tests in both languages) would cause duplicate symbol errors, though. I'll have to test this out.

> Will both QuickSpec variants try to maintain feature parity?

As much as possible, yes. But who knows, there may be features we can only implement in Swift, or in Objective-C. Our current feature set is safe, though.

> Also, is there a benefit for a framework entirely in Swift for Swift consumers?

Actually, I'm not entirely sure! :stuck_out_tongue: To be honest, I've always considered the amount of Objective-C in Quick (aside from the bare minimum necessary for Objective-C spec support) a personal failure, since I had set out to write it entirely in Swift. But maybe it's not such a big deal? I'd be interested to hear others' thoughts.

**Comment by sharplet** [comment]
My main feels on this are:

- I like the name Objective-Quick;
- Achieving this entirely in Swift would be super cool;
- At this point, bifurcating the interface doesn't seem worthwhile to me, unless there's some very specific user value attached to it. Adding two names where there was one does increase complexity. And to me, there's an elegance to `import Quick` and `@import Quick;`, regardless of what language you're currently in. But if you've got some specific Swift-only functionality in mind that may make it a no-brainer!

So I suppose maybe the tradeoff is between the complexity of maintenance vs. the simplicity of the interface?

I think if we can achieve both simplicity and expressiveness, and explicitly avoid *limiting* what users can do, we'd be onto a winner.

**Comment by jeffh** [comment]
I agree with what @sharplet said. There should probably be some user-facing benefit to split it.

**Comment by mkauppila** [comment]
I don't have hard opinions about this but I do agree with @jeffh and @sharplet that there should be user-facing benefits for the split too. Currently, there seems to be only negative effects for the users (mainly breaking the API compatibility).

Also it seems based on @modocache's original pros and cons list that the cons outweight the pros. Maintaining duplicate implementations sounds like work :thought_balloon:  Though I do love the idea of having framework written purely in Swift :heart: and having separate frameworks would probably increase the elegance.

**Comment by modocache** [comment]
OK, it seems like the nays have the vote! Admittedly, this would definitely bring more satisfaction to the maintainers than to the end users. :stuck_out_tongue: 

That being said, #287 makes the world monumentally better for everyone, so go merge that one! :grin:
