### ISSUE TITLE
Unable to install Quick & Nimble with Cocoapods

### ISSUE THREAD

**Issue by TomasLinhart** [Quick/Quick#291]
I have followed the guide described here https://github.com/Quick/Quick/blob/master/Documentation/InstallingQuick.md

and when I run tests I get an error in Nimble.h

Nimble.h:2:9: Include of non-modular header inside framework module 'Nimble.Nimble'

**Comment by modocache** [comment]
@ashfurrow might have some ideas here, especially on the CocoaPods side of things. Can you confirm which versions of Xcode, Quick, and Nimble you're using, @TomasLinhart?

**Comment by ashfurrow** [comment]
@TomasLinhart Very strange! Let's get this sorted out for you. Could you supply some additional information for us? The specific version of Xcode (Xcode menu -> About Xcode), the specific version of CocoaPods (`pod --version`), and the contents of your podfile? Thanks!

**Comment by TomasLinhart** [comment]
I have Xcode 6.3, Cocoapods 0.37.0 and this is the content of Podfile

```ruby
platform :ios, '7.0'
inhibit_all_warnings!

pod 'HockeySDK', '~> 3.6'

target 'MyAppTests', :exclusive => true do
  use_frameworks!

  pod 'Quick',
  pod 'Nimble'
end
```

**Comment by ashfurrow** [comment]
That's really strange. I took out the extra comma in `pod 'Quick',` and ran `pod install` using CocoaPods 0.37.0, and under Xcode 6.3.1, it seems to work fine. Here's a [sample project](http://cloud.ashfurrow.com/211g0x162G1S). 

Could you zip up a project showing the problem and upload it somewhere we could take a look?

**Comment by TomasLinhart** [comment]
I have updated Xcode to 6.3.1 and it started working so hard to say what could be wrong.

But anyway, thank you for help. Is there anyway how to get rid of this warning ld: warning: embedded dylibs/frameworks only run on iOS 8 or later?

**Comment by ashfurrow** [comment]
Awesome! Glad it's working. 

The warning is a [known issue](https://github.com/Quick/Quick/issues/146). I believe it can be ignored, but will defer to @modocache on this one.

**Comment by modocache** [comment]
Yeah, that warning began appearing in #277. I'd really love to get rid of it but it seems like it'll be there as long as we support iOS 7.0 deployment targets.

I think it's safe to ignore it, but if you know of a way to get rid of it altogether, please open a pull request! :+1:

**Comment by jboo1212** [comment]
Bump

- [X ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Pod installed Quick/Nimble using the installation guide.

### What did you expect to happen?

No build issues and to be able to run a test.

### What actually happened instead?

Frameworks not being included in the 'Frameworks' folder and the Pods > Frameworks > iOS path folder and thus not being able to run tests.  Running an empty test spits out this error in the log...

"
Showing Recent Messages
TestQuickTwoUITests-Runner.app (20931) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying error: The test runner failed to load the test bundle. Executable cannot be loaded for some other reason, such as a problem with a library it depends on or a code signature/entitlements mismatch.))
"

### Environment

List the software versions you're using:

 - Quick: *1.3.2*
 - Nimble: *7.3.1*
 - Xcode Version: *10.1 (10B61)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *Xcode Default*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.6.0* 

### Project that demonstrates the issue
N/A
