### ISSUE TITLE
Xcode keeps reporting failed test after it passed

### ISSUE THREAD

**Issue by evgenyneu** [Quick/Quick#294]
## How to reproduce

1) Write a test that fails by calling an `it` function.

```
it("fails") {
   expect(4) == 3
}
```

2) Run the tests. Xcode will indicate the failure, which is expected.

3) Change the test to make it pass **and** change the string argument of the `it` function **at the same time**.

```
it("passes") {
   expect(4) == 4
}
```

4) Run the tests.
## Expected behaviour

Xcode indicates that the tests passed.
## Actual behaviour

Xcode indicates that the test has failed. In the failure message it shows the results of the previous failure.

![xcode_test_failure](https://cloud.githubusercontent.com/assets/880411/7529462/6117cf00-f57c-11e4-9741-ae1e4abc992b.png)
## XCTest

XCTest does not have this problem after I rename the XCTest function and make it pass at the same time.
## Xcode version

Version 6.4 (6E14)

**Comment by modocache** [comment]
Once again, great bug report. Thanks a lot, @evgenyneu! :+1: 

I was able to reproduce this locally, although in my case, although Xcode *displays* a failure, the test suite succeeds, and Xcode displays a "Test Succeeded" overlay. Quitting and reopening Xcode makes the erroneous failure message disappear.

Unfortunately, like #293, I think this may also be a bug with how Xcode integrates with XCTest's dynamic invocations API. I'll keep this issue open as a reminder to file a radar.

**Comment by MichaelMcGuire** [comment]
`<khaaan_xcode_shatner.gif>`

**Comment by modocache** [comment]
Where's the "like" button on GitHub comments? :wink:

**Comment by istx25** [comment]
tbt when github didn't have reactions @modocache :P

**Comment by ikesyo** [comment]
Closing this as part of issue cleanup.
