### ISSUE TITLE
Carthage Archive

### ISSUE THREAD

**Issue by tibr** [Quick/Quick#296]
It would be great if you could attach [prebuilt framework archives](https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file) to the releases so that Carthage users don't have to build Quick locally which is especially useful to speed up CI builds.

I've created an archive for 0.3.1 using the latest Xcode version by running
```
carthage build --no-skip-current
carthage archive Quick
```

You can download it at https://github.com/rheinfabrik/Quick/releases/tag/v0.3.1

**Comment by jeffh** [comment]
Thanks Tim. I'll see if I get time to upload a binary later today.

**Comment by jeffh** [comment]
I've added a pre-built binary to v0.3.1. Let me know if you have any problems. Thanks!
