### ISSUE TITLE
Run tests using AppCode

### ISSUE THREAD

**Issue by priteshshah1983** [Quick/Quick#298]
Hi,
I'm not able to run any specs using AppCode. The "Run All" or "Debug All" menu options don't show up when I CTRL+CLICK (right-click). Please note that I can run the same specs using Xcode. I'm sure I'm missing something obvious.

Can someone please help?

Thanks.

**Comment by jeffh** [comment]
I don't really know the the underlying cause. Have you talked to the AppCode team about this?

**Comment by manumax** [comment]
You could create a configuration for testing. I usually work in that way using AppCode.

**Comment by priteshshah1983** [comment]
Thanks @manumax! I created a new Configuration (XCTest/Kiwi) with the following settings:
````
Name: All in MyQuickSpec.swift (could be anything though)
Test kind: Pattern
Pattern: MyQuickSpec
Target: MyTestTarget
`````

Any my tests are now running as expected! I wish AppCode could detect Quick specs like Kiwi specs.

**Comment by basharov** [comment]
@priteshshah1983, thanks, worked for me as well!
