### ISSUE TITLE
[Bug] Shared Example gets called with same context from within the same spec file

### ISSUE THREAD

**Issue by hffmnn** [Quick/Quick#299]
When calling `itBehavesLike` multiple times from within the same ObjC spec, the `sharedExamples` gets always called with the same context. Problem is, that the dynamically generated selector for the instance of the `Example` is always the same same.

https://github.com/Quick/Quick/pull/295 tries to fix this.

**Comment by modocache** [comment]
Thanks a ton for bringing this up, and for the proposed fix! :100:

**Comment by istx25** [comment]
Closing since this was addressed in #295.
