### ISSUE TITLE
Installing without submodule

### ISSUE THREAD

**Issue by potmo** [Quick/Quick#301]
Is it possible to add Quick without using git submodules or Pods etc?
I would like to just drag and drop the source in.

**Comment by jeffh** [comment]
We don't support it and I haven't tried it. YMMV. I don't think we could help much if there were problems. It's definitely not a route we would recommend.

You could also use Carthage or download the pre-built binary on the releases page. It makes it a lot simpler to pull in if that's what you're concerned about.

**Comment by modocache** [comment]
Using Git sumbodules is very similar to simply dragging and dropping in the source code--all it does is download the code into a specific folder. Alternatively, you can download the Quick source code, then drag and drop the Quick.xcodeproj into your Xcode workspace.

Hope that helps!
