### ISSUE TITLE
Examples with 'similar' names result in an unexpected behaviour

### ISSUE THREAD

**Issue by manumax** [Quick/Quick#306]
If you write two or more examples that produce the same test name (derived from `describe` and `it`) only one of them is actually executed (only the first one).

Example:

```swift
class QuickClashOfNamesSpec: QuickSpec {
    override func spec() {
        it("an example") {
            expect(true).to(beTruthy())
        }
        it("an.example") {
            expect(false).to(beTruthy())
        }
        it("an_example") {
            expect(false).to(beTruthy())
        }
    }
}
```

While Xcode reports it had run only one test (that makes it easy to spot a problem), both AppCode and  xctool reports they had run three tests.

I understand it is something that shouldn't happen, but when it does it's quite difficult to spot. The biggest problem here is that you could think all tests are passing, when they aren't. Shouldn't be the right thing to 'warn' about tests resulting in the same test?

**Comment by manumax** [comment]
Not sure, but it is probably related to #299.

**Comment by modocache** [comment]
This is an awesome bug. Thanks for reporting, @manumax! :100: :sparkles: 

Quick shouldn't allow this to happen, either by:

1. Giving each example has a unique name, by adding a unique identifier
2. Raise an exception when it encounters two examples with the same name

**Comment by modocache** [comment]
For what it's worth, I believe Specta avoids this by adding an index to the end of duplicate selector names. https://github.com/specta/specta/blob/42b8e0d8e28994abbf2012c76d980668b575a10d/Specta/Specta/SPTSpec.m#L100-L110

**Comment by romankl** [comment]
@manumax could you try the latest version from master? It contains a fix e67be524aff14fa6618e4cc57199813cc25b6011 (Swift-2.0) and e67be52 (Swift-1.2) that works around this bug by building a (probably) unique name.

**Comment by manumax** [comment]
@romankl I tried against e67be524aff14fa6618e4cc57199813cc25b6011 (Swift-1.2) with both Xcode and AppCode and it works like a charm!

**Comment by modocache** [comment]
I believe this issue is resolved. Thanks, everybody! :)
