### ISSUE TITLE
Quick functions should extern properly for Objective-C++

### ISSUE THREAD

**Issue by jeffh** [Quick/Quick#310]
For example:

```objective-c
extern void qck_beforeSuite(QCKDSLEmptyBlock closure);
```

This prototype definition is incorrect in (Objective-)C++ because of name mangling rules.

Instead,  we should replace the `extern` keyword with a macro like Foundation's

```objective-c
#if defined(__cplusplus)
#define FOUNDATION_EXTERN extern "C"
#else
#define FOUNDATION_EXTERN extern
#endif
```

Or just use `FOUNDATION_EXTERN` instead.

**Comment by marciok** [comment]
Hi, @jeffh I think I can help with this issue
 :wink:

**Comment by jeffh** [comment]
Feel free to submit a PR 😀

**Comment by modocache** [comment]
+1, this needs a fix!
