### ISSUE TITLE
Swift 2.0 Support: master, or 2.0 branch?

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#311]
A continuation of the discussion on https://github.com/Quick/Nimble/pull/131. Should we:

1. Support Swift 2.0 and the latest Xcode beta on the `master` branch. Create a branch named `swift-1.2` which will support Swift 1.2 and the latest stable release of Xcode.
2. Support Swift 1.2 and the latest stable release of Xcode on the `master` branch. Create a branch named `swift-2.0` which will support Swift 2.0 and the latest Xcode beta.

Comment with your preference, or any other feedback!

**Comment by esttorhe** [comment]
I'd say move `1.2` to its own branch and keep `master` with `2.0`.

Honestly it makes more sense because `2.0` is going to be the «latest official» `Swift` and makes more sense to keep `master` up to date.

IMHO ¯\_(ツ)_/¯

**Comment by aarondaub** [comment]
2.0 should be a branch until it is out of beta

**Comment by MarcoSero** [comment]
I lean towards n.2 but setting the default Github branch to `swift-2.0`, the way ReactiveCocoa has done for their v3.

**Comment by esttorhe** [comment]
Yeah; I guess that's what I meant to move it to `master` (when is out of «beta»).

**Comment by dimsumthinking** [comment]
Agreed

**Comment by twobitlabs** [comment]
+1 for branch while its in beta.

**Comment by fabiomassimo** [comment]
+1 for "branch it until it's beta"

**Comment by modocache** [comment]
@Quick/contributors?

**Comment by ashfurrow** [comment]
I like number 2 – keep it on a branch until it's out.

**Comment by paulyoung** [comment]
Part of me is all "YOLO" but generally I like to keep master able to deploy the latest stable version of a project.

**Comment by modocache** [comment]
Sounds good--thanks for the input, everybody! We'll be maintaining Swift 2.0-compatible releases on branches named `swift-2.0`. As usual, **don't** depend on a specific branch of Quick or Nimble in your project! Instead, use our releases (which we will tag).

For Quick, Swift 1.2-compatible releases will continue to be tagged `v3.*`. Swift 2.0-compatible releases will be tagged `v4.*`. We're still deciding version numbers for Nimble--follow the discussion in https://github.com/Quick/Nimble/pull/131 and https://github.com/Quick/Nimble/pull/132.
