### ISSUE TITLE
#asynctest - How to test the data returned by block?

### ISSUE THREAD

**Issue by selcukyucel** [Quick/Quick#319]
My problem is to test if my get service is working or not? 

I wonder how to set and get variable of test class? and how to test it? (async)

As you see in the code t_items is variable of test class.When I test it it FAILS.

But when I test the t_items variable in my service (production class) It PASSES I set this t_items var in production class but I don't need & want it.

Why would't I get my data returned by block? What do I miss?

Thanks

![screenshot 2015-06-15 20 34 25](https://cloud.githubusercontent.com/assets/265463/8168893/fe67d3b0-139d-11e5-8654-eafb0e54bf7a.png)

**Comment by jeffh** [comment]
Hey @selcukyucel, what's the type of `t_items`?

And what version of Xcode / Swift are you using?

**Comment by selcukyucel** [comment]
Hey @jeffh Xcode 6.3.2 / Swift 1.2
and t_items var in test class is NSMutableArray
t_items var in service class(production class) is NSNumber. I set it in production class through data returns from server. There are 3 objects turn back from request. That's What I am checking just to see it service works.

**Comment by jeffh** [comment]
I was wondering if t_items is of type NSMutableArray! instead of NSMutableArray? which would be a possible culprit of the nil unwrapping aborting.

Could you post the full code of the test?

**Comment by jeffh** [comment]
[Ping] @selcukyucel, are you still having issues? Could you post the full code of the test?

**Comment by jeffh** [comment]
Closing. Please reopen or refile an issue if you're still having problems. Thanks.
