### ISSUE TITLE
Can't install Quick via Carthage under Xcode 7?

### ISSUE THREAD

**Issue by ratkins** [Quick/Quick#325]
I created a brand new Swift project in Xcode 7 and followed the [installation instructions](https://github.com/Quick/Quick/blob/swift-2.0/Documentation/InstallingQuick.md). But when I try and `import Quick` at the top of the default FooTests.swift file, Xcode complains `No such module 'Quick'`.

Has anyone personally had success importing Quick as a framework in Xcode 7 via Carthage?

**Comment by jeffh** [comment]
Hey @ratkins, did you change your CLI tools to use Xcode 7?

https://github.com/Carthage/Carthage/issues/536

**Comment by ratkins** [comment]
Yes I did.

It builds with a couple of warnings (`embedded dylibs/frameworks only run on iOS 8 or later` and `URGENT: all bitcode will be dropped`) but no errors. And still `No such module...`.

**Comment by jeffh** [comment]
Do you have a sample project? What does your cartfile look like?

**Comment by ratkins** [comment]
Cartfile is pretty simple:

    github "Quick/Quick"

[Here is a repo](https://github.com/ratkins/BroDoYouEvenFrameworkXcode7) demonstrating the problem.

**Comment by ratkins** [comment]
As a follow-up, I've just tried rebuilding with Xcode 7 beta 2 and get the same result.

**Comment by MichaelMcGuire** [comment]
Dragging the framework from Carthage into the "Link Binary with Libraries" area under "Build Phases" of the unit test target does not appear to update the Framework search path of the unit test project.  If you go into the "BroDoYouEvenFrameworkXcode7Tests" target under "Build Settings" and search for "Framework Search" in the upper right hand corner, you can add "$(PROJECT_DIR)/Carthage/Build/iOS" to your target.  That got it to compile and run the tests for me.

**Comment by jeffh** [comment]
Thanks @ratkins. It's some more strict compiler settings carthage runs under is causing the issues. I've made a PR #336 to fix this.

**Comment by ratkins** [comment]
@MichaelMcGuire I've made it work by adding that framework search path as you suggest, but shouldn't this be unnecessary if you add the "Copy Files" phase as suggested by steps 4 and 5 of the Carthage installation instructions?

And @jeffh, should #336 obviate the need for both adding to the frameworks search path and the "copy files" phase?

**Comment by MichaelMcGuire** [comment]
@ratkins I would think so?  I'm not entirely sure how #336 relates to this, but I hope it fixes it
