### ISSUE TITLE
Is it possible to nest async tests?

### ISSUE THREAD

**Issue by i-schuetz** [Quick/Quick#327]
I'm testing web service calls, using Alamofire. My test of a service depends on the response of another. I tried to put the tests in the handler callback but they don't seem to be executed. Is this not possible?

**Comment by jeffh** [comment]
Hey @i-schuetz, do you have an example to explain what you're expecting / problem?

Nimble dispatches back to XCTest for assertion handling, so it should be safe to use on other threads.

That being said, if you're not careful, it's easy for an example to finish before an async block finishes, making it unsafe to have assertions in the handler. The example needs to block in until async code finishes (through `toEventually` or `waitUntil`).

**Comment by i-schuetz** [comment]
waitUntil would be what I need (I looked for it in the Quick documentation, was not clear that this would be in Nimble).

But it doesn't seem to work anyway. Here's an example:

```swift
    override func spec() {
        describe("foo") {            
            it("bar") {                
                waitUntil(timeout: 5) {done in
                    self.remoteProvider.removeAll {try in                        
                        expect(try.success).notTo(beNil())
                        println("!!!!!!!!!!!!!!!!!!!!!")
                        
                        it("nested") {
                            self.remoteProvider.lists{try in
                                println("???????????????")
                                done()
                            }
                        }
                    }
                }
            }
        }
    }
```

The ??????????????? is not printed and it fails with "Waited more than 5.0 seconds"

The same example works with XCTest:

```swift
    func test() {
        var expectation = self.expectationWithDescription("add lists")        
        self.remoteProvider.removeAll {try in        
            expect(try.success).notTo(beNil())
            println("!!!!!!!!!!!!!!!!!!!!!")
            
            println("nested")
            self.remoteProvider.lists{try in            
                println("???????????????")
                expectation.fulfill()
            }
        }
        
        self.waitForExpectationsWithTimeout(5.0, handler: nil)
    }
```

Maybe I'm missing something?

**Comment by jeffh** [comment]
It blocks can't be nested. Each example (it) corresponds to a test method in xctest.

**Comment by i-schuetz** [comment]
Makes sense. My actual problem was the missing waitUntil - the nested it was a mistake preparing the examples to post here...  It's fixed now, thanks.
