### ISSUE TITLE
Output which examples are *not run* when focused examples exist

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#332]
https://github.com/specta/specta/issues/166 is a good idea--Quick should do the same.

**Comment by istx25** [comment]
Is this something we're still interested in doing?

**Comment by modocache** [comment]
Yeah, I think this would be rad.

**Comment by nikolaykasyanov** [comment]
I believe nowadays a potential implementation of this feature request could use the now built-in skipped test reporting: #1098.
