### ISSUE TITLE
Problems with swift 2.0

### ISSUE THREAD

**Issue by geekgirl4** [Quick/Quick#334]
I migrated my project to new swift 2.0.

Then I updated the pods. Only having problems with Quick.
The podfile is like this: pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'swift-2.0'

When i build I get: 'Quick/Quick-Swift.h' file not found.

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "...Quick-umbrella.h"
        ^
...Quick-umbrella.h:6:9: note: in file included from ...Quick-umbrella.h:6:
#import "World.h"
        ^
...Pods/Quick/Quick/World.h:1:9: error: 'Quick/Quick-Swift.h' file not found
#import <Quick/Quick-Swift.h>
        ^
<unknown>:0: error: could not build Objective-C module 'Quick'

**Comment by nikita-leonov** [comment]
I do have the same with ObjC project that use Quick in the same way. It is not Xcode issue as version 7 used. I recently found that that 2.0.0 quick and 0.4.0 nimble is already available in pods, byt I didn't tried to install it not from the branch yet. I am going to check it soon, hopefully it may help.

**Comment by nikita-leonov** [comment]
I just checked, Installing from latest tag for swift 2.0 cause the same issue with swift.h as from branch.

**Comment by jeffh** [comment]
Whoops, accidentally clicking buttons.

**Comment by jeffh** [comment]
Hey @geekgirl4, thanks for filling.

I've pushed the fixed podspec on the `swift-2.0` branch. Try it out and let me know if it works for you.

**Comment by jeffh** [comment]
You might come across compilation failures, running the swift syntax migrator is a workaround until PR #336 is merged.

**Comment by jeffh** [comment]
I merged this into master. Let me know if this is still an issues. Thanks for filing the issue! :+1:

**Comment by geekgirl4** [comment]
It's working now, thanks :)
