### ISSUE TITLE
Unable to compile a simple project after cocoapods install

### ISSUE THREAD

**Issue by brianvoong** [Quick/Quick#340]
I can't for the life of me get a basic project compiled after installing quick via cocoapods. Can someone shine some light on my dire situation?

# Podfile

link_with 'quickTests'

use_frameworks!
pod 'Quick'
pod 'Nimble'

![image](https://cloud.githubusercontent.com/assets/8883574/8460333/a32b992c-1fd8-11e5-8815-faf3256472b5.png)

**Comment by jeffh** [comment]
Hey @brianvoong, what version of Xcode are you using?

The latest release of Quick (0.4.0) is for Swift 2 (Xcode 7), but the latest Nimble (1.0.0) is for Swift 1.2 (Xcode 6).

If you want Xcode 6 do:

```
use_frameworks!
pod 'Quick', '~>0.3.0'
pod 'Nimble', '~>1.0.0'
```

Otherwise for Xcode 7:

```
use_frameworks!
pod 'Quick', '~>0.4.0'
pod 'Nimble', '2.0.0-rc.1'

# or bleeding edge:
#pod 'Quick', :git => 'https://github.com/quick/quick.git', :branch => 'swift-2.0'
#pod 'Nimble', :git => 'https://github.com/quick/nimble.git', :branch => 'swift-2.0'
```

**Comment by jeffh** [comment]
Closing issue, please reopen if you're still having problems. Thanks!
