### ISSUE TITLE
Build problem: Falsely expects XCTest to contain bitcode

### ISSUE THREAD

**Issue by AkuTaku** [Quick/Quick#343]
After updating to Xcode 7 beta 3, I needed to update carthage where building of Quick-iOS failed. It seems to think that bitcode is enabled for XCTest, but that is not something I can change, none of my targets have bitcode enabled. Terminal displayed the following:

The following build commands failed:
	.../Library/Developer/Xcode/DerivedData/Quick-gsekzduxfwjnxhcekdlhnygnrmpn/Build/Intermediates/Quick.build/Release-iphoneos/Quick-iOS.build/Objects-normal/arm64/Quick normal arm64

(1 failure)
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later

ld: warning: Auto-Linking supplied '/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest', '/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.

**Comment by pcantrell** [comment]
Same problem here. The issue headline should perhaps be “Quick does not build on Xcode 7 beta 3.”

All the logged message are warnings and not errors, so it’s not clear why the build is failing. The thing about XCTest bitcode may not even be the problem. Relevant Carthage output:

    *** Building scheme "Quick-iOS" in Quick.xcworkspace
    ** BUILD FAILED **


    The following build commands failed:
        Ld /tmp/Xcode/DerivedData/Quick-bnexfyjqkvltxkawlrdflszahwaz/Build/Intermediates/Quick.build/Release-iphoneos/Quick-iOS.build/Objects-normal/arm64/Quick normal arm64
    (1 failure)
    ld: warning: directory not found for option '-F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/Developer/Library/Frameworks'
    ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
    ld: warning: directory not found for option '-F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/Developer/Library/Frameworks'
    ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
    ld: warning: directory not found for option '-F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'
    ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
    ld: warning: ignoring file /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/XCTest, missing required architecture armv7 in file /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/XCTest (2 slices)
    ld: warning: directory not found for option '-F/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'
    ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
    ld: warning: ignoring file /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/XCTest, missing required architecture arm64 in file /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/XCTest (2 slices)
    ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
    ld: warning: Auto-Linking supplied '/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest', '/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.
    ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
    ld: warning: Auto-Linking supplied '/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest', '/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    A shell task failed with exit code 65:
    ** BUILD FAILED **


    The following build commands failed:
        Ld /tmp/Xcode/DerivedData/Quick-bnexfyjqkvltxkawlrdflszahwaz/Build/Intermediates/Quick.build/Release-iphoneos/Quick-iOS.build/Objects-normal/arm64/Quick normal arm64
    (1 failure)

**Comment by pcantrell** [comment]
Ah, indeed, carthage was suppressing the message. `carthage build --verbose` reveals the culprit:

    Undefined symbols for architecture armv7:
      "_OBJC_METACLASS_$_XCTestCase", referenced from:
          _OBJC_METACLASS_$_QuickSpec in QuickSpec.o
      "_OBJC_CLASS_$_XCTestCase", referenced from:
          _OBJC_CLASS_$_QuickSpec in QuickSpec.o
    ld: symbol(s) not found for architecture armv7

**Comment by pcantrell** [comment]
I take it back, @AkuTaku: you were right, the bitcode was the problem, and #342 fixes this for me.

**Comment by jeffh** [comment]
Hey @AkuTaku I merged the fix, thanks @pcantrell for investigating :). After my Xcode Server says it's also good I'll be cutting a release.
