### ISSUE TITLE
Carthage install documentation missing step?

### ISSUE THREAD

**Issue by anandabits** [Quick/Quick#347]
I followed the Carthage install documentation in the Swift-2.0 branch (I'm using Xcode 7 beta 3) and kept getting a linker error: "ld: framework not found Nimble".

Adding "$(SRCROOT)/Carthage/Build/iOS" to the FRAMEWORK_SEARCH_PATHS build setting of my test target solved the issue.

I'm wondering if this was just an omission in the documentation or if this setting should not be necessary (maybe this is an Xcode beta issue?).

**Comment by saggymac** [comment]
FWIW, I did the same thing.

**Comment by ikesyo** [comment]
To drag & drop frameworks to a project adds the frame work search paths automatically in Xcode 6, but in Xcode 7 beta it does not. So it seems to me that is an Xcode beta isuue.

**Comment by mokagio** [comment]
@ikesyo I agree with you, but regardless whose fault it is proper instructions should be provider right?

**Comment by mokagio** [comment]
This is no longer an issue in Xcode 7 Beta 4 (see #352). Maybe we can close this issue /cc @jeffh?

**Comment by jeffh** [comment]
Closed. Thanks for the discussions guys!

**Comment by aral** [comment]
This is still an issue with Xcode 7.0.1 (I just ran into it) and @anandabits’s advice solved it.
