### ISSUE TITLE
Test failed without executing

### ISSUE THREAD

**Issue by skyylex** [Quick/Quick#351]
Hello.
I'm trying to use Quick 0.3.1 and Swift, compiling with Xcode 6.4 (6E35b). At first, Xcode doesn't see any test Spec. And on each try I get Test failed, without actually running. Xcode says:

     Test target AlecrimCoreData Tests encountered an error (Test session exited(1) without checking in. 
     If you believe this error represents a bug, please attach the log file at ...

I've tried to reopen and clean Derived Data, remove and add Quick/Nimble frameworks multiple times in different combinations without any success.

**Comment by jeffh** [comment]
Hey @skyylex,

Do you have some sample code that you're trying to compile? What version of Nimble are you using? Are you using cocoapods, carthage, or installing it manually?

**Comment by skyylex** [comment]
[Here](https://github.com/skyylex/AlecrimCoreData) the repo and "feature/unit-tests" branch (Cartfile located in the /Source folder). I'm using Carthage to build Quick and Nimble frameworks for "AlecrimCoreData Tests" target. Carthage downloaded and built Nimble with 1.0.0 version.

**Comment by manumax** [comment]
I gave it a try and I managed to have tests working again by removing the frameworks from `Link Binary With Libraries` in the Tests target and adding them to a new `Copy Files` phase. Hope it helps.

![screen shot 2015-07-24 at 10 40 25](https://cloud.githubusercontent.com/assets/6240851/8870732/76b8c94e-31f0-11e5-95f8-06963ebe53e1.png)

**Comment by skyylex** [comment]
Thank you very much, I skipped this step.

**Comment by paulyoung** [comment]
I was experiencing this exact issue and this worked for me: https://github.com/Quick/Quick/issues/141#issuecomment-138997319
