### ISSUE TITLE
Unable to get 0.3.x through CocoaPods

### ISSUE THREAD

**Issue by abbeycode** [Quick/Quick#356]
I'm trying to use Quick for the first time in the unit tests of a project. This is the project's first use of CocoaPods as well (aside from publishing a `podspec`), and it is not yet on Swift 2.0. I have a very basic podfile:

```none
use_frameworks!

target 'UnzipKitTests' do
    pod 'Quick', '~> 0.3.0'
end
```

When I call `pod install`, I'm getting the following error:

```none
[!] Unable to satisfy the following requirements:

- `Quick (~> 0.3.0)` required by `Podfile`
```

I'm using the example from the Readme almost verbatim, and I see that there is a tag for `0.3.1`, as well as documentation on CocoaDocs, so it definitely should work. Also, `0.5.0` works as well, but obviously doesn't compile. I tried clearing the CocoaPods caches of the pod and podspec as well, to no avail.

What am I missing?

**Comment by abbeycode** [comment]
Oh, I had to specify 10.10 as the platform target:

```none
platform :osx, '10.10'

use_frameworks!

target 'UnzipKitTests' do
    pod 'Quick', '~> 0.3.0'
end
```

**Comment by jeffh** [comment]
Thanks for posting the fix to your issue! :+1:
