### ISSUE TITLE
Error when the context, describe, it, beforeEach, afterEach are used incorrectly

### ISSUE THREAD

**Issue by jeffh** [Quick/Quick#362]
Background: #357 

Quick should raise an error (using ~~`fatalError`~~ `NSException`) when any of the DSL functions are used incorrectly:

- [ ] Using `it` inside `beforeEach`
- [ ] Using `it` inside `afterEach`
- [ ] Using `afterEach` inside `it`
- [ ] Using `beforeEach` inside `it`
- [ ] Using `context` inside `it`
- [ ] Using `describe` inside `it`
- [ ] Using `it` inside `it`

An error message should look like:

> 'afterEach' cannot be used inside 'it', 'afterEach' may only be used inside 'context' or 'describe'. (/Users/../exampleTest.swift:45)

**Comment by briancroom** [comment]
This was completed by #448. Thanks @jeffh and @jwfriese!
