### ISSUE TITLE
Can we make one test case dependent on other in Quick/nimble.

### ISSUE THREAD

**Issue by Nikunja6** [Quick/Quick#368]
Suppose I have two test cases- AB() and CD() and if I want to execute the test CD() only if AB() is passed.
Do we have this capability in Quick/Nimble.
Please provide an example.

**Comment by jeffh** [comment]
Sorry @Nikunja6, Quick doesn't support this feature. Maybe it's just me, but I can't imagine needing this kind of capability that couldn't be done through other means. Could you provide an example of your use case?

**Comment by DanielAsher** [comment]
@jeffh a `Promise`-like capability could deal with this use case e.g:
```
expect(dataReady).toEventually(beTrue)
.success { result in expect(button.position).toEventually(equal(firstCharacter.position)) }
.failure { error in doSomethingElse() }
```

**Comment by jeffh** [comment]
I'm not sure if this is any different from just having multiple assertions inside an `it` example. It's just adding some syntax without really adding anything.

**Comment by modocache** [comment]
This reminds me of [JUnit assumptions](https://github.com/junit-team/junit/wiki/Assumptions-with-assume), which allow you to specify conditions under which tests should run.

I don't personally use them, and I don't think I want to add them to Quick itself--sorry, @Nikunja6! :bow: 

It would be interesting this as a third-party extension to Quick, though. I'll close this issue in favor of #394.
