### ISSUE TITLE
Xcode 7 beta 5/6 compiler crash

### ISSUE THREAD

**Issue by keith** [Quick/Quick#369]
With Xcode 7 beta 5 we started getting crazy compiler crashes that I can only seem to reproduce when using Quick/Nimble for tests. I've written up a radar which can be found [here](http://www.openradar.me/22441425) (with an example project). Feel free to close this but I wanted to file it in case other reports came in.

**Comment by jeffh** [comment]
Thanks for writing up this issue @keith.

Since beta 5, the swift type checker has seem to undergone an overhaul that causes a lot of issues (like inferring type of the argument in a closure for `throwsError` or `raisesException` matchers). A temporary work around is to be more explicit in types:

```swift
expect("foo".example() as String).to(equal("example"))
```

**Comment by jeffh** [comment]
Labelled as `wontfix` since this is more of an issue for Apple. I've filed a radar for the equivalent versions for `throwsError` and `raisesException`.

**Comment by keith** [comment]
Sounds good! We also worked around this by assigning a temporary variable. We can close this now too if you'd like.

**Comment by jeffh** [comment]
Thanks, closing.
