### ISSUE TITLE
regarding description on tag/v0.6.0

### ISSUE THREAD

**Issue by KazuCocoa** [Quick/Quick#371]
Hi @jeffh 

Very tiny pointing out.

You described "v0.6.0 targets Xcode 6 beta 6 / Swift 2.0" on release tag.
https://github.com/Quick/Quick/releases/tag/v0.6.0

Does **Xcode 6 beta 6** means **Xcode 7 beta 7** ?

**Comment by ikesyo** [comment]
__Xcode 7 beta 6__ seems correct.

**Comment by KazuCocoa** [comment]
yes. its my mistake :cry:  > beta 7

**Comment by jeffh** [comment]
Yep, the latest is still Xcode 7 beta 6. It seems correct to me, closing.

Thanks for filing, @KazuCocoa! And thanks for the fast reply @ikesyo!
