### ISSUE TITLE
Generic ObjC subclasses

### ISSUE THREAD

**Issue by jedlewison** [Quick/Quick#372]
I'm having in issue that I think, but am not sure, may be related to generic objc subclasses.

When using Quick/Nimble to test a generic objc class, I *always* get a crash after the first example runs. Making the class be non-generic fixes the crash. I'm able to test the class using a plain old XCTestCase subclass, but then of course I want to gouge my eyes out because Quick and Nimble make tests so much easier to read and maintain.

Anyway, the call stack leads up to this:

```
+ (SEL)addInstanceMethodForExample:(Example *)example {
    IMP implementation = imp_implementationWithBlock(^(QuickSpec *self){
        currentSpec = self;
        [example run]; // <-- crash
    });
```

I haven't looked too deeply into this, wanted to flag in case there are any known workarounds, or if it's unlikely that my supposition is correct about the issue being use of a generic objective c subclass.

(It's a subclass of NSOperation, so making it a swift-only class or a struct is not an option.)

**Comment by jeffh** [comment]
Hey @jedlewison,

This is an interesting bug worth investigating. Are you using the Swift or Objective-C APIs for Quick? What version of Quick / Nimble are you using?

**Comment by jedlewison** [comment]
Swift-only and I'm using the testable import directive option. I'm using the swift-2.0 branches -- here are the commits:

```
CHECKOUT OPTIONS:
  Nimble:
    :commit: 703a7ae786b4dcb00c6eaa65156cc2da9ab4be8f
    :git: https://github.com/Quick/Nimble.git
  Quick:
    :commit: e96584ddc96b07b5b6577ac81bf2314aa460ca2b
    :git: https://github.com/Quick/Quick.git
```

Check out #21342574 in [the latest Xcode 7b6 release notes](http://adcdownload.apple.com/Developer_Tools/Xcode_7_beta_6/Xcode_7_beta_6_Release_Notes.pdf). I have a feeling that might be related. If so, it might just be impossible to do this using calls into ObjC.

**Comment by jedlewison** [comment]
I can confirm that it is possible to test generic NSObject subclasses within quick and nimble—I couldn't reproduce the issue with a very basic generic NSObject subclass that basically just boxed a generic property.

I'm still having an issue with the NSOperation subclass, but I'm optimistic that there will be a workaround given that the simple NSObject subclass worked. I'll keep you posted.

**Comment by jedlewison** [comment]
Hey @jeffh, I'm going to close this. I think it was a combination of user error and the compiler letting me get away without providing enough type information—basically I was testing a subclass of the generic subclass, and didn't adorn the second subclass with type information. Even if I shouldn't have to do that, doing it makes the crash go away. I'm still not entirely sure exactly what was going on, but since generic subclasses of NSObjects definitely do work with Quick and Nimble, I'll close the ticket. I'll follow up if there's anything more useful.

**Comment by jeffh** [comment]
Sounds good to me, thanks for the follow up comments, @jedlewison.

**Comment by jedlewison** [comment]
To erase the small amount of wiggle room I left in my last comment, I can now 100% confirm that the issue was entirely my fault. Quick/Nimble works beautifully with async test of generic subclasses of NSObjects. Sorry for the false alarm, and thanks for Quick/Nimble!
