### ISSUE TITLE
Typo on release v0.6

### ISSUE THREAD

**Issue by phatblat** [Quick/Quick#375]
> v0.6.0 targets Xcode 6 beta 6 / Swift 2.0

Should say "Xcode **7** beta 6"

**Comment by jeffh** [comment]
Whoops. My bad again. Thanks for the catch!




—

**Comment by modocache** [comment]
Looks like @jeffh edited the release and fixed the typo. Thanks to both of ya! :100:

**Comment by jeffh** [comment]
No credit to me, redirect thanks to @paulyoung :smile:
