### ISSUE TITLE
Quick not deploying to device in Xcode 7 beta 6: ENABLE BITCODE setting issue

### ISSUE THREAD

**Issue by zbeckman** [Quick/Quick#376]
We are seeing the linker failure with "must ENABLE BITCODE" error showing up in Xcode 7 beta 6, with the latest pull from the Quick "swift-2.0" branch (Quick 0.5.1). We've reproduced this on 3 different machines today. See the attached screenshot, but the relevant error during the link phase is:
```
.../XCTest' does not contain bitcode. You must rebuild it with botched enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable botched for this target. for architecture arm7
```
We are using the following pod:
```
  pod "Quick", :git => 'https://github.com/Quick/Quick.git', :branch => 'swift-2.0'
  pod "Nimble", :git => 'https://github.com/Quick/Nimble.git', :branch => 'swift-2.0'
```
I believe this is the same bug that bit Nimble... now biting Quick: https://github.com/Quick/Nimble/issues/170

Here's a screenshot that demonstrates the deployment issue (again, only seems to occur when we deploy to a hard device):

![glimpulse_xcworkspace](https://cloud.githubusercontent.com/assets/5351337/9616579/c4662b6e-50b3-11e5-8a71-d92c1c94facb.png)

**Comment by danielbyon** [comment]
Was getting the same error. I manually disabled bitcode for the Quick target in my Pods project, and it compiled.

I believe the permanent fix is to put the ENABLE_BITCODE=false into the pod spec?

![screen shot 2015-09-03 at 1 42 47 am](https://cloud.githubusercontent.com/assets/327737/9654088/1afe7a1a-51dd-11e5-9e8a-eef07960912f.png)

**Comment by ikesyo** [comment]
#378 is submitted.

**Comment by jeffh** [comment]
Yeah, sorry guys. I forgot that I needed to apply to change to Quick too. Thanks for the PR. It's been merged. :+1:
