### ISSUE TITLE
Support Swift.Dictionary in Shared Examples

### ISSUE THREAD

**Issue by abbeycode** [Quick/Quick#377]
I'm trying to pass structs into a shared example context, but I get:

> '[String: MyStruct]' is not convertible to 'NSDictionary'

It would be great if there were an overload of `itBehavesLike()` that took a different type of context, backed by a `Swift.Dictionary` instead of `NSDictionary` (even though it would be Swift-only.

**Comment by manumax** [comment]
Is this maybe related to #153?

**Comment by abbeycode** [comment]
@manumax yes! I missed that one. Thanks.
