### ISSUE TITLE
[Objective-c] KIF and Quick/Nimble 

### ISSUE THREAD

**Issue by tomomura** [Quick/Quick#380]
I found that I had to add a category to Quick's `QuickSpec`

```objc
@interface QuickSpec (WithObjC) <KIFTestActorDelegate>

@end
```

```objc
@implementation QuickSpec (WithObjC)

- (void)failWithException:(NSException *)exception stopTest:(BOOL)stop
{
  self.continueAfterFailure = !stop;
  [self recordFailureWithDescription:exception.description
                              inFile:exception.userInfo[@"SenTestFilenameKey"]
                              atLine:[exception.userInfo[@"SenTestLineNumberKey"] integerValue]
                            expected:YES];
}

- (void)failWithExceptions:(NSArray *)exceptions stopTest:(BOOL)stop
{
  NSException *lastException = exceptions.lastObject;
  for (NSException *exception in exceptions) {
    [self failWithException:exception stopTest:(exception == lastException ? stop : NO)];
  }
}
```

```objc
QuickSpecBegin(LoginViewSpec)

describe(@"this is describe block", ^{
  it(@"this test is example", ^{
    [tester enterText:@"user@example.com" intoViewWithAccessibilityLabel:@"Login User Name"]; // not exist
  });
});

QuickSpecEnd
```
but, all examples is executed.
is it possible to use Quick with KIF?

Thanks for the help.

* Xcode 6.3.2
* iOS 7 or later
* Quick 0.3.1
* Nimble 1.0.0

**Comment by modocache** [comment]
Thanks, @tomomura!

> is it possible to use Quick with KIF?

I don't have a ton of experience using KIF, but if there's anything Quick can do to support it I'd like to do so--provided Quick can do so without requiring KIF as a dependency.

> I found that I had to add a category to Quick's `QuickSpec`

Can you explain this a bit more? Why is this category necessary? How does KIF work differently with "normal" `XCTestCase` objects?

**Comment by jeffh** [comment]
I'm closing this issue (won't fix).

KIF requires you to inherit its `XCTestCase` subclass. In addition, KIF extends XCTestCase which leads me to believe they're doing some hacks around XCTest (like Quick does).

That being said, I've only glanced at the KIF code, but that's my impression.

Thanks for filling @tomomura!
