### ISSUE TITLE
Support tvOS

### ISSUE THREAD

**Issue by brentleyjones** [Quick/Quick#381]
Like https://github.com/Quick/Nimble/pull/183.

(I don't use Quick, which is why I'm not just adding this myself.)

**Comment by modocache** [comment]
Thanks, @brentleyjones! I'm currently downloading the latest version of Xcode. If you'd like to submit a PR in the meantime (even if you don't use Quick), that'd be much appreciated! :100:

**Comment by garnett** [comment]
I've added the same changes, but still do not see appletv in devices list to verify if it actually works, @brentleyjones how did you manage to run tests on tv as destination?

**Comment by brentleyjones** [comment]
TARGETED_DEVICE_FAMILY and SUPPORTED_PLATFORMS were the key. Also, of course, Xcode 7.1 beta.

**Comment by garnett** [comment]
@brentleyjones I've changed them :cry: Using beta 2 on 10.10

**Comment by modocache** [comment]
@garnett Is #396 ready to go, or does it not work yet? :8ball:

**Comment by garnett** [comment]
@modocache now it's ready! however I had to update Nimble submodule to latest version

**Comment by modocache** [comment]
Fantastic! Merged. Thanks, everyone! :100:
