### ISSUE TITLE
Swift 2 support

### ISSUE THREAD

**Issue by keith** [Quick/Quick#382]
Now that the GM is released can the swift 2 branch be merged into master and a new release be made?

Thanks!

**Comment by modocache** [comment]
Seems like a good idea to me! I can do this sometime after Tuesday of this week, but if any other contributor wants to do so (or has objections) let me know! :+1:

**Comment by keith** [comment]
I can submit this PR from a fork if that would be useful.

**Comment by keith** [comment]
Submitted here: https://github.com/Quick/Quick/pull/386

**Comment by modocache** [comment]
Taken care of in #390. Thanks, @keith! :bouquet:
