### ISSUE TITLE
OCMockito test failure not reported

### ISSUE THREAD

**Issue by jonreid** [Quick/Quick#384]
I created a FooSpec.m:

    @interface FooSpec : QuickSpec
    @end
    
    @implementation FooSpec
    
    - (void)spec
    {
        it(@"should verify mock array", ^{
            NSMutableArray *mockArray = MKTMock([NSMutableArray class]);
    
            [mockArray addObject:@"FOO"];
    
            [MKTVerify(mockArray) addObject:@"BAR"];
        });
    }
    
    @end

I confirmed that `-recordFailureWithDescription:inFile:atLine:expected:` is called on QuickSpec. But then, nothing…

**Comment by modocache** [comment]
Probably related to an open issue regarding using XCTest assertions from within Objective-C specs. I'll find the issue number and post here.

**Comment by modocache** [comment]
Hmm, the issue I was referring to was #121, but that was fixed in #328. @jonreid, can you confirm the commit with the fix is included in the version of Quick you're using?

**Comment by modocache** [comment]
@objczl, which versions of Quick, Nimble, and OCMockito are you using?

**Comment by jonreid** [comment]
Ah. Downloaded the Xcode GM seed and used v0.6.0. All is well, sorry to trouble you.
