### ISSUE TITLE
Decouple Quick from XCTest

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#385]
> I'll flesh this issue out with details later, but tl;dr: Quick should be able to run tests without using XCTest, and provide a separate integration layer for XCTest.

**Comment by jeffh** [comment]
More details @modocache?

There's some features worth noting to get or design to support:

- #358 - support a test reporter that can capture test results.

**Comment by istx25** [comment]
I'd love to hear more about this. Seems interesting. @modocache, mind sharing more details?

**Comment by modocache** [comment]
I don't really remember my exact plans... 😅 Also, I think this is less useful now that swift-corelibs-xctest exists. That library allows tests written using the XCTest APIs to be run on non-macOS environments, and as a result I'm not sure what the benefit of decoupling would be.

I'll close this for now. Sorry for the lack of details at the time!

**Comment by istx25** [comment]
No problem. Sounds good to me.
