### ISSUE TITLE
Prettier test method names in output

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#392]
#295 added file names and line numbers to test method names, which I consider to be aesthetically unpleasant. It would be great to make sure tests with identical names do not clash, but produce test output that doesn't affix file names or line numbers.

Perhaps only append file names or line numbers where clashes occur, but leave the test names alone otherwise?

**Comment by jeffh** [comment]
I think only post fixing a number if a conflict occurred would be the least intrusive change. Otherwise I agree that simplifying the test names

**Comment by brentleyjones** [comment]
When I noticed the file name and line numbers I thought it was a bug. They are so ugly now :(

**Comment by abbeycode** [comment]
Agreed. For me, it's more about the absurd length (on top of already verbose names), and the end being all you can often see in the test navigator. Look at this from an Xcode Bot build in-progress:

<img width="1421" alt="Screenshot of bot test name" src="https://cloud.githubusercontent.com/assets/1349578/12075292/9f8a74e8-b149-11e5-976f-2ee198a4ca5f.png">

**Comment by modocache** [comment]
A pull request would be much appreciated here! I believe a solution could be achieved by storing the name of each test selector in a set (stored on the shared `World` instance). If a selector already exists in the set, add an incrementing `1`, `2`... to its name.




On Sat, Jan 2, 2016 at 9:09 AM -0800, "Dov Frankel" <notifications@github.com> wrote:












Agreed. For me, it's more about the absurd length (on top of already verbose names), and the end being all you can often see in the test navigator. Look at this from an Xcode Bot build in-progress:

**Comment by jeffh** [comment]
I don't think there needs to be any global state. We can check when creating all the test methods for each `QuickSpec` subclass.

**Comment by modocache** [comment]
@abbeycode fixed this in #462. I'll release a new version soon, then close this issue. :wave:

**Comment by NachoSoto** [comment]
I'm so excited for this :cl

**Comment by abbeycode** [comment]
Should we close this issue out?

**Comment by modocache** [comment]
Yup! Thanks for the reminder, @abbeycode!
