### ISSUE TITLE
Quick/Nimble will build but not test under carthage or cocoa pods

### ISSUE THREAD

**Issue by thecb4** [Quick/Quick#395]
Getting the following error

"Include of non-modular header inside framework module Quick"

Xcode: Version 7.0 (7A220)

Cartfile.private
github "Quick/Quick" "v0.6.0"
github "Quick/Nimble" "v2.0.0-rc.3"

I've set "Allow Non-Modular includes in Framework Modules" to Yes

**Comment by Danappelxx** [comment]
:+1:

**Comment by jeffh** [comment]
Hey @thecb4,

what is the platform (& version) you're testing on? Is it tvOS, iOS, or OS X?

**Comment by ollieatkinson** [comment]
Im also getting this.

Xcode 7.0 (and 7.1)
Cocoapods 0.38.1
Quick 0.6.0
Nimble 2.0.0-rc.3

From what I can tell the Quick & Nimble headers are going under the "Private" folder on the pod install

![-users-oliveratkinson-src-ios-rapp-pods-headers-private-nimble finder today at 11 32 11](https://cloud.githubusercontent.com/assets/1382565/10335239/4d36fcf8-6ce7-11e5-8fb4-cee64b553b15.png)

**Comment by jeffh** [comment]
Do you have a sample project? I can't seem to reproduce it [locally](https://github.com/jeffh/QNATs/).

**Comment by ollieatkinson** [comment]
@jeffh I believe it is just Xcode 7.1, I tested with a fresh project (single view application) with a `pod install` which gave me those results. I will get you an example this evening

**Comment by browndev** [comment]
I am also experiencing the issue with Xcode 7.1 beta 3, CocoaPods 0.39.0, Quick v0.6.0, Nimble v2.0.0

**Comment by danroberts** [comment]
I'm experiencing this with Xcode 7.1 beta 3, including Quick as a git submodule

**Comment by jeffh** [comment]
Thanks guys, I see this issue on 7.1.

I'll get a fix in after deploying the next release for 7.0.

**Comment by jeffh** [comment]
If you're using Xcode 7.1 betas. Let me know if the pull request versions of these work. It's currently a "works-on-my-machine" situation right now.

**Comment by cecilcosta** [comment]
I'm using the official Xcode 7.1 and this issue persists. It doesn't happen with any other framework in my project, only with Quick and Nimble. I tried to use the xcode-7.1 branch, but I still got the same result.

**Comment by dcunited001** [comment]
me too.  having this issue with lots of pods.  kinda frustrated

**Comment by serieuxchat** [comment]
Same for me. Is there a known work-around yet?

**Comment by jeffh** [comment]
I've pushed some changes for fixing Xcode 7.1 support on to the `xcode7.1` branch. Please let me know if you find any issues. I'll be cutting a new release in the next 24 hours.

I've also opened a PR for [tvOS support](https://github.com/Quick/Quick/pull/409).

**Comment by jeffh** [comment]
I've cut [v0.8.0](https://github.com/Quick/Quick/releases/tag/v0.8.0) which should solve tvOS issues (except for [tvOS + UI Testing Bundles](https://github.com/Quick/Quick/issues/413)).

Please file new issues if you're still having problems.
