### ISSUE TITLE
Shared examples not being called

### ISSUE THREAD

**Issue by mark-anders** [Quick/Quick#397]
I've followed the documentation for creating a shared example.  When I invoke ```itBehavesLike``` the ```sharedExamples``` closure is being called, however none of the contained ```it``` ones are.  So in the following example, I see "Shared Examples called", but not "In 'has a foo' test".

Any ideas what could be wrong? 

```
class SharedSpecs: QuickConfiguration {
    override class func configure(configuration: Configuration) {
        sharedExamples("A Foo provider") {
            (sharedExampleContext: SharedExampleContext) in
            NSLog("Shared Examples called")
            it("has a foo") {
                NSLog("In 'has a foo' test")

            }
        }
    }
}

class ModelSpec: QuickSpec {
    override func spec() {
        describe("Model Tests") {
            it ("can be instantiated") {
                let model = Model()
                expect(model).toNot(beNil())
                itBehavesLike("A Foo provider") {
                    ["model" : model]
                }
            }
        }
    }
}

```

**Comment by jeffh** [comment]
Move the itBehavesLike outside of the it closure. And you should be good to go. 




Having better errors for this situation is part of issue #362




—

**Comment by jeffh** [comment]
Please reopen this issue if you're still having problems. Closing.
