### ISSUE TITLE
No such module 'Quick'

### ISSUE THREAD

**Issue by sger** [Quick/Quick#402]
I'm using Xcode 7.0.1

my pod contains

target :TestQuickTests do
  link_with 'TestQuickTests'
  pod 'Quick', '~> 0.6.0'
  pod 'Nimble', '2.0.0-rc.3'
end

any ideas how to eliminate this error?

**Comment by klaaspieter** [comment]
I'm seeing the same issue with Cocoapods 0.39.0 and 0.39.0-rc.1

My Podfile:

```
use_frameworks!

target "SegmentsTests" do
  pod "Quick"
  pod "Nimble"
end
```

**Comment by ajfigueroa** [comment]
Experiencing the same issue on my end. I'm using cocoapods version 0.39.0 and my Podfile looks like:

```
target 'ApplicationTests' do
	pod 'Nimble', '~> 2.0.0'
	pod 'Quick', '~> 0.6.0'
end
```

**Comment by jeffh** [comment]
Hey all,

- Have you fully cleaned Xcode (removed derived data)?
- Do you guys get the same issue when using master branch of Quick?

Sadly, I don't see this issue on my own machine. If you have a sample project that exhibits this issue, it would be greatly appreciated.

**Comment by sger** [comment]
this is my sample project https://github.com/sger/TestQuick

**Comment by jeffh** [comment]
@sger, the project you gave compiles just fine for me:

![screen shot 2015-10-15 at 7 45 06 pm](https://cloud.githubusercontent.com/assets/68616/10532618/59890728-7375-11e5-8f4f-5129bacfa49b.png)

**Comment by sger** [comment]
@jeffh correct any change to pod?

**Comment by jeffh** [comment]
Nope, I didn't change anything I simply just cloned the repo, removed derived data, and ran tests.




—

**Comment by daneov** [comment]
Cloned your project, installed pods using :
cocoapods : 0.39.0

Denied upgrading of frameworks, and your project looks good.

![screen shot 2015-10-19 at 10 54 56](https://cloud.githubusercontent.com/assets/7900887/10574371/e7ee3136-7655-11e5-82f4-62cc13312366.png)

At my side however the error remains.
I am however able to compile and execute the tests, despite this error message, but there's no autocompletion whatsoever, which is rather painful.

My project is actually an objective-c project, but I'm now trying to learn swift trough writing the tests in it.
Can I share my project privately with you somewhere? Just to take look, and hopefully spot the culprit of this error we're having.

**Comment by jeffh** [comment]
Sure, I'll look at it when I get some free time (since I tend to look at issues via my phone), but I'll probably squeeze some free time this weekend.

**Comment by daneov** [comment]
@sger Could you try adapting your scheme's :
* Expose the Quick scheme in the Pods project
* Select the Quick scheme als build scheme (I had an iPhone selected as target)
* Build (⌘+B)
* Select your scheme

Retry ?

This seems to have fixed the autocompletion on my side.
Something is wrong nonetheless, but this is a workaround for me.

**Comment by sger** [comment]
Fixed by running tests

**Comment by daneov** [comment]
@sger So you had the error, but were able to compile as well ? Afterwards it was resolved? No other steps?

**Comment by sger** [comment]
yes @daneov run the tests for the first time and everything is working including autocomplete syntax.

**Comment by daneov** [comment]
@sger Can you try running the latest beta of XCode ? Now my autocompletion is working, and I can run the tests, however when I start typing the error appears again, while everything works in XCode 7.0.1.

However, compiling that some project with XCode 7.1b3 fails (#406)

**Comment by sger** [comment]
@daneov not working on latest Xcode 7.1

**Comment by jeffh** [comment]
I've pushed some changes for fixing Xcode 7.1 support on to the `xcode7.1` branch. Please let me know if you find any issues. I'll be cutting a new release in the next 24 hours.

I've also opened a PR for [tvOS support](https://github.com/Quick/Quick/pull/409).

**Comment by jeffh** [comment]
I've cut [v0.8.0](https://github.com/Quick/Quick/releases/tag/v0.8.0) which should solve tvOS issues (except for [tvOS + UI Testing Bundles](https://github.com/Quick/Quick/issues/413)).

**Comment by ivanruizscm** [comment]
Im having the same problem, i can run the tests, but i have no autocompletion, with xcode 7.1 and latests of quick/nimble

**Comment by ajfigueroa** [comment]
Hmm, @sger's advice worked. I built the tests and the `No such module` issue was gone.
However, I had to comment out my imports prior to building otherwise it would crap out.

**Comment by alessandroorru** [comment]
@daneov your suggestion helped me, it is the only thing that brought me autocompletion back

**Comment by sger** [comment]
the message No such module shows if target set to device with simulator everything works

**Comment by ivanruizscm** [comment]
@sger can you explain how did you solve it?

**Comment by sger** [comment]
@ivanruizscm running tests only on simulator works fine.

**Comment by timbroder** [comment]
Also make sure that the Target Membership of your tests file is only your test Target. If Quick does not exist in your main project, you will get this error

**Comment by tlandsmancars** [comment]
daneov suggestion worked for me!
You are my freaking hero.  Spent all day on this.  :(

**Comment by geraldeersteling** [comment]
Hi all,

Read all the comments and solutions up to this point. Had to say that @daneov 's solution worked for a while, but now the notorious _"No such module"_ is back and stronger then ever.

I've tried to:

- Cleaned, cleaned cleaned all the time, every time (also removed the DerivedData folder every time)
- Re-installed the pods
- Do daneov's solution again
- First build the _pods_, then the main target (cmd+shift+B), then build it for testing (cmd+shift+U)
- Removed all the header paths and stuff; replaced them with `$(inherited)`

> Also, my test files are in the test-target's membership (and only there)
---

All the above did 2 things; in 1 test file the _"No such module"_ is just doing it's error and won't let me compile, but in another there is no code completion at all. Option-clicking the module or the `QuickSpec` subclass gives me a `?` popup.

Now the weird thing is that, in the file which has no code completion and stuff, I can just manually write the tests and they run fine 😕.

I've got no clue what to do anymore and most of all it's Xcode that's driving me nuts.

**Comment by wladyslaws** [comment]
Hi all, As of Xcode v. 8.3.3, I also experience "Quick module not found" error across multiple projects. Tried workarounds from this thread - the one with deleting derived data folder, enabling schemes and rebuilding worked for around 15 minutes, then problem came back and I was not able to get rid of it (deleting derived data each 15 mins is out of the question). Other approaches didn't work at all. Lack of code completion is effectively slowing down the process of tests development to the extent that it's impossible to use this (apart from that - truly awesome, especially in synergy with Nimble) framework. Maybe we could catch up together and try to bisect where this was introduced?

**Comment by jkunzelman** [comment]
I am hitting this issue too. Is this happening for everyone on 8.3.3 or is it a configuration issue?

**Comment by bellebethcooper** [comment]
I'm seeing this issue with Xcode version 9.2 (9C40b). I also have a mixed Objc/Swift project—could that be the trigger perhaps?

**Comment by eagle-dan1349** [comment]
Same issue on xcode 9.2 any updates since last time?

**Comment by daboja** [comment]
`pod update Nimble` and `pod update Quick` resolved this issue for me.
