### ISSUE TITLE
Tests with Xcode7.1 

### ISSUE THREAD

**Issue by bytegh** [Quick/Quick#416]
hey guys:

yesterday I update my xcode to 7.1, and build my test target. but get failed:

```
Module file was created by an older version of the compiler; rebuild 'Quick' and try again: 
```

Then I tried to run the command: carthage update.
the output is:

```
*** Downloading Nimble.framework binary at "Nimble v3.0.0"
*** Downloading Quick.framework binary at "v0.8.0"
```

seemed it use the newest version of Quick which noticed to support swift2.1 and xcode7.1 .

but when I clean the project and rebuild the test target. I got the same error.

what can I do? 

Thanks! :)

**Comment by daneov** [comment]
Did you try cleaning `~/Library/Developer/Xcode/DerivedData` ?

Cheers,

D

On 29 October 2015 at 10:56:11, bytelee (notifications@github.com) wrote:

hey guys:

yesterday I update my xcode to 7.1, and build my test target. but get failed:
"
Module file was created by an older version of the compiler; rebuild 'Quick' and try again:
"
Then I tried to run the command: carthage update.
the output is:

*** Downloading Nimble.framework binary at "Nimble v3.0.0"
*** Downloading Quick.framework binary at "v0.8.0"

seemed it use the newest version of Quick which noticed to support swift2.1 and xcode7.1 .

but when I clean the project and rebuild the test target. I got the same error.

what can I do?

Thanks! :)

**Comment by daneov** [comment]
Did you try cleaning `~/Library/Developer/Xcode/DerivedData` ?

**Comment by bytegh** [comment]
I think so. but still have this issue. any other solutions? thanks

**Comment by yoichitgy** [comment]
Did you run the Carthage command with `--no-use-binaries` option?

**Comment by DorianListens** [comment]
I have the same problem, using either method of carthage installation.
When running Carthage with the --no-use-binaries option, Nimble fails to build with a clang error on the appletvos release version for arm64.

**Comment by jeffh** [comment]
Hey @DorianListens,

Some people have problems compiling with tvos support.

Does `carthage update --no-use-binaries --platform ios,osx` work for you?

**Comment by eimantas** [comment]
I use `carthage update --platform iOS`. Works like a charm for installation.

**Comment by DorianListens** [comment]
--platform iOS did the trick for me as well.

**Comment by DivineDominion** [comment]
Same here, without the tvOS platform it works.

**Comment by istx25** [comment]
Did the above solutions work for you @bytegh?

**Comment by istx25** [comment]
Closing this since a workaround has been found. Feel free to reopen if necessary.
