### ISSUE TITLE
Cant build after installing via Cocoa Pods

### ISSUE THREAD

**Issue by Raymond26** [Quick/Quick#418]
Hi I am on XCode 7.1 and I followed the installation instructions (via Cocoapods) from here: https://github.com/Quick/Quick/blob/master/Documentation/InstallingQuick.md

It seems to install just fine.  However, I am receiving the the following errors when I try to build my tests.
  
<img width="781" alt="screen shot 2015-11-01 at 8 32 15 pm" src="https://cloud.githubusercontent.com/assets/885279/10874369/f1af01be-80d7-11e5-9b8a-87c67939e0f9.png">

I tried using Quick 0.8.0 instead of 0.6.0 (as mentioned at the very top of the guide) and 3.0.0 Nimble but now Quick wont install when running pod install.

<img width="517" alt="screen shot 2015-11-01 at 8 47 37 pm" src="https://cloud.githubusercontent.com/assets/885279/10874470/d905fb20-80d9-11e5-83e2-1b9ede019681.png">

**Comment by hectormatos2011** [comment]
Try deleting your Headers folder inside of the Pods directory. That should help out with the non modular error.

**Comment by jeffh** [comment]
The installation documentation page had incorrect versions. Please use the one in the README

**Comment by Raymond26** [comment]
@jeffh, I tried using the README ones as well.  That was the one that gave me the error in the second screenshot.

**Comment by jeffh** [comment]
Hey @Raymond26,

It looks like your master repo needs to be updated.

what does `pod repo update --verbose` give you?

**Comment by Raymond26** [comment]
Ah, looks like the update worked.  Pod install now works.  Thank you!

**Comment by jeffh** [comment]
Glad that solved your problem! :+1:
