### ISSUE TITLE
iPhone OS Deployment Target set to default in Xcode 7.1 project 

### ISSUE THREAD

**Issue by chrisinsfo** [Quick/Quick#419]
When Quick is checked out as a submodule in Xcode 7.1 (Version 7.1 (7B91b)) at commit 5fff1989, the 
IPHONEOS_DEPLOYMENT_TARGET is set to "default" when read in Xcode. However, when the project file is opened in a text editor, searching for IPHONEOS_DEPLOYMENT_TARGET shows that it is set to 7.1 for both release and debug. This was last set as a fix for issue #206 at commit 028718b2.

When the deployment target is set to a different version (8.1 for example) in Xcode 7.1, the git diff shows IPHONEOS_DEPLOYMENT_TARGET = 8.1; as a addition, not a change. 

This has serious implications for Continuous Integration, because  "error: module file's minimum deployment target is ios9.1 v9.1" will be thrown, since the default iOS deployment target of 9.1 is being used.

### Steps to reproduce:
1. Add Quick as a submodule to an existing project in Xcode 7.1.
2. Add the reference to the project file as described in InstallingQuick.md.
3. Select the project file in Xcode 7.1 and go to the Info tab.

Expected 
iOS Deployment Target is 7.1.

Actual
iOS Deployment Target is "Default"

### Steps to Fix:
Set the iOS Deployment Target to 7.1 using Xcode 7.1.

### Workaround
Fork Quick and commit a change to the deployment target.

**Comment by jeffh** [comment]
Thanks for filling an issue @chrisinsfo!

I'll see if I can get a fix in this weekend

**Comment by jeffh** [comment]
Hey @chrisinsfo,

I've followed the README directions and I still see the correct deployment target:

![screen shot 2015-11-08 at 11 47 49 pm](https://cloud.githubusercontent.com/assets/68616/11028409/396d168a-8673-11e5-9b8b-52f535213bc1.png)

**Comment by sharplet** [comment]
@jeffh Because Quick-iOS builds a dynamic framework, shouldn't the deployment target be at least 8.0?

**Comment by jeffh** [comment]
@sharplet, no, because setting the minimum deployment target to iOS 7 allows it to work for users that target iOS 7 as a minimum platform. Dynamic frameworks don't work for pre-iOS 8 on device, but for users test only via simulator it works.

**Comment by istx25** [comment]
I also followed the README directions and still see the correct deployment target (several months later). I would consider this issue to be resolved.
