### ISSUE TITLE
Lack of modular Specifications?

### ISSUE THREAD

**Issue by mutech** [Quick/Quick#423]
I am looking for something like this:

Given

```Swift
class ModularQuickSpec: QuickSpec {
  spec(context: MyComplexObject) {
    describe("a complex object") {
        // quick specification based on/using context
    }
  }
}
```

and in another QuickSpec:

```Swift
expect(complexObject).to(conformToSpecification(ModularQuickSpec.dynamicType))
```

If the spec fails, I would like to see something like "complexObject expected to conform to AnotherQuickSpec: <Test failure message from AnotherQuickSpec>"

That would be easy to implement if QuickSpec would provide (perhaps another class QuickSpecTemplate) a parameterized "spec" method and if the test could be run such that success and error message can be determined by a caller.

Is there a way that is not alien to Quick/Nimble to achieve this kind of modularity (or something equivalent, the ultimate goal is to DRY and not to loose the expressiveness of Quick/Nimble)?

**Comment by modocache** [comment]
Do shared examples achieve what you're looking for here? `itBehavesLike("something")`.






On Fri, Nov 13, 2015 at 9:27 AM -0800, "Michael" <notifications@github.com> wrote:












I am looking for something like this:



Given

class AnotherQuickSpec: QuickSpec {
  spec(context: MyComplexObject) {
    describe("a complex object") {
        // quick specification based on/using context
    }
  }
}



and in another QuickSpec:

expect(complexObject).to(conformToSpecification(AnotherQuickSpec.dynamicType))



If the spec fails, I would like to see something like "complexObject expected to conform to AnotherQuickSpec: "



That would be easy to implement if QuickSpec would provide (perhaps another class QuickSpecTemplate) a parameterized "spec" method and if the test could be run such that success and error message can be determined by a caller.



Is there a way that is not alien to Quick/Nimble to achieve this kind of modularity (or something equivalent, the ultimate goal is to DRY and not to loose the expressiveness of Quick/Nimble)?

**Comment by mutech** [comment]
Let me check... Think I overlooked that one ("example" distracted me from the doc ;-)

**Comment by mutech** [comment]
Yes, that does the job, sorry for noise then ;-)
