### ISSUE TITLE
Can't install Quick+Nimble XCode Version 7.1.1 (7B1005), Cocoapods: 0.39.0

### ISSUE THREAD

**Issue by ivanruizscm** [Quick/Quick#428]
I have installed Quick+Nimble through cocoapods with no errors.
![captura de pantalla 2015-11-27 a las 13 51 03](https://cloud.githubusercontent.com/assets/15628215/11441603/237c1f7a-950e-11e5-9ea6-d88df971e4d3.png)
![captura de pantalla 2015-11-27 a las 13 51 31](https://cloud.githubusercontent.com/assets/15628215/11441621/41f355fe-950e-11e5-884b-0852442702ae.png)

**Comment by ivanruizscm** [comment]
![captura de pantalla 2015-11-27 a las 13 54 37](https://cloud.githubusercontent.com/assets/15628215/11441636/71e51568-950e-11e5-9ca6-3d4b04a6eb06.png)

**Comment by yoichitgy** [comment]
The latest versions of Quick and Nimble are 0.8.0 and 3.0.0. You can try replacing `testing_pods` with the following definition.

```
def testing_pods
    pod 'Quick', '~> 0.8.0'
    pod 'Nimble', '3.0.0'
end
```

**Comment by ivanruizscm** [comment]
Installing Nimble 3.0.0 (was 2.0.0-rc.2)
Installing Quick 0.8.0 (was 0.6.0)

But im getting the same.
![captura de pantalla 2015-11-27 a las 14 18 06](https://cloud.githubusercontent.com/assets/15628215/11442007/b7f38a82-9511-11e5-870b-7f6f78528311.png)

**Comment by yoichitgy** [comment]
One of your screenshots told the build of Nimble failed. I cannot tell exactly from only the screenshot, but the installation by CocoaPods looked failed actually. You can try reinstall the frameworks by CocoaPods again, or install only Quick and Nimble to a new project via CocoaPods, to find a clue.

The build succeeds In my environment with Xcode 7.1.1 and CocoaPods 0.39.0.

**Comment by yoichitgy** [comment]
Regarding "Include of non-modular header" error, this issue note might be helpful:
https://github.com/CocoaPods/CocoaPods/issues/3847

**Comment by jeffh** [comment]
Thanks @yoichitgy for linking to those issues. :+1:

**Comment by ivanruizscm** [comment]
@jeffh can you have a look at my project why isnt working? I just able to run the tests, but i can't get automcomplete Quick/Nimble. I tried removing derived data, and so on. No clue whats going on

**Comment by ivanruizscm** [comment]
I've modified my project with only a test class to show you the problem. In the test target open "MyTest" 
http://www.ruiznadal.com/check.zip
No such module 'Nimble' 
No such module 'Quick' if you put it first

**Comment by jhoughjr** [comment]
I have a similar issue, pod install goes fine and everything appears to build properly.

**Comment by yoichitgy** [comment]
@ivanruizscm, @jhoughjr, the CocoaPods fixed the issue 4420 on its master branch but still the fixed version is not released. Probably you will be able to resolve the problem with CocoaPods v0.39.1 or 0.40.0 when the update is released.

If you would like to try the fixed version in the master branch now, the following Q&A is helpful.
http://stackoverflow.com/questions/2823492/install-gem-from-github-branch

**Comment by cerupcat** [comment]
Any updates to this? I've tried installing the latest CocoaPods from the master repo and it still has the same error.

**Comment by jhoughjr** [comment]
same here with no luck.

**Comment by paulz** [comment]
Same here, tried master version of CocoaPods with no luck.

Had to resort to https://github.com/Carthage/Carthage to install Quick

**Comment by ScottRobbins** [comment]
Haven't been able to get master to work for me. Would rather not introduce a second dependency manager.

**Comment by jhoughjr** [comment]
I thought I had it integrated with Carthage but it didn’t seem to work. expect ain’t found or something, i forget what the error was.

**Comment by cerupcat** [comment]
I was able to get it working using Carthage. I also don't really want the extra dependency manager, but it was simple enough to add that we'll use it for now and likely remove Carthage after this is fixed.

**Comment by ivanruizscm** [comment]
any updates to this? I can't use Quick with cocoapods :-(

**Comment by jhoughjr** [comment]
I just installed the beta of cocoa pods, via sudo gem install cocoa pods --pre , and it appears to integrate properly. I'm not having the issues with Xcode not seeing Nimble or Quick.
You could try that I think.

**Comment by modocache** [comment]
For those of you experiencing issues: could you try with the latest versions of CocoaPods and Quick? If that doesn't work, please post the versions you are using and the full error logs--that should make it easier to figure out why this doesn't work for some people! :+1:

**Comment by jhoughjr** [comment]
> On Jan 26, 2016, at 11:38 AM, Brian Gesiak <notifications@github.com> wrote:
> 
> For those of you experiencing issues: could you try with the latest versions of CocoaPods and Quick? If that doesn't work, please post the versions you are using and the full error logs--that should make it easier to figure out why this doesn't work for some people! 
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Quick/Quick/issues/428#issuecomment-175135675>.
> 
I was able to import Quick and Nimble using cocoa pods 1.0.0-beta2 installed via sudo gem install cocoapods —pre .
Incidentally I think I’ve got some other issues in my test target as I’m not able to use symbols from the main target,  But I don’t think this is a Quick problem.
Hope that helps.

**Comment by ivanruizscm** [comment]
<img width="1143" alt="screen shot 2016-01-26 at 22 35 04" src="https://cloud.githubusercontent.com/assets/15628215/12595708/1c96b8ca-c47d-11e5-8757-7476546c7160.png">
Cocoapods -> 0.39.0 
Quick -> 0.9.0

**Comment by ivanruizscm** [comment]
I can't install pods using .beta2 
https://github.com/CocoaPods/CocoaPods/issues/4814

**Comment by ivanruizscm** [comment]
Also i failed installing with Carthage:
AFE0806015:next-visit-ios ivan.ruiz$ carthage update
*** Cloning Nimble
*** Cloning Quick
*** Checking out Quick at "v0.9.0"
*** Checking out Nimble at "v3.1.0"
*** xcodebuild output can be found in /var/folders/qc/hj9gmlv919q0g_l7xjhbc4g0xk255y/T/carthage-xcodebuild.5rquRh.log
*** Building scheme "Nimble-OSX" in Nimble.xcodeproj
*** Building scheme "Nimble-tvOS" in Nimble.xcodeproj
** BUILD FAILED **


The following build commands failed:
	Ld /Users/ivan.ruiz/Library/Developer/Xcode/DerivedData/Nimble-affaujztwrmpukagtxhsuhwvuhlv/Build/Products/Release-appletvos/Nimble.framework/Nimble normal arm64
(1 failure)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Ld /Users/ivan.ruiz/Library/Developer/Xcode/DerivedData/Nimble-affaujztwrmpukagtxhsuhwvuhlv/Build/Products/Release-appletvos/Nimble.framework/Nimble normal arm64
(1 failure)

**Comment by muqq** [comment]
You can run 'carthage update --platform iOS --no-use-binaries'

**Comment by jhoughjr** [comment]
Any progress on a cocoa pods install for this?

**Comment by johndpope** [comment]
actually - I just got this working - try closing and restarting project.

**Comment by ivanruizscm** [comment]
@johndpope wtf? do you think all of us didnt try several times that?

**Comment by johndpope** [comment]
Hi Ivan, 
Sorry I can't be more help. I downloaded your sample app and it compiled fine. 
<img width="434" alt="screen shot 2016-04-20 at 9 14 45 am" src="https://cloud.githubusercontent.com/assets/289994/14675759/81646d86-06d8-11e6-9543-90894809e4f6.png">

I may have ran the command CMD+SHIFT+ALT+K to remove the  build folder 
followed by an xcode restart. 

If this doesn't solve your problem, you could try reinstalling cocoapods (I didn't need too)
gem uninstall cocoapods 
gem install cocoapods 

let me know if this fixes problem.

**Comment by adampitchie** [comment]
I'm having the same issue. This ruined my afternoon trying to figure out a solution. Ridiculously frustrating.

**Comment by ccorneliu** [comment]
Hey, guys!

I just noticed that if I turn off "Gather coverage data" option it fixes the _No such module 'Quick'_ problem, after a build. Maybe this might be the problem for some of you.

![screen_shot_2016-06-07_at_17_29_51](https://cloud.githubusercontent.com/assets/7429128/15861679/bf4007dc-2cd5-11e6-918d-02e7cfffd166.png)

**Comment by briancroom** [comment]
Oh that's very interesting @ccorneliu! Thanks for the tip. 

I've noticed that Xcode puts build products in a different directory than normal when that option is turned on, which could explain why it is unable to find the framework where it wants it to be sometimes.

**Comment by istx25** [comment]
Closing for now. I believe the issue has been fixed. Let me know if not and we can reopen.
