### ISSUE TITLE
Not working well on XCode7.1

### ISSUE THREAD

**Issue by alexiosdev** [Quick/Quick#429]
They are not running test cases as desired.

So  I can see things in this log
It doesn't matter if I wanted to run selected (used fdescribe) or run all 

```
Test Suite 'Selected tests' started at 2015-11-28 15:47:15.429
Test Suite 'SomeSpec' started at 2015-11-28 15:47:15.430
Test Case '-[MyAppTests. SomeSpec (null)]' started.
Test Case '-[MyAppTests. SomeSpec (null)]' passed (0.003 seconds).
Test Suite 'SomeSpec' passed at 2015-11-28 15:47:15.433.
     Executed 1 test, with 0 failures (0 unexpected) in 0.003 (0.003) seconds
```

I only had to quit Xcode and after that it works as desired but after some times then it repeats inconsistency as I described.

Any one can help me
Thanks

**Comment by jeffh** [comment]
Hey @zhangyicococo,

We're still trying to diagnose this issue. What does your examples look like?

**Comment by zhangyicococo** [comment]
It's a general QuickSpec with several test cases.

I found when I defined test function like this it didn't work 

```Swift
class MyClassTest : XCTestCase {
        func testSomething() throws {
                //some codes
        }
}
```
So when I defined test function and made it throw then I see similar messages of issue.
Sorry I am not a skilled developer, but it's interesting see similar messages.

**Comment by ole** [comment]
I'm also seeing this. At least right now, I see a pretty consistent behavior (I can't remember if it always behaved like this):

1. Write a Spec.
2. Run a single Spec (by clicking on the green Play button in Xcode). I see `(null)` in the log:

        Test Case '-[MyAppTests.DummySpec (null)]' started.
        Test Case '-[MyAppTests.DummySpec (null)]' passed (0.003 seconds).

   It will remain this way until I run the full test suite.
3. Run the full suite (Cmd+U). This works fine.
4. Run the single Spec again. This works now reliably every time until I …
5. … change the Spec's code. After the Rebuild, we're back to step 2. Running the single step fails until I run the full suite once.

This is on the final release of Xcode 7.2.

**Comment by aunnnn** [comment]
Not sure of this, but for a quick fix right now, I rerun individual Spec by re-ticking checkmark on "Target Membership" of the Spec file at the Utilities Pane. 

Steps are:
1. De-tick the "target membership" of a Spec file. You will see that the Spec in the test navigator will gone. Somehow Xcode clear the test cache of that particular file.
2. Now, re-tick that, in ~1sec it'll reappear brand-new in the test navigator and you can rerun this.
3. Repeat 1. & 2. if you need to rerun that Spec again.

**Comment by istx25** [comment]
Any progress with this? I would appreciate it if someone would be able to upload a focused sample which replicates the issue. I'm having a hard time replicating the problem on my end.

**Comment by ikesyo** [comment]
This is fairly outdated. Closing for now.
