### ISSUE TITLE
Carthage: Can't import Quick/Nimble from within files in my test target

### ISSUE THREAD

**Issue by dcunited001** [Quick/Quick#430]
I'm working on a library [Spectra](https://github.com/dcunited001/SpectraNu) and I'm using carthage to pull down Quick/Nimble.  

Within my workspace, I've created two projects for OSX and iOS.  I've got a test target within each project.  I've followed the instructions and I've added the Quick/Nimble frameworks to the build steps, but I can't seem to get the compiler to recognize `import Quick` and `import Nimble`.  The symbols aren't available to my test files.  

How do I set up my build steps for my test targets so the compiler recognizes that symbols from these frameworks should be available?

Thank you!

**Comment by jeffh** [comment]
What error messages are you getting?

Does performing something like:

```bash
carthage update --platform ios,osx
```

work for you?

**Comment by dcunited001** [comment]
yes, i've run these commands:

```bash
carthage update --platform ios,osx --use-submodules
carthage build --platform ios,osx --use-submodules
```

carthage builds successfully and the frameworks are available.  i've added the built frameworks for iOS and OSX into each projects' respective `build steps` for the test target.  but quick/nimble aren't available in my source code.

**Comment by dcunited001** [comment]
i've figured out the import issues.  i was following [this guide](http://www.swift-studies.com/blog/2014/6/30/creating-a-pure-swift-framework-for-both-ios-and-mac) to set up  a multiproject workspace, so my project works for both OSX & iOS.  

mdiep helped me resolve this in the [carthage issue](https://github.com/Carthage/Carthage/issues/946) i opened.  basically, i hadn't set the `FRAMEWORK_SEARCH_PATHS` correctly.  also, my `PRODUCT_NAME` build setting was borked.  i've fixed those and almost everything is addressed.

**Comment by mikemee** [comment]
Fwiw, on a relatively new iOS-only codebase (well, old objc code, but with some new swift code) I was able to follow the documentation for inclusion via Carthage and was able to use Nimble with some existing XCTests and also create some new specs with Quick & Nimble combined. 

_I.e., just trying to reassure that the Carthage install & include process is working for at least one relatively vanilla project as described._

**Comment by jeffh** [comment]
Thanks @mikemee, it's super valuable hear positive cases too. Otherwise I get the perception that carthage isn't working in the default case.

**Comment by dcunited001** [comment]
@jeff @mikemee sorry i'm terrible at checking my github notifications. 

configuring the `FRAMEWORK_SEARCH_PATHS` and `PRODUCT_NAME` helped resolve most of the problems.  i had a few more issues, but they were relatively simple and moreso related to my `xcworkspace` multi-framework setup than `carthage` or `Quick/Nimble`, which have all been working great since then.

Thanks guys, peace!

More info at [Carthage#946](https://github.com/Carthage/Carthage/issues/946)
