### ISSUE TITLE
Combining assertions

### ISSUE THREAD

**Issue by aufflick** [Quick/Quick#432]
It would seem to be useful to be able to generate two tests by eg:

`expect { try someFunc() }.toNot(throwError()).to(equal(5))`

This form doesn't work, I don't see any docs about how to achieve the same thing, or is there some reason that eludes me that this isn't a good idea?

**Comment by aufflick** [comment]
Now I realise that simply `.to(equal(5))` will also prove that it doesn't throw, but a test report that shows the difference between throwing and wrong value is good, and there are other combinations where that this would be useful.

**Comment by jeffh** [comment]
Thanks for the feedback @aufflick. I'm curious about what kind of use case are you imagining to combine assertions? I have been thinking about it, but not much implementation yet.

**Comment by istx25** [comment]
Any progress on this? Would love to see a PR if not.

**Comment by jeffh** [comment]
Moved issue to Nimble. Closing this one.
