### ISSUE TITLE
Cross-platform support

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#433]
Quick should work on all platforms. This is made easier thanks to XCTest's front-end API being available on those platforms: https://github.com/apple/swift-corelibs-xctest

This issue tracks:
- [ ] Implementing `-[QuickSpec allTests]` so that platforms not using the Objective-C runtime can detect test methods: https://github.com/apple/swift-corelibs-xctest#additional-considerations-for-swift-on-linux
- [ ] Documenting use of `XCTMain` in the Quick documentation, or wrapping it using Quick such that the process is automatic
- [ ] Testing Quick against open-source Swift on OS X and ensuring everything works
- [ ] Testing Quick against open-source Swift on Linux and ensuring everything works
- [ ] Updating the Quick test suite such that it passes on all platforms

**Comment by modocache** [comment]
Well, Quick's unit tests work when running Xcode via `xcrun launch-with-toolchain /Library/Developer/Toolchains/swift-latest.xctoolchain`. Looks promising.

**Comment by modocache** [comment]
Quick imports XCTest, whereas the open-source XCTest defines a module named SwiftXCTest. Using Quick from within a test that uses SwiftXCTest results in an error:

```
'XCTestCase' is ambiguous for type lookup in this context
```

I wonder if there's a way we can detect which version of XCTest is available? Or we can provide two products: one that works with XCTest, and one that works with SwiftXCTest.

**Comment by modocache** [comment]
We probably need two products: Quick-OSX, and Quick-OSX-SwiftXCTest. The second should be written entirely in Swift.

**Comment by unchartedworks** [comment]
If you want support cross-platform, I don't think using framework as product is a good idea. Swift Package Manager doesn't support framework yet.

**Comment by ikesyo** [comment]
The feature was implemented in #444 and #687. Also there is a dedicated documentation issue #675. So let's close this.
