### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#434]
Quick should support [Swift's official package manager](http://cjwirth.com/swift-org/package-manager/). This task tracks:

- [x] Adding a `Package.swift` file
- [ ] Confirming that Quick can be used within a unit test bundle after being imported via the package manager

After this issue is resolved we really need to get around to tackling #238.

**Comment by istx25** [comment]
Quick supports SPM so I'm going to close this issue.
