### ISSUE TITLE
Workaround for really long test case names?

### ISSUE THREAD

**Issue by attheodo** [Quick/Quick#438]
Is there any workaround to make the test case names in the console shorter?

```
Test Case '-[REDACTED_FootballTests.IRMultipleSelectionSegmentedControlSpec IRMultipleSelectionSegmentedControl__Should_deselect_the_correct_option_if_the_button_is_pressed_UsersthanosthDocumentsdevREDACTEDREDACTEDFootballREDACTEDFootballTestsSubviewsIRMultipleSelectionSegmentedControlTestsswift_59]' passed (0.043 seconds).
```

Especially having the test case's filepath in there makes it even harder to make sense of what test is being executed/failing in a CI environment.

Thanks

**Comment by modocache** [comment]
Yeah, this is definitely something I'd like to improve upon--thanks for bringing this up. #392 covers removing the file path. I'll close this issue to centralize the discussion there.

Thanks! And if you'd like to try your hand at tackling #392, I'd love to help. We can chat there if you need advice or additional context. We could also schedule a video call if you'd prefer!
