### ISSUE TITLE
Weird warning with do-catch block in spec: "'catch' block unreachable because no errors are thrown"

### ISSUE THREAD

**Issue by Dschee** [Quick/Quick#440]
I have this spec where `type()` is a method that can throw:

    @testable import DemoFramework
    
    import Quick
    import Nimble
    
    class ThingsFactorySpec: QuickSpec {
        
        override func spec() {
            
            describe("newThing()") {
                
                it("has the stuff type by default") {
                    let thing = ThingsFactory.sharedInstance.newThing()
                    do {
                        expect(try thing.type()).to(equal(ThingType.Stuff))
                    } catch {
                        expect(true).to(equal(false)) // something went wrong in do{}
                    }
                    
                    expect(crossword.board.fieldRows.count).to(equal(15))
                    expect(crossword.board.fieldColumns.count).to(equal(15))
                }
            }
         }
    }

This produces the following warning in XCode 7.2 which I don't expect:
`'catch' block is unreachable because no errors are thrown in 'do' block`

When I remove the catch block I get (which I expect):
`Cannot invoke 'it' with an argument list of type '(String, () throws -> ())'`

When I don't use the do-catch block at all I get (which I also expect):
`Call can throw but is not marked with 'try'`

So I'm pretty sure the do-catch block should be there. But why does XCode tell me it's not reachable, **is it an XCode 7.2 bug I can safely ignore** or **can it be fixed within this framework**?

*Btw. as you may have noticed in my catch block I wasn't sure how to make sure my test fails when the error is thrown. I find this solution working but not satisfying, I'd be happy about a hint to a better implementation.*

**Comment by jeffh** [comment]
Hey @Dschee,

[Nimble](https://github.com/Quick/Nimble) will automatically catch `try` expressions implicitly in `expect`:

```swift
let thing = ThingsFactory.sharedInstance.newThing()
expect(try thing.type()).to(equal(ThingType.Stuff))
expect(crossword.board.fieldRows.count).to(equal(15))
```

You don't need to catch them on your part.

**Comment by jayce-leathers** [comment]
@jeffh Xcode 7.2 will actually complain without the do {} catch {}. I'm getting an error "Cannot invoke 'it' with an argument list of type '(String, () throws -> ())' " with the following
`expect(try object.throwingFunc()).to(throwError(ErrorEnum.ErrorCase))`
with
`do {
                        expect(try object.throwingFunc()).to(throwError(ErrorEnum.ErrorCase))
                    }catch _ {}`
there is no error but instead the warning " 'catch' block is unreachable because no errors are thrown in 'do' block

**Comment by briancroom** [comment]
@Dschee @jayce-leathers I have been unable to reproduce the compiler errors that you are encountering. Do you think you could push a more complete example to GitHub for further investigation?

**Comment by csotiriou** [comment]
Hello,

I have the same problem.

Sample code:

`describe("Sample Error") {
            it("should throw an error", closure: {
                
                func throwErrorSample() throws {
                    throw NSError(domain: "sammple.domain", code: -100, userInfo: nil)
                }
                
                expect(try throwErrorSample()).to(throwError())
                
            })
        }`

Compiler will complain with this code, because the closure should be throwable.

If I change the line into this (adding an exclamation mark)

`                expect(try! initializeTwice()).to(throwError())
`

The problem goes away, but the exception will be thrown and not handled by Nimble. I am forced to write the corresponding line like this:

`
                do { expect(try initializeTwice()).to(throwError()) }catch{}

`

But I get "'catch' block unreachable because no errors are thrown", as the op says.

**Comment by istx25** [comment]
Any updates? Did you ever find a solution to this? @Dschee @csotiriou

**Comment by istx25** [comment]
I am going to close this issue since it's been inactive for a very long time. If either (or anyone else) if having a similar problem or needs help, please feel free to comment and I will reopen the issue.

**Comment by chrismcleod** [comment]
For anyone coming across this, looked at the Nimble issues and figured out you are supposed to declare expectation which throw inside a closure so { } not ():

`expect {
  try thing.methodThatThrows()
}.to(throwError())`
