### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by masukomi** [Quick/Quick#455]
> When you create a new project in Xcode 7, a unit test target is included by default

This is not true if you are creating a Command Line Tool project. Furthermore if you are working on a command line tool there is no `"Defines Modules" line` to set to "Yes" as instructed.

**Comment by modocache** [comment]
Interesting... I'd be happy to merge a pull request that adds instructions on how to test a command-line application--does anyone know the best approach for this sort of thing?

**Comment by masukomi** [comment]
minor correction: There is a "Define Modules" but it's been moved under "Packaging" (same applies to OS X project too.
