### ISSUE TITLE
Add documentation for using Quick with swift-package-manager

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#458]
https://github.com/Quick/Quick/pull/444 added support for using Quick on Linux. The [Documentation folder](https://github.com/Quick/Quick/tree/master/Documentation) should be expanded to include installation instructions.

**Comment by sauliusgrigaitis** [comment]
:+1: I would like to use Quick on Linux for [Swifton](https://github.com/necolt/Swifton) web framework, unfortunately I can't find any example how to run Quick on Linux with swift-package-manager. Maybe somebody could make sample project that has Quick integrated with few sample tests and swift-package-manager support?

**Comment by briancroom** [comment]
Hey @sauliusgrigaitis, try checking out [this repo](https://github.com/briancroom/QuickOnLinuxExample) to get you started. I'm still intending to write up some documentation here about this before long, but I don't expect it to happen at least until the new `swift test` functionality reaches the snapshots and I can make sure that Quick integrates properly with it.

Good luck and please follow up with additional questions you have!

**Comment by modocache** [comment]
> I'm still intending to write up some documentation here about this before long

This would be awesome!! :100:

**Comment by modocache** [comment]
@briancroom For the time being, how would you feel about including https://github.com/briancroom/QuickOnLinuxExample in the Quick org, and providing a simple one-sentence link to it in the documentation?

**Comment by briancroom** [comment]
Sounds like a good idea. I'll take care of it a bit later when I get a few minutes free.

**Comment by briancroom** [comment]
@modocache looks like I don't have the needed permissions to add a repo to the Quick org  `¯\_(ツ)_/¯`

**Comment by modocache** [comment]
@briancroom OK, I think you should be able to create repositories now. Figuring out the GitHub UI for those permissions took me... longer than I care to admit. :stuck_out_tongue:

**Comment by briancroom** [comment]
@modocache heh I've experienced that before. Thanks for making it happen!

**Comment by briancroom** [comment]
Done! https://github.com/Quick/Quick/commit/a9fc47c01467c85b875c1c63c7af7a08b2a30823

But let's keep this issue open because I'm far from satisfied with the state of this.

**Comment by sauliusgrigaitis** [comment]
Thanks a lot @briancroom , I wrote some [tests](https://github.com/necolt/Swifton/commit/0d776b4d8a76debd4849c13f6096a7974ad5ae15) and looks like it works well.

**Comment by briancroom** [comment]
That's great! Please file issues as you encounter problems going forward.

**Comment by sauliusgrigaitis** [comment]
@briancroom thanks. Actually two issues:

Travis.ci doesn't build any more:

```/Users/travis/build/necolt/Swifton/Packages/Nimble-3.3.1/Sources/Nimble/Adapters/NimbleXCTestHandler.swift:2:8: error: cannot load underlying module for 'XCTest'
import XCTest
       ^
<unknown>:0: error: build had 1 comman
```

And another one really interesting - if I remove exclamation mark at this [line](https://github.com/necolt/Swifton/blob/master/Sources/Spec/MemoryModelSpec.swift#L15), then it just [collapses](https://gist.github.com/sauliusgrigaitis/62a189d5bd6bde37996e).

**Comment by modocache** [comment]
Ooh, `cannot load underlying module for 'XCTest'` is the same error from #492. :point_up:

**Comment by modocache** [comment]
As for the crasher from removing the exclamation point: it would be great if you could reduce this to a minimal test case and report a bug on bugs.swift.org. Perhaps @practicalswift could help you here, they using fuzzing tools to produce minimal crashing test cases for the compiler.

**Comment by briancroom** [comment]
+1 on the crasher.

As for Travis, I would suggest trying to have the build run on Linux instead of on OS X, where Quick's SwiftPM support is still lacking. You might take a look at Quick's own Travis config+scripts:
https://github.com/Quick/Quick/blob/master/.travis.yml
https://github.com/Quick/Quick/blob/master/script/travis-install-linux
https://github.com/Quick/Quick/blob/master/script/travis-script-linux
https://github.com/Quick/Quick/blob/master/Rakefile#L42

**Comment by sauliusgrigaitis** [comment]
Thanks, ironically build passes on Linux :) Will try to isolate that compiler issue if I'll have chance.

BTW, :+1: for Quick - I feel like at home after RSpec.

**Comment by sauliusgrigaitis** [comment]
@briancroom there is something wrong with this approach. Steps to reproduce:

1. Checkout git@github.com:sauliusgrigaitis/Swifton-TodoApp.git and run ```swift build``` . You should get this error https://gist.github.com/sauliusgrigaitis/8b97fc3c7fb70167cd0d
2. Open Package.swift and change ```<Version(0,0,8))``` to ```<Version(0,0,7))``` and run  ```swift build --clean dist && swift  build``` . There is no error. The only difference is this [commit](https://gist.github.com/sauliusgrigaitis/8b97fc3c7fb70167cd0d) where I added Quick```.

Interesting is that it builds when building only Swifton, problem is when Swifton with Quick tests are built as dependency.

**Comment by sauliusgrigaitis** [comment]
@briancroom @modocache just wondering is there any update regarding to better approach to run Quick tests on Linux? Please let me know if you don't expect to get better solution soon - I'll need to think some other way, because now I can't release Swifton new version - it's just doens't compile if used as dependency ([error](https://gist.github.com/sauliusgrigaitis/8b97fc3c7fb70167cd0d)).

**Comment by morganchen12** [comment]
@sauliusgrigaitis if you use the newest Swift snapshot and build Quick from the `master` branch, are the build errors still there?

**Comment by istx25** [comment]
Seems like there are a few unrelated topics being discussed in this issue. However, the main purpose of the issue has been completed ([as far as I can see](https://github.com/Quick/Quick/blob/master/Documentation/en-us/InstallingQuick.md#swift-package-manager)). I will close for now, but feel free to reopen if necessary.
