### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#460]
I added a section called "code of conduct" in https://github.com/Quick/Quick/commit/ecfc6132fe5f48c3f9210c92ab102bd6666add59#diff-6a3371457528722a734f3c51d9238c13, but removed it in https://github.com/Quick/Quick/commit/11167ab8d6db66ced958a3ea094e4f6440cf995e. The old section was meant as a procedural manual for core members, whereas this issue refers to [this kind of CoC](https://robots.thoughtbot.com/adding-a-code-of-conduct-to-open-source-projects).

I assume there's a "one size fits most" CoC out there; we should allow for community review by submitting a pull request to add it. I'm sure anything with clear instructions on how to report inappropriate behavior is fine--the real challenge is in living up to the CoC in practice, not in adopting one that has the perfect wording.

> Note: Thankfully this issue isn't being created in response to any incidents I'm aware of--I think we're doing a great job at being welcoming and helpful to everyone who interacts with repositories in the org.

**Comment by morganchen12** [comment]
Why not get started with the [Contributor Covenant](http://contributor-covenant.org/)?

I'd make a PR to add it, but I think Nimble and any other future codebases under the Quick umbrella should also benefit. Can we add it to the whole org and then link it in each project's CONTRIBUTING file instead?

**Comment by modocache** [comment]
Yes please!






On Fri, Apr 8, 2016 at 9:42 AM -0700, "Morgan Chen" <notifications@github.com> wrote:












Why not get started with the Contributor Covenant?



I'd make a PR to add it, but I think Nimble and any other future codebases under the Quick umbrella should also benefit. Can we add it to the whole org and then link it in each project's CONTRIBUTING file instead?

**Comment by morganchen12** [comment]
It requires some customization (like an email that people can send
complaints to), so we will probably want to host that text ourselves in a
separate repo under the Quick org.

**Comment by istx25** [comment]
Any updates on this?

**Comment by modocache** [comment]
Yes, good point. I'll try and get one up this weekend! Sorry for the wait!






On Sat, Jul 9, 2016 at 2:41 PM -0700, "Willow Bellemore" <notifications@github.com> wrote:












Any updates on this?

**Comment by istx25** [comment]
Awesome! If it makes it easier or faster, I don't mind doing it. Let me know if I can help. I'll need the enforcement email address and write access though. Thanks for being open to making the community safer though! 💓

**Comment by modocache** [comment]
I was planning on sending a pull request so that contributors have a chance to read it over. Forgive my ignorance: what makes a good enforcement email address? Will my email address do, or an email that's forwarded to all core team members, or something else? I'm planning on reading more on the topic this weekend.



On Sat, Jul 9, 2016 at 2:46 PM -0700, "Willow Bellemore" <notifications@github.com> wrote:












Awesome! If it makes it easier or faster, I don't mind doing it. Let me know if I can help. I'll need the enforcement email address and write access though. Thanks for being open to making the community safer though! 💓

**Comment by istx25** [comment]
No problem, @modocache! Just looking for ways to get involved in this community, haha. 😺

I have seen a lot of communities (like Angular and Swift) adopt a "conduct@domain.com" address/alias for receiving complaints. I would recommend doing something similar, but replying to complaints as personally as possible, like replying to complaints using your own individual team account instead of from the alias you received the complaint from. From my own experience, it makes it feel like matters are being taken more seriously than if it's coming from an anonymous person at an org.

Looking forward to the Code of Conduct being added. ❤️

**Comment by istx25** [comment]
Additionally, I recommend that all Code of Conduct complaints are sent to all core team members. I think this is best, since if something is getting bad enough that someone in the community is reporting the problem to you, it should probably be dealt with as soon as possible and by whichever one of you are most available at that time.

**Comment by modocache** [comment]
I agree with all of your suggestions, and that something like `conduct@quick.org` would be cool. We currently don't have an easy way to email committers either, and having an email domain would be very useful. I'm checking out options now... do you know of any free ones? If not, I think the best option would be to buy a domain name for around $8/year (which I guess I wouldn't mind doing).

**Comment by istx25** [comment]
Awesome. Regarding ways for emailing contributors, I'm not entirely sure. Though, you could follow Facebook in implementing a Contributor License Agreement (CLA) which would collect a potential contributors contact information and store that for any potential future use? Getting a domain name though would definitely be great though.

**Comment by modocache** [comment]
I'm sorry I didn't actually end up doing this over the weekend. It's not for lack of enthusiasm, I just ended up getting sidetracked 😅 

Here's my plan: Some night after work this week I'll register a domain for Quick-related emails. I'll contact people with commit access to Quick repositories and invite them to get a `@quick` email address. We can use that email address as the contact, so that any concerns that people may have in the future will be sent privately to all the core team members.

**Comment by istx25** [comment]
Fantastic! Looking forward to see the results. Thanks, @modocache.

**Comment by modocache** [comment]
Not done yet, but not forgotten. 😓 

Shooting to put some work into this this weekend!

**Comment by istx25** [comment]
Any updates on this?

**Comment by istx25** [comment]
I am going to try to get this done as soon as possible. Will write a longer comment with my plan later today or sometime this week.

**Comment by istx25** [comment]
To make this happen we need to:

- [ ] Purchase the domain name.
- [ ] Setup the email server or service.
- [ ] Adopt the [Contributor Covenant](http://contributor-covenant.org/) CoC.

Have you purchased the domain name yet?

**Comment by istx25** [comment]
After more thought...

I think we should do the email server/domain stuff later and just use an out of the box solution for email like Gmail. Do you have an email using one of those services for Quick? If not, we can create one.

Alternatively, I can just put down my work email since I will be contributing and managing this project for the unforeseeable future. It'll allow us to get the CoC out sooner and I will probably be replying to such reports anyways.

I would consider creating a Slack for Quick (if we haven't already) so core contributors have a more private way to interact with each other.

Thoughts @modocache?

**Comment by modocache** [comment]
> Do you have an email using one of those services for Quick? If not, we can create one.

Please do create one! We don't have one already.

> I would consider creating a Slack for Quick (if we haven't already) so core contributors have a more private way to interact with each other.

I've been opposed to this in the past, since I prefer that all communication on the project is in one place. My biggest pet peeve is when maintainers redirect users, since I think it's super frustrating: "this isn't the place to report bugs, please do so using the bug reporting system".

I also really dislike Slack -- I have to restart it 7-8 times before it loads any conversations.

But I can respect the fact that some people prefer a lightweight communication channel. I'll defer to your judgement here. If you'd like to create an official Slack channel, that's fine with me. I'll try to be present in the channel as often as I can.

**Comment by istx25** [comment]
@modocache: Awesome. I'll create the email address for Quick. 

Regarding Slack, I know where you're coming from - I've also found that issue really, really frustrating but from my understanding it's actually a bug with Electron. I'll rope in Slack with this issue to see what they say about your feedback. For now, we can stick with IRC or just pump more traffic through GitHub Issues. There are also Slack alternatives which we can consider.

**Comment by istx25** [comment]
I have created the email address: `quickorg@icloud.com`. PM me for the password.

**Comment by istx25** [comment]
🎉
