### ISSUE TITLE
Quick/Package.swift should depend on canonical Nimble

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#461]
https://github.com/Quick/Quick/blob/11167ab8d6db66ced958a3ea094e4f6440cf995e/Package.swift#L10-L15 depends on @briancroom's Nimble fork; it should depend on https://github.com/Quick/Nimble.

**Comment by briancroom** [comment]
(I also had to create a "fake" release tag on my Nimble branch to convince swiftpm to use it 😱)

Unfortunately canonical Nimble doesn't build on Linux yet. This change will have to wait until https://github.com/Quick/Nimble/pull/226 (or, more likely, a series of more focused PRs with the same changes) get merged, and a release is cut.

**Comment by modocache** [comment]
Ah yeah, I figured. To keep up with the changes (Linux support is super interesting!) I'll also try to take a look at https://github.com/Quick/Nimble/pull/226 in the next day or two.

**Comment by istx25** [comment]
This issue has been completed. https://github.com/Quick/Nimble/pull/226 was broken down into https://github.com/Quick/Nimble/pull/236, https://github.com/Quick/Nimble/pull/237, https://github.com/Quick/Nimble/pull/238, https://github.com/Quick/Nimble/pull/239, and https://github.com/Quick/Nimble/pull/240. All have been merged.
