### ISSUE TITLE
No ability to lazily evaluate rspec style `let` statements

### ISSUE THREAD

**Issue by seansu4you87** [Quick/Quick#466]
One of the true advantages of a xSpec style over xUnit style is the ability to declare variable values in blocks that are lazily evaluated (such as `let` statements in rspec).  This allows you to structure dependencies as `let` statements, that can be overridden in deeper contexts blocks, when your setup needs a slight modification.  This allows you to easily branch off a spec with a complicated setup, while writing very little code, compared to copy/pasting all of your setup over again.

Unfortunately, this isn't possible with Quick right now.  See the following example.  Is this on the docket for future releases?

```
import Foundation

import Quick
import Nimble

class SwiftSpec : QuickSpec {
    override func spec() {
        describe("some kind of spec") {
            it("passes this test") {
                expect(1 + 1).to(equal(2))
            }
            
            xit("fails") {
                expect(true).to(equal(false))
            }
        }

        describe("nesting") {
            var a: Int!
            beforeEach {
                a = 5
            }

            it("sets a") {
                expect(a).to(equal(5))
                a = 4
                expect(a).to(equal(4))
            }

            it("resets a") {
                expect(a).to(equal(5))
            }

            context("deeper nesting") {
                var b: Int!
                beforeEach {
                    b = 10 + a
                }

                it("keeps a") {
                    expect(a).to(equal(5))
                }

                it("sets b") {
                    expect(b).to(equal(15))
                }

                context("even deeper nesting") {
                    var c: Int!
                    beforeEach {
                        a = 100 // We change `a` here due to slightly different test situation
                        c = 1000
                    }

                    it("overrides a") {
                        expect(a).to(equal(100))
                    }

                    it("keeps b") {
                        // ERROR THIS FAILS because b has been set earlier when `a` was 10,
                        // instead of lazily evaluated with
                        // the new value of `a`, 100.
                        expect(b).to(equal(110))
                    }

                    it("sets c") {
                        expect(c).to(equal(1000))
                    }
                }
            }
        }
    }
}
```

**Comment by jwfriese** [comment]
Hi @seansu4you87,

I want to make sure I understand your request correctly, so let me give a couple examples. 

Your particular case can actually be satisfied with a computed property:
```swift
//... some more code above
            context("deeper nesting") {
                // change this: 
                // var b: Int!
                // into this:
                var b: Int { return 10 + a }
                
                it("keeps a") {
                    expect(a).to(equal(5))
                }
                
                it("sets b") {
                    expect(b).to(equal(15))
                }
                
                context("even deeper nesting") {
                    var c: Int!
                    beforeEach {
                        a = 100 // We change `a` here due to slightly different test situation
                        c = 1000
                    }
                    
                    it("overrides a") {
                        expect(a).to(equal(100))
                    }
                    
                    it("keeps b") {
                        // This will pass now because b is evaluated in the moment taking into account
                        // the value of a. 
                        expect(b).to(equal(110))
                    }
                    
                    it("sets c") {
                        expect(c).to(equal(1000))
                    }
                }
            }
```
I think you're asking for something different, though. Is your expectation that the property is computed the first time, and stored thereafter? With this behavior, the following tests would fail:

```swift
//... some more code above
            context("deeper nesting") {
                var b: Int { return 10 + a }
                
                it("keeps a") {
                    expect(a).to(equal(5))
                }
                
                it("sets b") {
                    expect(b).to(equal(15))
                }
                
                context("even deeper nesting") {
                    var c: Int!
                    beforeEach {
                        a = 100 
                        c = 1000
                    }
                    
                    it("overrides a") {
                        expect(a).to(equal(100))
                    }
                    
                    it("keeps b") {
                        // This will pass now because b is evaluated in the moment taking into account
                        // the value of a. 
                        expect(b).to(equal(110))

                        // ... but the next test will fail because the value of a will have changed.
                        a = 1000
                        expect(b).to(equal(110)) // fails because b, a computed property, will now return 1010
                    }
                    
                    it("sets c") {
                        expect(c).to(equal(1000))
                    }
                }
            }
```
You can't use the ```lazy``` keyword because you cannot use it for local variables, so it would seem that we would require kind of construct built into Quick to satisfy this need.  

Does this accurately capture what you're looking for?

**Comment by seansu4you87** [comment]
@jwfriese thanks for the tip on computed properties, I didn't realize I could use them in this way.  I think the use of computed properties satisfies most of the use cases of test set up.  If you really need to change the value of a `let`, in the middle of an `it` example, u can just write another `it` statement.

However, I think you're right in that the value should be lazily computed once, and unsettable afterwards, to prevent user error.

**Comment by seansu4you87** [comment]
@jwfriese actually, I didn't understand how computed properties work when I first answered (new to swift!).  I ran into an issue where I actually need the memoization of these properties, and it's pretty common.

Imagine I want to lazily declare a view controller and have it be memoized:

```
describe(...) {
    var ctrl: ViewController! { return ViewController(state: state) }
}
```

Then deeper in the nesting, I want to make a slight modification to the view controller's dependency, the `state`.  Since calling `ctrl` re-executes that block everytime, any modifications I've made to the view controller are lost, and my test state will be invalid.

How high of a priority is this for you guys?  This ability to lazily evaluate and memoize properties for each `it` statement is huge for how I test.  It allows to drive out edge cases while keeping the test set up sane.

I'm happy to help contribute something here, but I'm not well versed in Swift, so I could use some guidance in how to design these feature.

**Comment by modocache** [comment]
Thanks for the interest, @seansu4you87!

We've discussed adding `let` to Quick before in #290.

My conclusion was that while I don't want to add `let` to Quick directly, I do want to enable adding it via a plugin of some kind--like how [rspec/rspec-its](https://github.com/rspec/rspec-its) works.

The best way to contribute to this effort is to read the discussion in #290, then either:

1. Answer the questions in #394, then implement a plugin feature.
2. Chime in on #231.

Personally, I think answering the questions in #394 is the most impactful thing that can be done here.
