### ISSUE TITLE
Turn `script/release` into a Rake task

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#467]
Just a personal preference. I find shellscripts harder to debug.

**Comment by ashfurrow** [comment]
We should consider doing this for Nimble, too, since they currently have similar-ish release scripts anyway.

**Comment by phatblat** [comment]
Agreed. It should be easy to copy over to Nimble once #475 is complete.

**Comment by ikesyo** [comment]
Closing this as part of issue cleanup.
