### ISSUE TITLE
Using xit or fit causes your custom Configuration beforeSuite/afterSuite not to run

### ISSUE THREAD

**Issue by JeffBNimble** [Quick/Quick#482]
If you create a custom Configuration class and add your own custom closures for:
* beforeSuite,
* afterSuite,
* beforeEach
* afterEach

and then use fit (focused it) or xit (exclude it) on any of your Quick tests, the configuration closures for beforeEach and afterEach are called, however the beforeSuite and afterSuite closures are not.

If there are no focused/excluded tests in the suite, then the beforeSuite and afterSuite closures are invoked.

**Comment by briancroom** [comment]
Hey @JeffBNimble, thanks for the bug report.

While trying to reproduce this, I'm seeing `beforeSuite` be called as-expected in all cases, but `afterSuite` being left off when focused or excluded tests are present. Can you confirm whether this is what you are experiencing as well?

**Comment by JeffBNimble** [comment]
@briancroom Yes, somehow I incorrectly reported the bug. The behavior I am seeing is identical to yours. I am getting `beforeSuite` being called as-expected. I am NOT seeing `afterSuite` being called when focused or excluded tests are present.
