### ISSUE TITLE
Documentation Mock

### ISSUE THREAD

**Issue by takecian** [Quick/Quick#485]
Add document which describes Mock and how to use Mock in Swift.

**Comment by modocache** [comment]
Awesome! :+1:

**Comment by istx25** [comment]
I guess this issue can be closed now since #487 has been merged?

**Comment by modocache** [comment]
Yup, thanks for the reminder!

**Comment by deveras** [comment]
Hi guys,

I was reading https://github.com/Quick/Quick/blob/master/Documentation/en-us/TestUsingTestDoubles.md and wanted to note that the following:

Mock object: Used for receiving output from a test class.
Stub object: Used for providing input to a test class.
Fake object: Behaves similarly to the original class, but in a simplified way.

They do not follow the definitions of ISO/IEC/IEEE 24765:2017 (Systems and software engineering --Vocabulary) where:

Mock object is a temporary dummy object created to aid testing until the real objects become available
Stub is a computer program statement substituting for the body of a software module that is or will be defined elsewhere.

For consistency, it might be good idea to update the documentation and follow standards to avoid confusion and ease understanding unless the intention is to deviate from what common, and if so, what are the advantages introduced? Do we want to be a class apart?
