### ISSUE TITLE
Xcode 7.2.1 crashes when using Quick and Nimble

### ISSUE THREAD

**Issue by SimonBacher** [Quick/Quick#495]
I'm using Quick and Nimble to run tests for an iOS app. The tests run fine, but when a test fails, and I click on the failing test in the test navigator, Xcode is not responding. Activity Manager shows Xcode consumes 100% CPU and I have to "force quit" Xcode. Is this a known issue? How to solve this?

**Comment by modocache** [comment]
Perhaps not exactly known, but this does seem related to https://github.com/Quick/Quick/issues/160. Let's see if there's something we can do here.

**Comment by SimonBacher** [comment]
I fixed it by reducing the size of my test file. I also noticed that the test in #160 contained Japanese writing - my test file contained chinese characters (they showed up in the expected result). But no idea whether that's related to the issue.

**Comment by istx25** [comment]
@SimonBacher: Did you ever experience this problem again (in future Xcode versions)?

**Comment by SimonBacher** [comment]
No - so I'm closing this now.

**Comment by istx25** [comment]
Thanks!
