### ISSUE TITLE
"Cannot invoke `to` with an argument list of type `(NMBMatcher!)`"

### ISSUE THREAD

**Issue by justinmakaila** [Quick/Quick#498]
![screen shot 2016-03-10 at 15 21 11](https://cloud.githubusercontent.com/assets/1638996/13683281/e0f57378-e6d3-11e5-948b-513c5101804b.png)

I'm not sure what to make of this. 

Let me know if you need anything else from me

`user.toJSON(...)` returns a `JSONObject` which is defined as
```
typealias JSONObject = [String: AnyObject]
```

`testUserWithRelationshipJSON()` returns `[String: AnyObject]`

**Comment by jeffh** [comment]
Hey @justinmakaila,

I think you're receiving that error message because `AnyObject` isn't equatable. It's an ideal error message from Swift, but that's the underlying cause.

**Comment by istx25** [comment]
@justinmakaila: I believe @jeffh answered your question. Please feel free to comment back if you're still experiencing problems with this and we can reopen the issue.
