### ISSUE TITLE
Swift 2.2 warnings

### ISSUE THREAD

**Issue by paulz** [Quick/Quick#503]
Thank you for awesome framework we use it daily!

Would it be possible to fix Swift 2.2 warnings showing in Xcode7.3. We could generally ignore them, but our [travis-ci.com](http://travis-ci.com) log gets overwhelmed with those warnings and does not have space left to show test failures:

```
This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log.
```

⚠️  /Pods/Quick/Sources/Quick/DSL/DSL.swift:166:105: __LINE__ is deprecated and will be removed in Swift 3, please use #line

public func itBehavesLike(name: String, flags: FilterFlags = [:], file: String = __FILE__, line: UInt = __LINE__, sharedExampleContext: SharedExampleContext) {
                                                                                                        ^~~~~~~~

⚠️  /Pods/Quick/Sources/Quick/DSL/DSL.swift:201:79: __FILE__ is deprecated and will be removed in Swift 3, please use #file

public func xit(description: String, flags: FilterFlags = [:], file: String = __FILE__, line: UInt = __LINE__, closure: () -> ()) {
                                                                              ^~~~~~~~

⚠️  /Pods/Quick/Sources/Quick/DSL/DSL.swift:201:102: __LINE__ is deprecated and will be removed in Swift 3, please use #line

public func xit(description: String, flags: FilterFlags = [:], file: String = __FILE__, line: UInt = __LINE__, closure: () -> ()) {
                                                                                                     ^~~~~~~~

**Comment by modocache** [comment]
Thanks! Yeah, will do.

I'm unable to download Xcode 7.3 at the moment. I might be able to just run a Swift 2.2 snapshot with Xcode 7.2. Alternatively, I'd be happy to review a pull request like https://github.com/Quick/Nimble/pull/269, but for Quick!

**Comment by phatblat** [comment]
I just submitted #504 for this.

**Comment by phatblat** [comment]
@paulz this is fixed now in master. Have you had a chance to test it?

**Comment by paulz** [comment]
Yes, thank you! Works now. No warnings, yay!

**Comment by phatblat** [comment]
Awesome. I'll close this issue then.
