### ISSUE TITLE
Still not getting autocompletion when installing with Cocoapods

### ISSUE THREAD

**Issue by ivanruizscm** [Quick/Quick#509]
Xcode version 7.2.1
cocoapods 0.39.0

Installing Nimble (3.2.0)
Installing Quick (0.9.1)

![captura de pantalla 2016-03-29 a las 17 45 09](https://cloud.githubusercontent.com/assets/15628215/14114103/0e611fae-f5d6-11e5-81eb-b77d357dd7ea.png)

**Comment by ivanruizscm** [comment]
[testProject.zip](https://github.com/Quick/Quick/files/207996/testProject.zip)

Here is my project emptied just with 1 test

**Comment by briancroom** [comment]
@ivanruizscm I was just able to download your project and get autocomplete working after poking around for a few minutes. A couple of things I did which may be relevant:
* Delete the *entire* `~/Library/Developer/Xcode/DerivedData` directory, which includes the `ModuleCache`
* Explicitly build (`Cmd+B`) the `Quick`, `Nimble`, and `Pods-NextVisitTests` targets after enabling their schemes from the Manage Schemes dialog.

Good luck!

**Comment by ivanruizscm** [comment]
@briancroom works!

**Comment by briancroom** [comment]
I'm glad to hear it! I don't have any insight into *why* it works, though. Xcode is fickle. ¯\_(ツ)_/¯

**Comment by gtsifrikas** [comment]
I found out that works quite reliable if you you choose from the Scheme selector your test target  , run them once in the start and then keep writing/running keeping this target.

**Comment by weijian19391** [comment]
Hi! the autocomplete is still not working when i did the steps @briancroom suggested. 
I'm using Xcode 8.2, Nimble 6.1.0, Quick 1.1.0 

Any idea what are the things i can try?

**Comment by gabrieloliva** [comment]
I'm still getting this issue...
