### ISSUE TITLE
Consider removing pod versions from readme

### ISSUE THREAD

**Issue by ashfurrow** [Quick/Quick#519]
Currently the readme has the current pod file description:

```rb
def testing_pods
    pod 'Quick', '~> 0.9.0'
    pod 'Nimble', '~> 3.2.0'
end
```

Which will work probably, but it does create some overhead for us. For example, Nimble is at 4.0.1 now, and this Podfile would constrain it to using a 3.2.x. According to the [CocoaPods documentation](https://guides.cocoapods.org/syntax/podfile.html#pod):

> ~> 0.1.2 [indicates] Version 0.1.2 and the versions up to 0.2, not including 0.2. This operator works based on the last component that you specify in your version requirement. The example is equal to >= 0.1.2 combined with < 0.2.0 and will always match the latest known version matching your requirements.

So we either need to be more careful about updating the versions in the readme as Quick and Nimble have releases, or we should remove them altogether and let CocoaPods manage it for the users (which I would recommend). Happy to discuss!

**Comment by briancroom** [comment]
I concur with removing the versions here - this feels like a unnecessary maintenance burden that we can easily do without.

**Comment by briancroom** [comment]
Fixed on master by https://github.com/Quick/Quick/commit/e36d15b321b626df914ea031a761be6e77990027.
