### ISSUE TITLE
CI is flaky due to buggy xcodebuild

### ISSUE THREAD

**Issue by briancroom** [Quick/Quick#520]
Our OS X build on Travis is incredibly flaky right now. See e.g. [these](https://travis-ci.org/Quick/Quick/builds/122863200) [builds](https://travis-ci.org/Quick/Quick/builds/124912462). The underlying issue appears to be a bug in Xcode 7.3's `xcodebuild` which results in `xctool` hanging just before it starts to execute tests. There is some discussion of the issue [here](https://github.com/facebook/xctool/issues/689) and the consensus currently seems to be that there's not much to be done besides wait for a fix.

I'm thinking that we should either
1. Disable the `xctool` invocations for the Travis build altogether for now, or
2. Split the `xctool` piece out to a separate job, so it's easy to verify if the `xcodebuild` test run succeeded, even if the overall build fails.

Thoughts @Quick/contributors?

**Comment by modocache** [comment]
I'm in favor of option 2. Some people use xctool out there, and I think we should try to support that use case. I don't think we'll succeed at that unless we integrate it into our CI somehow.

(Warning: Backseat programmer alert!) For https://github.com/facebook/xctool/issues/689, I wonder if it would be possible to avoid using `xcodebuild -showBuildSettings`. The argument is that that's the point of failure, and it's up to Apple to fix it? I wonder if `xctool` could avoid invoking that in the meantime...?

**Comment by briancroom** [comment]
It may indeed be possible, but I am definitely *not* the one to start messing with the `xctool` source. :shudder:

To be clear, I wasn't suggesting permanently disabling the `xctool` testing with option 1.. but it's hard to say how long it will be before there's a stable Xcode release that fixes the issue.

**Comment by modocache** [comment]
Oh yeah, I understand. But option 2 seems like it would help us at least be aware of how well `xctool` works with Quick (or in this case, even on its own).

**Comment by ashfurrow** [comment]
I think option 2 works, open to suggestions on an implementation. We could add a new entry to our CI matrix to text with xcodebuild vs xctool, or maybe some more cleverer?

**Comment by briancroom** [comment]
Taken care of by #525.
