### ISSUE TITLE
Cannot import Quick in Xcode 7.3 with CocoaPods

### ISSUE THREAD

**Issue by adampitchie** [Quick/Quick#526]
I have tried various ways to get Quick to import, but to no avail. I am installing Quick/Nimble verbatim to the documentation, adjusted for the target test names of course. This is the response I get when I try to import:

<img width="703" alt="screen shot 2016-04-30 at 10 56 25 pm" src="https://cloud.githubusercontent.com/assets/5626372/14940319/1d47d4da-0f27-11e6-88d7-8d00158e9f33.png">

The curious thing is that Quick/Nimble was working properly when I built via Carthage.

Any help is greatly appreciated. Thanks!

**Comment by briancroom** [comment]
These sorts of issues can be tricky to track down, unfortunately. Could you first try the steps that I listed on this issue? https://github.com/Quick/Quick/issues/509 And check your build log to see that the Quick pod target is getting built before your tests target. 

I'd also suggest trying to make sure all traces of the Carthage-built framework have been removed from the project file - no longer listing the old Quick.framework as a lib to link against, no longer including the Carthage dir as a framework search path. 

Good luck!

**Comment by adampitchie** [comment]
Wow it works. You are my new favorite human being. Thank you so much!

**Comment by adampitchie** [comment]
I don't know how often this occurs, but it'd be cool if there was a 'troubleshooting' section of the documentation with common problems. It could help reduce the time needed for support for these kinds of issues. What do you think?

**Comment by briancroom** [comment]
Since these steps have helped at least two people in the last few weeks, I think that would make some sense, yeah. Do you want to take a first stab at a PR with that info?

**Comment by adampitchie** [comment]
Sure!

**Comment by adampitchie** [comment]
Alright, started it here #527
