### ISSUE TITLE
Remove Quick.framework.zip from older releases

### ISSUE THREAD

**Issue by kballard** [Quick/Quick#528]
Older releases of this project (such as v8.0) include a Quick.framework.zip attachment, which Carthage uses instead of building from source. However, this doesn't work if the user is using a different version of Xcode than the one that was used to build Quick.framework (due to Swift code). Users can pass a flag to Carthage to make it skip prebuilt frameworks, but that means skipping even pure-objc frameworks. So the correct fix here is for frameworks that include Swift code to simply never have a a prebuilt framework download. I assume this is known to you since you stopped including the prebuilt framework in newer releases, but anyone who's still pinned to an older release (like we are) will hit this problem unless you remove the framework from the older releases too.

**Comment by modocache** [comment]
> I assume this is known to you since you stopped including the prebuilt framework in newer releases

I can't be certain about why they stopped being attached, but I've never included a prebuilt framework in releases that I've cut because I couldn't figure out how to successfully build them with Carthage 😅 

I'd happily do this, since I don't use prebuilt frameworks. Would it be prudent to give people who do use them a chance to chime in, though? I'm a bit out of my depth since I don't use Carthage or prebuilt frameworks.

**Comment by phatblat** [comment]
We'd be doing users a favor by removing the binaries. I use Carthage to pull in and build dependencies on a few projects and without the --no-use-binaries flag any Swift framework rarely build successfully.

**Comment by briancroom** [comment]
Yeah, I agree. I know that @jeffh removed the binary-generation from the release scripts for this reason. Using the pre-built frameworks is unfortunately a recipe for pain at this point, until ABI-compatibility is achieved.

**Comment by briancroom** [comment]
I've just finished removing the pre-built frameworks from both Quick's and Nimble's releases. Thanks for bringing this up @kballard. Hopefully this will save users some pain for the next while until Swift reaches a point where we can start using them again.
