### ISSUE TITLE
Failed when uploading app archive

### ISSUE THREAD

**Issue by pot8os** [Quick/Quick#535]
I got the following error when uploading app archive to `iTunes Connect`. Any idea?

![_2016-05-22_18_56_27](https://cloud.githubusercontent.com/assets/5249113/15453394/543c6e7c-204f-11e6-950c-2d89be5e27e6.png)

> Your Xcode version (eg - Xcode 7.0.1 7A1001)

7.3.1 7D1014

> Your version of Quick / Nimble (eg - v0.7.0 or git sha 7d0b8c21357839a8c5228863b77faecf709254a9)

- `Quick` v0.9.2
- `Nimble` v4.0.1

> What are the steps to reproduce this issue?

Uploading an archive which has `Quick` and `Nimble` as frameworks for tests. I'm confusing why frameworks for testing included into an archived app. Some build settings might be incorrect but I'm not sure.

> Are you using carthage or cocoapods?

I'm using `Carthage` v0.16.2 and my `Cartfile.private` is as follows.
```
github "Quick/Quick"
github "Quick/Nimble"
```

Thanks!

**Comment by pot8os** [comment]
I've resolved the issue by deleting `build` dir instead of `Delete Derived Data`. Sorry for creating spam here. Build cache seemed incorrect condition.

**Comment by hhgz9527** [comment]
@pot8os 

Could you tell me specific steps?

I have same issue...T.T
