### ISSUE TITLE
itBehavesLike block executes before beforeEach

### ISSUE THREAD

**Issue by MichaelMcGuire** [Quick/Quick#536]
I'm attempting to use a `sharedExample` to reduce some repetition in my code.  It requires a differently configured type for testing so I'm passing it in via the context:

    describe("with successful authentication") {
        
        var actualResponse: ServerResponse<ServerAuthenticationResponseData>!
        var boxedValue: Box<ServerResponse<ServerAuthenticationResponseData>>!
        
        beforeEach {
          (_, actualResponse) = stubCallAndWaitForSuccess(Fixtures.AuthenticationSessionSuccess, request: testRequest)
          boxedValue = Box(actualResponse)
        }
        
        itBehavesLike("populates the response") {
          ["actualResponse": boxedValue]
        }
    }

I'm using a simple `Box` value because my `ServerResponse<T>` type is a `struct` and the dictionary requires an `AnyObject` for the value.  

The tests are crashing when trying to access `boxedValue` inside of the `itBehavesLike` box because it executes before the `beforeEach`.  Is this expected behavior?  I'm not entirely sure how to use a `sharedExample` if it requires some setup in a `beforeEach`. 

Thanks!

**Comment by MichaelMcGuire** [comment]
And a couple months after opening this issue, I have figured out what I was doing wrong.  My bad! 😄

**Comment by ryanbaldwin** [comment]
@michaelmcguire I'm currently experiencing the same issue (`beforeEach` is executing prior to my `itBehavesLike` call)... what did you discover you were doing wrong?

**Comment by modocache** [comment]
No worries, @ryanbaldwin! I don't mind being your rubber ducky, so feel free to create issues/comment if you ever have any questions. :)

**Comment by istx25** [comment]
LOL. 

```
it("will not even get to this test") {
    // doesn't matter, little timmy has already died.
}

I have to say - I laughed at this @ryanbaldwin. 😬 

Glad you got it sorted out. :relaxed:

**Comment by istx25** [comment]
![d3e736bed9c147b06e4c8ca7851c9a81](https://cloud.githubusercontent.com/assets/6799989/20032789/4e17ca02-a392-11e6-9a6b-2d24e2522103.jpg)

**Comment by ryanbaldwin** [comment]
I guess the only thing that isn't clear for me right now is the chaining of beforeEach. How does it resolve? Outer first? It'd be great - likely in the QuickConfiguration section - if there were details of how the test setups are resolved... or are here details already and I failed to read?

Loving Quick + Nimble, btw. Great work. It's refuelled my passion for tests. I love the QuickConfiguration and the ability to reuse tests for common/similar components. That's what initially won me over and it continues to please me. Also -rad documentation. Y'all are hitting home runs.
