### ISSUE TITLE
MinimumOSVersion invalid.

### ISSUE THREAD

**Issue by cocotutch** [Quick/Quick#541]
Just FYI that when we're downloading with Carthage and building and running w/ Fastlane or with Xcode Application Loader, BOTH Quick AND Nimble trigger an error because the MinimumOSVersion field is set to 7.0 w/ Xcode 7.3. With that version, the MinimumOSVersion field must be set to 8.0 or greater, which forces me to check in built and modified frameworks to my repo to avoid Carthage being executed by CI and breaking the frameworks.

**Comment by istx25** [comment]
Hey @cocotutch! Would love it if you could submit a PR with this change.

**Comment by istx25** [comment]
I will try to get around to making this change (or seeing if it's still necessary) in the coming weeks.

**Comment by jeffh** [comment]
Hey @cocotutch, just to clarify: this is about setting the minimum deployment target for Quick & Nimble frameworks correct?

**Comment by istx25** [comment]
I'm going to let @jeffh take over with this.

**Comment by cocotutch** [comment]
Yeah @jeffh that's the one. Up to now I've been manually setting this in the Carthage checkouts whenever somebody rebuilds them. I've taken steps to prevent this, but it would be nice if we could have that already done. :+1:

**Comment by jeffh** [comment]
If you could submit a PR for Quick and Nimble that would be great!

Otherwise I'll fix it when I get some free time to work on it.

**Comment by jeffh** [comment]
This apparently was resolved in a previous commit (83eb4897ebae25093a0c39a775424de0d797bd2f). Closing
