### ISSUE TITLE
Remove SwiftPM dependency on Nimble?

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#545]
![screen shot 2016-06-13 at 3 38 32 pm](https://cloud.githubusercontent.com/assets/552921/16020656/0d232b54-317d-11e6-8501-13e6fcc98290.png)

It's unfortunate, but most [Swift package indexes list Quick as having a dependency](https://swiftpkgs.ng.bluemix.net/package/Quick/Quick): Nimble. This is not true, of course -- Quick isn't dependent upon Nimble, it simply uses Nimble as part of the test suite that tests Quick.

I'd prefer Quick be listed without any dependencies, but as far as I know the only way to do so (that we can do ourselves) is  by modifying `Package.swift` somehow, or by not using Nimble as part of the test suite. However, I like testing Quick and Nimble together, because I think many people use them together.

Is it possible to define a `Package.swift` that does not list Nimble as a dependency?

**Comment by takecian** [comment]
I saw comment in Package.swift and found following,
```
// TODO: Once the `test` command has been implemented in the Swift Package Manager, this should be changed to
    // be `testDependencies:` instead. For now it has to be done like this for the library to get linked with the test targets.
    // See: https://github.com/apple/swift-evolution/blob/master/proposals/0019-package-manager-testing.md
    dependencies: [ 
        .Package(url: "https://github.com/briancroom/Nimble", majorVersion: 3)
    ]
```

If my understanding is correct, we need to use future functionality to remove dependency on Nimble.

https://github.com/apple/swift-evolution/blob/master/proposals/0019-package-manager-testing.md#test-only-dependencies

**Comment by modocache** [comment]
Until that functionality is present, though, can we remove the `dependencies` altogether? Does SwiftPM build our test suite as well? Can we disable that?

**Comment by briancroom** [comment]
SwiftPM has matured tremendously since I was last actively working on this and wrote that note. There's a pretty good chance that `testDependencies` is functional now!

**Comment by takecian** [comment]
I tried using `testDependencies` on Travis CI, but it doesn't work.
I think it depends on Swift version on Travis CI. I'll check.

**Comment by takecian** [comment]
I updated swift version, and following error occured.

```
t-fujiki$ swift build
error: mixedSources("/Users/t-fujiki/Development/iOS/Quick/Sources/Quick")
```

I think that we have to support Swift3 in order to use `testDependencies `.
What do you think?

**Comment by ikesyo** [comment]
We should be able to workaround the case by using SwiftPM in the latest toolchain and `SWIFT_EXEC` env for building the sources as follows: 

- original: https://github.com/AliSoftware/Dip/blob/4.5.0/.travis.yml#L26-L38
- forked: https://github.com/ikesyo/Dip/commit/0bfa97c462a3db52817597a4ee28b60ecb9b318b

**Comment by takecian** [comment]
I added @ikesyo san's workaround. I found build error.

```
/home/travis/build/Quick/Quick/Sources/Quick/QuickSpec.swift:1:8: error: no such module 'XCTest'
import XCTest
```
DEVELOPMENT-SNAPSHOT-2016-05-09-a might not contain XCTest?

**Comment by istx25** [comment]
I noticed Nimble is [still listed as a dependency](https://swiftpkgs.ng.bluemix.net/package/Quick/Quick). Would anyone be able to finish this issue off?

**Comment by modocache** [comment]
> DEVELOPMENT-SNAPSHOT-2016-05-09-a might not contain XCTest?

Indeed, none of the Swift snapshots contain corelibs-xctest for now. I believe they will start including corelibs-xctest as of Swift 3.0. So I think @ikesyo's solution might work, but I guess on only certain versions of Swift...

It might be best to think of a way of addressing this *after* we work out a general strategy for supporting multiple Swift versions.

**Comment by istx25** [comment]
Okay, sounds good. We can come back to this later.

**Comment by takecian** [comment]
According to [apple/swift-package-manager/pull/597](https://github.com/apple/swift-package-manager/pull/597), as of now we have no way to remove dependency of Nimble..

**Comment by modocache** [comment]
We'll have to wait for Swift evolution to bring it back, I guess. I'll keep an eye out for a proposal.

**Comment by istx25** [comment]
This seems not possible for now so I'm going to temporarily close this. If SPM supports this functionality again in the future, we can totally open this again and complete what's necessary.

**Comment by modocache** [comment]
This is still something I'd like to do, though. Could we keep this issue open and add a "blocked" tag? I'd like to be able to reference an open issue if I find the time to bring this up with the SPM folks.

**Comment by istx25** [comment]
Sounds good to me.

**Comment by jeffh** [comment]
Resolved by https://github.com/Quick/Quick/commit/be559b9da79cb2eaf3b1d136b2ddab86128068d0.
