### ISSUE TITLE
Xcode Code Coverage

### ISSUE THREAD

**Issue by XBeg9** [Quick/Quick#556]
https://developer.apple.com/library/ios/documentation/ToolsLanguages/Conceptual/Xcode_Overview/CheckingCodeCoverage.html

I am not getting any test coverage, who knows what it can be?

![imageprocessing xcworkspace 2016-07-01 11-16-30](https://cloud.githubusercontent.com/assets/872907/16515890/5ce09c2c-3f7d-11e6-923c-1438582310b9.jpg)

**Comment by istx25** [comment]
Hey @XBeg9. Thanks for reaching out. Would love to see a sample project for us to reproduce the issue. From there we can work out what the issue is and help you find a solution. Cheers!

**Comment by XBeg9** [comment]
@istx25 was my bad, sorry. From Testing target works good.

**Comment by RafaelPlantard** [comment]
@XBeg9 what was your problem?!

**Comment by chrismcleod** [comment]
I'm new to ios but in xcode 8.1 if you check Show Test Bundles in upper right, you can get some coverage info, though now there are two things.
