### ISSUE TITLE
Quick can't recognize a moduleName for Unit test targets containing a space in the name

### ISSUE THREAD

**Issue by MP0w** [Quick/Quick#557]
Hi! I had an issue trying to run a single test from the test navigator: 0 tests were performed.  
I searched for existing issues and found #534 (after debugging seems unrelated - no space in the file path).  
I tried to debug the issue and looks like in `testCaseClassForTestCaseWithName(name:)` Quick fails to resolve the module name and returns nil. This is caused by my test target having a space in the name (Kakapo iOSTests), the path of the bundle contains a space: "/path/Kakapo iOSTests.xctest" while the module name (created by Xcode) is `Kakapo_iOSTest`. NOTE: `String+Filename` fails because of the space but the module name wouldn't be correct even if the space was escaped.

I can create a PR but I'm not sure what's the proper behavior:
1. Space in the target name (actually in the bundle path) should be avoided -> then we might just add an assert
2. Since Xcode use underscore `_` for the module name instead of spaces we might just replace it (kind of bad)
3. Another proper way to identify the module name? The module name might be completely different than the bundle filePath (if you specify a different module name than the default it won't work)

I know the preferred way to run a single test is `fit` but I would prefer a crash or failure if something goes wrong when running the tests from the navigator, running 0 tests successfully is a misleading result.

**Comment by istx25** [comment]
@modocache @jeffh: Would love it if you chimed in on this.

**Comment by modocache** [comment]
> Since Xcode use underscore _ for the module name instead of spaces we might just replace it (kind of bad)

This seems like a good solution to me!

**Comment by jeffh** [comment]
I agree with @modocache.

**Comment by MP0w** [comment]
👌🏼 I'm in holidays right now. I can submit a PR next week

**Comment by istx25** [comment]
Awesome @MP0w! Thank you. Looking forward to seeing the PR come through. 😸

**Comment by MP0w** [comment]
PR is open, sorry for the delay

**Comment by istx25** [comment]
No worries. Thanks for submitting the PR. I'll try to review it asap. :)
