### ISSUE TITLE
No Auto-completion 

### ISSUE THREAD

**Issue by grifas** [Quick/Quick#564]
Hi,

I'm getting a serious issue. I have no completion in my testings files ! 
One day I had it and one day it disappeared :/

It's very frustrating and testing quickly becomes boring because I have to search the meanings of methods ...

I use :
```
pod 'Quick'
pod 'Nimble'
``` 

Someone have a solution ?

**Comment by modocache** [comment]
Hmm, I don't think there's much I can do here without more information. Did you try deleting derived data, quitting Xcode, opening it again, and then rebuilding your tests? If that doesn't solve your problem, could you try to provide a sample project that demonstrates the problem?

**Comment by grifas** [comment]
I tried all you said but nothing. I tried to create a new project with only Quick and Nimble pods and when I create a test file, I have the auto-completion but not in my big project :/

**Comment by sunshinejr** [comment]
Ok, so I'm having the same issue in my big project as well (tried clearing everything), got a workaround but didn't have time to look why exactly it works. Maybe it will help you as well:

1. Go to your project settings.
2. Add to linked libraries Quick & Nimble.
3. Clean your derived data: `rm -rf ~/Library/Developer/Xcode/DerivedData/*`
4. Clean and build the project.
5. Now you should have the syntax, you can remove the libraries from project settings.

**Comment by grifas** [comment]
I already tried this but it did not work :/ and when I want import Quick module, it doesn't find it :/

**Comment by grifas** [comment]
Ok I resolved my issue ! I followed the instruction of ```daneov``` at https://github.com/Quick/Quick/issues/402

I choose Quick Scheme and built it and choose my scheme. When I import, Quick Module is findable and completion works !

Thank you !
