### ISSUE TITLE
Quick v0.9.3

### ISSUE THREAD

**Issue by sharplet** [Quick/Quick#566]
I think it would be great to cut a new release with Swift 2.3 support.

**Comment by modocache** [comment]
Absolutely!

**Comment by IvoPintodaSilva** [comment]
+1

**Comment by sharplet** [comment]
FWIW I don't have GPG set up (yet — going to have to figure it out at some point), so I can't create the release.

**Comment by modocache** [comment]
GPG is pretty nice. Plus, these days, it gives you that cool "Verified" badge next to your GitHub commits! 😄 

In any case, I'm on it. I'll cut a release sometime tonight or tomorrow night.

**Comment by modocache** [comment]
Done! https://github.com/Quick/Quick/releases/tag/v0.9.3

One snafu, though: I signed the release with my Facebook email address, instead of my personal one. Whoops! As a result, it's not signed; you'll just have to trust me. 😉
