### ISSUE TITLE
[Contributor Happiness] List of organizations that use Quick/Nimble

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#568]
> I mentioned this to @istx25 in an email, but I think one big area the Quick org can do better is to recognize the work done by our contributors. Here's one suggestion on how we can improve there.

Since no one ships Quick or Nimble as part of their app, we never show up in any of [those "top used libraries in iOS apps" blog posts](https://medium.com/ios-os-x-development/libraries-used-in-the-top-100-ios-apps-5b845ad927b7). But many people do use Quick and Nimble, and they appreciate our work. To help remind contributors of this, it'd be great to have a list of organizations that use Quick/Nimble, or testimonials, or something.

@istx25, if you could create a space to put this list, I'll encourage people to list their organization. I know a few companies off the top of my head that use Quick, for example, I could reach out to them.

**Comment by istx25** [comment]
Awesome, @modocache! I'll get on this soon. 😸

**Comment by istx25** [comment]
Done! Now all we need is projects for the list.

>Many apps use both Quick and Nimble however, as they are not included in the app binary, neither appear in “Top Used Libraries” blog posts. Therefore, it would be greatly appreciated to remind contributors that their efforts are valued by compiling a list of organizations and projects that use them. Does your organization or project use Quick and Nimble? If yes, [please add your project to the list](https://github.com/Quick/Quick/wiki/Projects-using-Quick).

https://github.com/Quick/Quick#projects-using-quick

**Comment by istx25** [comment]
Please add your projects @Quick/core.

**Comment by ashfurrow** [comment]
So that's adding them to the wiki, right?

**Comment by istx25** [comment]
Yes please @ashfurrow. The link is above.

**Comment by ashfurrow** [comment]
Done.
