### ISSUE TITLE
[Contributor Happiness] Testimonials/surveys

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#570]
Similar to https://github.com/Quick/Quick/issues/568, it'd be nice to hear *why* people use Quick and Nimble. Are there features they love? Are there features that are just OK? Are there some features we have that no one uses?

For purely positive "testimonials", maybe we can add that to the [Who Uses Quick wiki](https://github.com/Quick/Quick/wiki/Projects-using-Quick) -- "What benefits has using Quick had in your organization/test suite?". For surveys, maybe we can use some other system like SurveyMonkey or something.

**Comment by istx25** [comment]
In an alternative route, I think it would be cool to get a static webpage up for Quick/Nimble with links to documentation (something else we wanted to focus on) as well as provide these testimonials and whatnot. Feedback testimonials/things we can work on should probably just be directed to GitHub issues, no?

**Comment by modocache** [comment]
Yup, sounds great!

**Comment by istx25** [comment]
I'll add it to my list of tasks to do, but we could start with designing what the static website for Quick could look like. I'm not a web developer but I may know of a few people who would be willing/interested in contributing. Are there any suggestions/guiding principles that I should keep in mind when designing the first draft (in Sketch)?

**Comment by istx25** [comment]
I was thinking about this more and I think for now we should setup another wiki post to get it going and then create a page for the testimonials once we make the website for documentation.

**Comment by istx25** [comment]
I have added a "Who Uses Quick" page in the Wiki and added one testimonial. https://github.com/Quick/Quick/wiki/Who-Uses-Quick
