### ISSUE TITLE
How we can add a .feature file in a swift project and how the .feature file is being integrated. 

### ISSUE THREAD

**Issue by abhaythakur** [Quick/Quick#572]

**Comment by istx25** [comment]
I'm not familiar with .feature files so I will have to read up on this topic before I can accurately/properly answer your question. Mind providing more information?

**Comment by istx25** [comment]
@abhaythakur: Please respond within 7 days or I will close the issue for inactivity.

**Comment by modocache** [comment]
Yeah, I'm really not sure what this could be referring to. More details, please! :)

**Comment by pedrovereza** [comment]
The only tool I know of that uses `.feature` files is [Cucumber] (https://cucumber.io/docs/reference), which is used to create BDD-like tests.

I think this may be a confusion on how to use Quick, as we don't have `.feature` files to define test cases

**Comment by modocache** [comment]
Ah, yes, Quick doesn't really resemble Cucumber, and we don't have any plans to. So I don't think there's anything to do here, except maybe help @abhaythakur if they're having trouble learning how to use Quick.

**Comment by istx25** [comment]
Oh okay. Thank you @pedrovereza for clearing that up. I googled a bit when @abhaythakur originally opened the issue but I couldn't find anything. And by all means, if you need any help with quick or how to get started with quick - I recommend heading over to our documentation which covers a lot of topics, even related to testing but not Quick itself.

https://github.com/Quick/Quick/tree/master/Documentation

**Comment by istx25** [comment]
I will close this issue. @abhaythakur, if you need any help please open another issue about that specific problem/question. Cheers!
