### ISSUE TITLE
Hubot for Quick / GitHub management

### ISSUE THREAD

**Issue by istx25** [Quick/Quick#575]
I've seen this in other open-source projects but I couldn't find some hard examples. I'm pretty sure Parse and Realm do this but I may be incorrect. I think we should automate some of the management experience for Quick in GitHub issues.

I've found that my initial question for inquiries are to provide more information, adding tags, etc is done by me. I would love if we could automate as much of this as possible. In addition to that, it would be cool if the bot would give warnings if the issue is inactive and closes the issue automatically if someone from the core team has responded but the OP has not.

Thoughts?

It would be cool to evaluate our options for this.

**Comment by bmunkholm** [comment]
At Realm we didn't make a "bot" - we like the human touch for support :-) But we made a small script that provides a daily overview of issues that are not responded to (and their age) and older issues that need follow-up. This is then posted in the teams Slack channels. The new automatic issue template in GitHub helps a lot - and doesn't require any custom scripts.

**Comment by istx25** [comment]
Oh okay. That is awesome. I mean, I don't know where I've seen it but it's an automatic responder and tagged for GitHub issues which adds tickets like "Waiting For User Response" "Needs more Information" etc so users don't have to. Any ideas where I've seen it? I'm pretty sure the tickets has "T:blah" in it as well

**Comment by bmunkholm** [comment]
That's Realm. We also use Waffle.io to manage the issues. "S:xx" is a status - equivalent to a column in the waffle board. So we move issues back and forth between columns. We also got a script that moves an issue from "S:Waiting for User" into our "inbox" (which lacks a "S:xx" label) in case a person outside our org has made the last comment.
The other kind of label "T:xx" indicates which type of issue it is. So all issues must have exactly one Type and one State label.
If it has interest, I don't see a problem open sourcing that - when we get a bit of time... :-)

**Comment by istx25** [comment]
I would love to see that. Thank you for your reply. It would be great to launch something similar for Quick. I'll check out Waffle.io in the meantime.

**Comment by istx25** [comment]
We'll revisit this in the future.

**Comment by wongzigii** [comment]
Hey @istx25 There is an awesome project call [danger](https://github.com/danger/danger), and has been shipped with lots of GitHub repo likes [Moya](https://github.com/Moya/Moya). Could we use something like this to automate the dirty job ? If yes, I would like to play around it and make this into Quick/Nimble. :)

**Comment by istx25** [comment]
I've heard of Danger but I've never got around to using it. I would love to use Danger in Quick/Nimble. I'll open up a new issue and assign it to you. Would love to see what you come up with. :)
