### ISSUE TITLE
Using Quick with UITests - waitForExpectation

### ISSUE THREAD

**Issue by jgreubel** [Quick/Quick#578]
Hey Quick Team!

We are using the Quick/Nimble testing suite on our Swift project and are having great success with it so far in a significantly sized test suite of 1000~ UnitTests and 10~ UITests.  

We've been using Nimble on our UITests since we started writing them, but recently we've tried using Quick to structure our UITests as well with overall success, however producing annoying warning message related to doing a expectationForPredicate & waitForExpectationsWithTimeout combo:

```
Questionable API usage: called -[XCTestExpectation fulfill] for Expect 
predicate `exists == 0` for object "In progress" ActivityIndicator after 
the test case in which the expectation was created is no longer running. 
Created in test -[JourneyTest (null)], current test is -[JourneyTest
Have_cool_things_happen]
```

I've found this related Issue #330, and there appeared to be a merged PR that exposed a QuickSpec.currentSpec() to use instead of _self_ for the XCTestCase.  I am having trouble finding that currentSpec method, is it still around?  Or is there another solution?  Bonus: Can it be used in a beforeEach block and still point to the correct spec?

Thanks in advance!

Using Carthage:
- Quick v0.9.3
- Nimble v4.1.0

**Comment by istx25** [comment]
Thanks for reaching out, @jgreubel. I'll need to do a little bit of digging, but I wanted to let you know that someone's on it! 👍 In the meantime, I'll rope in @modocache. Maybe he will have some initial thoughts or suggestions.

**Comment by palfvin** [comment]
@jgreubel @istx25 I believe the pull request being referred to is https://github.com/Quick/Quick/pull/331 from @pcantrell, which appears to not have been merged.  If there's nothing directly usable in Quick at this point, it would be great to get a workaround of some sort (i.e. some way to get a handle on the "real" spec at example execution time).  In any event, I appreciate the attention to this.

**Comment by pcantrell** [comment]
I've maintained a fork with #331 ever since it was rejected/deferred. It's been in real-world use on Siesta for over a year, and works like a charm.

**Comment by istx25** [comment]
Inactive question thread. Feel free to open again if you'd like to continue the conversation but there is a maintained fork of Quick with similar functionality (from my understanding).

**Comment by pcantrell** [comment]
No need to reopen this one, but it sure would be nice to get #331 or some equivalent feature merged so I can stop maintaining that year-old fork….

**Comment by istx25** [comment]
I would appreciate it if you could file another issue or PR so we can bring attention back to it and see what the community decides on, even if it's reimplementing the functionality in a different way.

**Comment by modocache** [comment]
Yeah, if those changes have been helping you out @pcantrell I wouldn't mind merging them, just send another pull request. Might as well put it in trunk!

**Comment by palfvin** [comment]
I would really appreciate that. We would like to use this, but aren't
comfortable leaving our client with any dependencies on a personal fork, no
matter how reputable!

**Comment by pcantrell** [comment]
New PR published: https://github.com/Quick/Quick/pull/645

**Comment by istx25** [comment]
Thanks @pcantrell. I'll review that asap.
