### ISSUE TITLE
Remove one of the continuous integration platforms

### ISSUE THREAD

**Issue by istx25** [Quick/Quick#586]
I don't see the point of having multiple CI platforms on the Quick project. I think we should remove one of them and fix the remaining one to work as effectively as possible.

1. Do people agree with me?
2. Which one(s) should we kick and which one should we keep?

**Comment by pedrovereza** [comment]
Agreed, no point having multiple CI platforms.

I feel that Travis is the one to keep, based on the config files. What we have for Circle CI is pretty basic compared to what's currently running on Travis.

**Comment by modocache** [comment]
+1, let's dump Circle CI for now.

**Comment by istx25** [comment]
Awesome. I'm pretty sure we'll need to fix up somethings with Travis to make it work more effectively as well.
