### ISSUE TITLE
ToEventually test not running

### ISSUE THREAD

**Issue by victoraugustolls** [Quick/Quick#590]
So, I have the following test:

    class UserHandlerTest: QuickSpec {
    
        override func spec() {
        
            describe("UserHandler") {
            
                context("Succeed") {
                
                    //Arrange:
                
                    let handler = UserHandler(withNetwork: NetworkMockFulfill(), keychain: KeychainMockFulfill())
                    let info = UserInfo(email: "test@gmail.com", password: "12345678", name: "Test", cpf: "12345678")
                    var success = false
                
                    describe(".createUser") {
                    
                        handler.createUser(withInfo: info) {
                            result in
                            switch result {
                            case .Success(let bool):
                                success = bool
                            case .Failure:
                                break
                            }
                        }
                        expect(success).toEventually(beTrue(), timeout: 5)
                    
                    }
                }
            }
        }
    }

When the test finishes, it appears `Test Succeeded` but there is no green checkmark, and nothing in the Xcode logs about this test. Any help?

**Comment by victoraugustolls** [comment]
I got it to working when I used:

> expect(success).toEventually(beTrue(), timeout: 5)

inside an `it` closure. Is this the expected behaviour?

**Comment by takecian** [comment]
Yes, `describe` is used for defining an example(test) group. To write tests, please use `it`.

**Comment by victoraugustolls** [comment]
Thanks!
