### ISSUE TITLE
Need to change directory tree to support SPM

### ISSUE THREAD

**Issue by takecian** [Quick/Quick#597]
I read [Proposal: SE-0019](https://github.com/apple/swift-evolution/blob/master/proposals/0019-package-manager-testing.md),  For Swift Package Manager, test modules needs to be in `Tests` directory. 

I think this means we need to change Quick directory tree,

as is,

    Package
    └── Sources
           ├── Quick
           ├── QuickTests
           └── QuickFocusedTests

to be like following,

    Package
    ├── Sources
    |     └── Quick
    └── Tests
            ├── General
            └── Focused

If Quick member agree to change this, i will do that at some point.
Any feedbacks are helpful.

**Comment by ikesyo** [comment]
This is already done in #510.

**Comment by takecian** [comment]
Oh, ok. Thanks @ikesyo san.
