### ISSUE TITLE
Release swift 3 branch on cocoapods

### ISSUE THREAD

**Issue by ldiqual** [Quick/Quick#608]
@modocache Now that Xcode 8 / Swift 3 is out, it would be fantastic to have an official Quick version on cocoapods that support swift 3, so we can stop relying on the `swift3` branch directly.

**Comment by pedrovereza** [comment]
Hey @ldiqual, I think a new release for Swift 3 is coming soon, see: https://github.com/Quick/Quick/pull/601#issuecomment-248664253

**Comment by tw-safad** [comment]
@pedrovereza when we can expect new release ?

**Comment by tcurdt** [comment]
why on earth was the swift3 branch removed??

**Comment by wongzigii** [comment]
@tcurdt @tw-safad Swift 3 branch has been merged into master and is pending for released! See #601

**Comment by ntus1017** [comment]
will it be released soon?

**Comment by damianesteban** [comment]
I hope so :)

**Comment by pedrovereza** [comment]
Aaaaand [it's out] (https://github.com/Quick/Quick/releases/tag/v0.10.0)

**Comment by damianesteban** [comment]
For some reason I'm still getting the following warning when I open the workspace:

`The targets “Nimble” and “Quick” contain source code developed with an earlier version of Swift.`

**Comment by tw-safad** [comment]
@pedrovereza We updated with the new versions . Still not able to import Quick and Nimble modules in swift test targets.

**Comment by damianesteban** [comment]
@tw-safad are you using cocoapods? If so, add this to to your `Podfile`:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
```

**Comment by perwyl** [comment]
@damianesteban i added that to the end of `Podfile`, still getting `No such module `Quick``

```
  def testing_pods
      pod 'Quick', '~> 0.10'
      pod 'Nimble'
  end
```

**Comment by tw-safad** [comment]
@damianesteban No luck . Still facing same issue . Not able to import Quick/Nimble module.

**Comment by dusek** [comment]
@tw-safad version of CocoaPods you use? I think for Xcode 8 / Swift 3, CocoaPods 1.1.0 is strongly recommended (if not required).

**Comment by tw-safad** [comment]
I used cocoapods 1.1.0.beta.1 version . Same issue with this version.

**Comment by tw-safad** [comment]
@dusek Thanks a lot . Its working now .

**Comment by filipszczepanski** [comment]
@perwyl check 'defines module' in your test target. It should be: Yes


<img width="300" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3180140/18854129/92fa167e-8449-11e6-9ada-d691ce2d5713.png">

https://github.com/Quick/Quick/blob/master/Documentation/en-us/SettingUpYourXcodeProject.md#testing-swift-code-using-swift

**Comment by istx25** [comment]
Closing since 3.0 has been released.
