### ISSUE TITLE
[Idea] Include prebuilt binaries for tagged releases for faster Carthage builds

### ISSUE THREAD

**Issue by Hammertime38** [Quick/Quick#611]
This applies to both Quick and Nimble, but I figured the general idea could just live here. Carthage supports downloading prebuilt binaries from Github releases, which are associated with semantic version tags. This means that instead of forcing users to build each platform scheme locally, Carthage will automatically detect a prebuilt framework + dSYMs associated with that version (if it exists) and download it via the Github API instead, which drastically reduces the time needed for a `carthage update`.

From a core contributor standpoint, this only means adding an additional step to the tagging/release process:

```
carthage build --no-skip-current
carthage archive
```

This first builds all dependencies _as well_ as the current project itself and then zips it up to be uploaded directly to the Github release page.

Let me know what you all think.

**Comment by istx25** [comment]
I'm a fan of this.

**Comment by ikesyo** [comment]
It seems that this was discussed in #528.

**Comment by modocache** [comment]
Yeah, I think all the arguments in #528 still apply. Sorry, but looks like we'll continue not attaching prebuilt binaries for now. Thanks for the idea, though!
