### ISSUE TITLE
Label for Hacktoberfest?

### ISSUE THREAD

**Issue by pedrovereza** [Quick/Quick#614]
Hey folks,

[Hacktoberfest](https://hacktoberfest.digitalocean.com/) starts next Saturday (10/01) and we can get some extra help by having trivial/not-complex issues tagged with label `Hacktoberfest` (the official website links to [this query](https://github.com/search?l=&q=state%3Aopen+label%3Ahacktoberfest&ref=advsearch&type=Issues&utf8=%E2%9C%93))

What you all think?

**Comment by modocache** [comment]
Yeah, I'd love to tag issues that newcomers to the Quick codebase could work on! I think @istx25 has done an excellent job in organizing our issues, and you could help!

I don't know about labeling them with "Hacktoberfest", though:

- It seems like many "featured projects" on their website don't include the label.
- The hard part is creating thoughtful issues and instructions for newcomers. Labeling things as "hacktober", then removing the label in November, seems like less impactful work.

**Comment by istx25** [comment]
Speaking of that. 😜

**Comment by istx25** [comment]
I like the idea of adding some kind of label for newcomers but I agree with @modocache that a tag called "Hacktoberfest" may not be the best route. Unless, we named it Hacktoberfest for the purpose of this month and renamed the tag later with a different name.

**Comment by istx25** [comment]
I also think we should get in on this opportunity because there is a lot of hype associated with Hacktoberfest and it would probably help potential contributors find us.

**Comment by pedrovereza** [comment]
I agree with both of you @modocache @istx25:

- Making the repository inviting to newcomers goes way beyond just having labels.

> I also think we should get in on this opportunity because there is a lot of hype associated with Hacktoberfest and it would probably help potential contributors find us.

Yes! That's what lead me to suggest the label creation, thanks for clarifying 😉 

- Having "Hacktoberfest" as a temporary label and renaming it later sounds cool 👍

**Comment by modocache** [comment]
I hadn't realized Hacktober was such a hyped up event! I guess I'm out of touch, I'd never heard of it before :sweat_smile:

If you find or create some starter tasks with good instructions for beginners, I'll gladly label them "Hacktober". :)

**Comment by ajeetrocks100** [comment]
yay \m/ #hacktoberfest, wait where is the label?

**Comment by istx25** [comment]
Feel free to look through the issues and find some that could be tagged for hacktoberfest.

**Comment by istx25** [comment]
We're effective at the end of October so I'm closing this. Sorry folks. :(

**Comment by modocache** [comment]
I can understand the festive nature of Hacktoberfest, but creating approachable issues with clear instructions on how to help strikes me as a year-round activity! No time like the present! :)

**Comment by istx25** [comment]
Totally! We'll work on it for next year and all around the year.

**Comment by Ajeet-Yadav** [comment]
Hope to see this project in Google summer of code.

**Comment by modocache** [comment]
Phew, do we even qualify? I don't think Quick fits in with the other projects.
