### ISSUE TITLE
Unable to find a specification for `Quick`

### ISSUE THREAD

**Issue by Faisalcs** [Quick/Quick#618]
Hi, I try to download and integrate Quick and Nimble to my project via Cocoapods version 1.1.0.rc.2 
and Swift 3.0 but It doesn't work. So can I have your help please. 

This is my pod file looks like 

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'BDD' do

  def testing_pods
    pod 'Quick'
    pod 'Nimble'
  end

  target 'BDDTests' do
    inherit! :search_paths
    testing_pods
  end

  target 'BDDUITests' do
    inherit! :search_paths
    testing_pods
  end

end

**Comment by wongzigii** [comment]
Hey @Faisalcs What error message did you come up against?

**Comment by Faisalcs** [comment]
HI @wongzigii, Sorry I forgot to write the error : This is what's happened if I run pod install 

Analyzing dependencies
[!] Unable to find a specification for `Quick`

**Comment by wongzigii** [comment]
Your Podfile works fine for me. Could you please run `rm -rf ~/.cocoapods/repos/master` and try `pod install` again?

**Comment by Faisalcs** [comment]
I did what You've said but it's been on cloning for a while !!! . Is that normal ? 

 pod install --verbose
  Preparing

Setting up CocoaPods master repo

Cloning spec repo `master` from `https://github.com/CocoaPods/Specs.git` (branch `master`)
  $ /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git master
  Cloning into 'master'...

**Comment by istx25** [comment]
@Faisalcs: It will take a fair bit of time but shouldn't take an excessive amount of time. Try a wired connection to the internet if possible or a better internet connection.

**Comment by wongzigii** [comment]
Just wait! It happened the same for me :)

**Comment by Faisalcs** [comment]
@wongzigii @istx25 Yeah. It works perfect. Thank you so much for you help. I really appreciate it.

**Comment by istx25** [comment]
Awesome. I'm going to go ahead and close the issue (since it sounds like @wongzigii helped resolve the problem you were experiencing). Feel free to open another issue if you need more help with another problem. :)
