### ISSUE TITLE
Problem with Travis CI and Linux?

### ISSUE THREAD

**Issue by istx25** [Quick/Quick#621]
I recently merged a PR (#620) and noticed that the CI failed due to a problem with the Linux part of the tests. I looked around and concluded that this isn't just with this PR so I think we have a problem with Linux. Not really sure where to start looking how to resolve this but I'll do some research. 

https://travis-ci.org/Quick/Quick/jobs/168831314

**Comment by ikesyo** [comment]
This is related to swiftenv. The env variable of `PLATFORM=linux` in `.travis.yml` is affecting Swift platform detection with regard to https://github.com/kylef/swiftenv/pull/61. We should rename the env variable (or unset it in the `travis-install-linux` script) to fix the failure.

**Comment by istx25** [comment]
Mind making that change? @ikesyo
