### ISSUE TITLE
Linker issues when building in release configuration on Linux

### ISSUE THREAD

**Issue by jpsim** [Quick/Quick#626]
I get the following linker issues when invoking `swift build -c release` in my SPM project that has Quick as a dependency:

```
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest6XCTestg7testRunGSqCS_9XCTestRun_'
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest6XCTests7testRunGSqCS_9XCTestRun_'
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest6XCTestm7testRunGSqCS_9XCTestRun_'
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest10XCTestCaseg5_nameSS'
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest10XCTestCases5_nameSS'
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest10XCTestCasem5_nameSS'
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest10XCTestCaseg16_allExpectationsGSaCS_17XCTestExpectation_'
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest10XCTestCases16_allExpectationsGSaCS_17XCTestExpectation_'
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest10XCTestCasem16_allExpectationsGSaCS_17XCTestExpectation_'
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest10XCTestCaseg17_performanceMeterGSqCS_16PerformanceMeter_'
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest10XCTestCases17_performanceMeterGSqCS_16PerformanceMeter_'
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest10XCTestCasem17_performanceMeterGSqCS_16PerformanceMeter_'
/SourceKitten/.build/release/Quick.build/QuickSpec.swift.o:/SourceKitten/.build/release/Quick.build/Hooks/SuiteHooks.swift.o:_TMC5Quick9QuickSpec: error: undefined reference to '_TFC6XCTest10XCTestCasem20continueAfterFailureSb'
```

This doesn't happen in debug mode (`swift build`).

If you have Docker installed and running on your Mac, you can trigger this by following these steps:

``` shell
$ git clone https://github.com/jpsim/SourceKitten.git
$ cd SourceKitten
$ docker run -v `pwd`:/SourceKitten swiftdocker/swift bash -c "cd /SourceKitten && swift build -c release"
```

I tried to trigger this in #625, but it didn't happen.

**Comment by istx25** [comment]
Thank you for reaching out. We will need to investigate this more. It would be awesome if you could try to reproduce this in a new environment.

**Comment by jpsim** [comment]
Just to be clear, what do you mean "new environment"? Would you like a more minimal repro case?

**Comment by istx25** [comment]
My apologies @jpsim. I was reading on my phone before and misunderstood the problem. I'll try to reproduce it on my machine and see what I come up with.

**Comment by jeffh** [comment]
Hey @jpsim,

That's a tricky error for sure. I'm guessing it's something related to testability with one of your dependencies, [Commandant](https://github.com/Carthage/Commandant), that's pulling in Quick as a dependency for XCTest. `swiftc` usually infers that flag only if your project directly imports XCTest.

SwiftPM currently doesn't have a way to separate test and non-test dependencies, so you'll have to remove all test dependencies from `Package.swift`. So your immediate solution is to change [Commandant](https://github.com/Carthage/Commandant)'s `Package.swift`:

```swift
let package = Package(
    name: "Commandant",
    dependencies: [
        .Package(url: "https://github.com/antitypical/Result.git", majorVersion: 3, minor: 0),
    ]
)
```

It's not a great solution, but it's the only one that's available at the moment 😟. I think there was a eventual goal to submit a swift evolution proposal for something like this, but I don't really know anything about the process of getting that ball rolling (/cc @modocache).

**Aside**: If you're feeling adventurous, you can enable testability by passing in `-enable-testing` flag like so:

```
swift build -c release -Xswiftc -enable-testing
```

But I haven't tried that on SourceKitten. Or in any project for that matter. It's not particuarly common to enable it for release mode.

**Comment by istx25** [comment]
I'll let @jeffh take over this issue since he knows a lot more about this than I do. Cheers! :)

**Comment by jpsim** [comment]
Thanks for digging into this @jeffh! You're spot on with your analysis. Seems the right solution to this is to have SwiftPM revive its support for `testDependencies` in the manifest.
