### ISSUE TITLE
Add support for Danger in Quick and Nimble

### ISSUE THREAD

**Issue by istx25** [Quick/Quick#631]
In #575, @wongzigii mentioned [Danger](https://github.com/danger/danger):

> There is an awesome project call [danger](https://github.com/danger/danger), and has been shipped with lots of GitHub repos likes [Moya](https://github.com/Moya/Moya/pull/716). Could we use something like this to automate the dirty job ? If so, I would like to play around it and make this happen in Quick/Nimble. :)

Looking forward to what you come up with. Feel free to document your progress here and discuss what we should/shouldn't implement in our danger file.

**Comment by wongzigii** [comment]
Closing.
