### ISSUE TITLE
Quick should fail silently when SwiftLint isn't installed

### ISSUE THREAD

**Issue by getaaron** [Quick/Quick#648]
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Create a `Cartfile`:

```ruby
github "Quick/Quick"
github "Quick/Nimble"
```

Run `carthage update`.

### What did you expect to happen?

I expected Quick and Nimble to install successfully.

### What actually happened instead?

Quick and Nimble installed successfully but displayed 4 warnings about `SwiftLint`.

```
$ carthage update
*** Fetching Nimble
*** Fetching Quick
*** Checking out Nimble at "v5.1.1"
*** Checking out Quick at "v1.0.0"
*** xcodebuild output can be found in /var/folders/0j/29ytx6wx0fg86sznfb4mqdph0000gn/T/carthage-xcodebuild.n4mp2t.log
*** Building scheme "Nimble-macOS" in Nimble.xcodeproj
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "Nimble-tvOS" in Nimble.xcodeproj
*** Building scheme "Quick-iOS" in Quick.xcworkspace
*** Building scheme "Quick-macOS" in Quick.xcworkspace
*** Building scheme "Quick-tvOS" in Quick.xcworkspace
warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint
warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint
warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint
warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint
```

I don't want SwiftLint, and this doesn't interfere with my use of Quick, so no warnings should be displayed.

### Environment

List the software versions you're using:

 - Quick: *1.0.0*
 - Nimble: *5.1.1*
 - Xcode Version: *8.1 (8B62)*
 - Swift Version: Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Carthage: *0.18.1* (Use `carthage version` in Terminal)

### Project that demonstrates the issue

No project required.

**Comment by getaaron** [comment]
I think it's OK to just delete the relevant `else` clauses in [lines 1384 – 1424 of `Quick.xcodeproj/project.pbxproj`](https://github.com/Quick/Quick/blob/e8f38facd1f3b37048d64323b817b6701735b5c1/Quick.xcodeproj/project.pbxproj#L1384-L1424).

**Comment by istx25** [comment]
Hi @getaaron. Thanks for filing this issue. We'll review and get #649 merged asap.
