### ISSUE TITLE
None of the tests are executed anymore

### ISSUE THREAD

**Issue by benediktreichert** [Quick/Quick#651]
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Installed Quick and Nimble via Cocoapods.
Wrote some tests. Built and ran them.

### What did you expect to happen?

Every test has to be executed each time i run the tests

### What actually happened instead?

All tests (including standard XCTests) are simply skipped and ignored after their first run. The get only executed one again when I change something in the source code, so the file has to be recompiled. I need to execute the test twice to be noticed. After execution, the test is then ignored again. 

### Environment

List the software versions you're using:

 - Quick: 1.0.0
 - Nimble: 5.1.1
 - Xcode Version: *8.1* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: Standard *3.0.1*
```
$ swift --version
Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)
```

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.2.0.beta.1* (Use `pod --version` in Terminal)

### Project that demonstrates the issue
[My complete project](https://github.com/benediktreichert/moodleinfo_ios)

# Additional notes
My Quick tests get recognised by Xcode as "runtime Tests"
See here: http://stackoverflow.com/questions/19699730/xcode-5-testing-symbol-rt-means-what
I have also this purple `rT` symbol on my Quick tests and they got only recognized after their initial launch or when i change the source code of a test so it has to be recompiled.

I also deleted the `Derived Data` folder and `xcuserdata` folders.

**Comment by danielsaidi** [comment]
I have the exact same problem. I have a large amount of tests in a project of mine, running Quick 0.10.0 and Nimble 5.0.0. The tests all run without problem.

Today, I created a new project and decided to use Quick 1.0.0 and Nimble 5.0.0. The initial test example ran just fine, but as soon as I added some general extensions and their tests from the old project to the new one, the test in the new project stopped running.

After commenting out all new tests, the initial test example started working again, so I started re-adding the new tests piece by piece.

For me, what made the tests fail was that one test file contained the QuickSpec class as well as some private classes used by that test. Once I moved the private classes to a separate file, the tests began to work once more.

Have a look at the two screenshots below - one is with the private classes inside the test class file, one is with the private classes moved out to a separate file:

<img width="389" alt="skarmavbild 2016-12-04 kl 10 18 56" src="https://cloud.githubusercontent.com/assets/429927/20865167/40810932-ba0b-11e6-898e-b6acca975eeb.PNG">
<img width="444" alt="skarmavbild 2016-12-04 kl 10 19 18" src="https://cloud.githubusercontent.com/assets/429927/20865166/407f2d88-ba0b-11e6-913d-7996e3060c9f.PNG">

**Comment by danielsaidi** [comment]
To clarify my last comment, I created my pod project using the CocoaPods `pod lib create` terminal command.

**Comment by Shedward** [comment]
I have the same problem with Cocoapods 1.1.1, Quick 1.0 and Nimble 5.0.0 in new pod created with `pod lib create`.

**Comment by danielsaidi** [comment]
That's the same setup that I have.

**Comment by benediktreichert** [comment]
_My **opinion**_: There are a couple of other issues where users are reporting that tests don't get executed, only the whole test suite can be executed or tests have to be prefixed with an f in code to execute them individually. This situation is very frustrating. I am disappointed and a little angry at the author of Quick because he doesn't mention any of the restrictions, limitations and current problems on the GitHub main page of Quick. I refactored all my XCTests to Quick and then noticed all these issues and limitations ☹️☹️. At the current state of Quick, the added "describe" and "context" abstractions Quick is bringing to the table are not worth dumping XCTest because of the induced limitations of not being able to execute single tests via the Xcode GUI and the bugginess of not executing tests when XCTests are present, etc.... There is some information regarding these limitations but you have to read the whole documentation. Please write these issues on the main page. I now refactor everything back to XCTests to finally get peace of mind! Sorry but the current state does **not** deserve v1.0.0. !!

**Comment by Shedward** [comment]
Hmm, seems I somehow fixed this by setting target application in *_Tests target:

![image](https://cloud.githubusercontent.com/assets/904623/20867909/6127ea40-ba81-11e6-9c27-49f3f8205c24.png)

@danielsaidi can you try this?

**Comment by MP0w** [comment]
@benediktreichert this project is open source and free, before depending on an OSS project you should look at the code and understand it (other than reading the whole documentation). Blindly using stuff is dangerous and stupid.
Blaming the author and maintainers  that worked hard on this project is really disrespectful since you didn't even try to check what's happening.
The source code is available, you guys can try to solve your problems before complaining.

**Comment by benediktreichert** [comment]
sry @MP0w but I just don't agree on this point. I did read the documentation before trying Quick and I was aware of the "not able to run single tests via UI" limitations. I also quickly skimmed through the open issues before using Quick. After careful thoughts, I tried the framework though. Even though there is no obligation for the authors and maintainers it would be honest to mention major issues. "It's open source" as an excuse for everything is valid, but I don't encourage this approach. If every author would act that way, it would be terribly frustrating to use frameworks, so I think you are just wrong in your opinion MP0w. Sorry for that, but I also disclosed my post to be my very personal opinion. In case you don't share it, it's nothing i'm interested in.

**Comment by danielsaidi** [comment]
@Shedward - Ok, this is SUPER strange. Before reading your comment about the host application, I trashed the project and was going to recreate it manually, without the CocoaPod script.

However, seeing your comment, I instead restored the project to verify that I had selected a host application. To my surprise, the test suite now worked perfectly, without me making any changes!

This is the same code that I trashed earlier. Now it works without any modifications. The only thing I've done with it is to restart XCode. 

I'm baffled, but happy that things now work...without no reason whatsoever.

**Comment by MP0w** [comment]
@benediktreichert  "it would be terribly frustrating to use frameworks"
- check the open issues
- check the code
- make sure you can maintain it when needed
- don't depend on your dependency
- give back to the project

Blaming the author/maintainers is not fair

**Comment by benediktreichert** [comment]
I completely agree with you on the described process. I don't think you have grasped the essence of what I said in my recent posts.

**Comment by danielsaidi** [comment]
@benediktreichert What do you mean with that you cannot run individual tests? You can tap the "play" button next to a QuickSpec to just run the tests in that spec. If you want more separation, you could have multiple QuickSpecs in a single file (see screenshot). If a test fail, that line gets highlighted. Isn't that enough?

<img width="458" alt="skarmavbild 2016-12-04 kl 19 37 00" src="https://cloud.githubusercontent.com/assets/429927/20868317/09f87456-ba59-11e6-90ee-939a53e248d6.PNG">

**Comment by benediktreichert** [comment]
Running more granular tests than the whole suite is not supported at the moment, this is mentioned in the depths of the documentation. I'm not criticizing the fact, but merely that it is not stated on the main page, because it is a major limitation. Several users (check open issues) are reporting that tests do not run at all under certain circumstances. You can look at my provided project to reproduce the issue or just look at the open issue section especially where i cross referenced this topic. These bugs are not stated anywhere in the readme or documentation which i highly reccommend to do, because it just kills your whole testing capabilities.

**Comment by MP0w** [comment]
This is exactly the same issue I had but for a different character: https://github.com/Quick/Quick/issues/557
Also dash `-` as to be replaced with an underscore
See the PR that fixed the issue with space https://github.com/Quick/Quick/pull/638
