### ISSUE TITLE
Cannot invoke 'toEventually' with an argument list of type '(NMBMatcher)'

### ISSUE THREAD

**Issue by ryanbaldwin** [Quick/Quick#657]
### What did you do?

I'm trying to run an asynchronous assertion on an Error value which should eventually be set by a dataTask.

### What did you expect to happen?

Well, I expected this to compile.

### What actually happened instead?

I'm getting the following error:

> Cannot invoke 'toEventually' with an argument list of type '(NMBMatcher)'

### Environment

 - Quick: *v0.10.0*
 - Nimble: *v5.1.1*
 - Xcode Version: *8.1 (8b62)*
 - Swift Version: *Xcode Default*
 - Carthage: *0.18.1*

### Project that demonstrates the issue
Can't give a link to the project as it's all internal, but here's the test:

```Swift
describe("its default submit") {
    it("forwards a noRequest error if the implementer fails to construct a request") {
        let postable = NilRequestPostable()
        var assertedError: Error?
        
        postable.submit() {
            response in
            switch response {
            case .failure(let error): assertedError = error
            default: break // do nothing
            }
        }
        
        expect(assertedError).toEventuallyNot(beNil(), timeout: 0.5)
        expect(assertedError!).toEventually(equal(HttpProtocolError.noRequest))
    }
}
```

The compilation error occurs on the final `expect`, and I'm super confused why. I'm just evaluating an Error value. I'm surprised this doesn't compile but also don't understand why. My apologies if this is a frivolous question, but much googling this morning isn't helping much so I figured I'd turn to the best supported maintainers in the OSS testing universe!

Cheers!

**Comment by ryanbaldwin** [comment]
Heyoooooo! I'm a dumb dumb. I never implemented `Equatable` on my HttpProtocolError enum. Whoopsies.

**Comment by jeffh** [comment]
Thanks for following up on the issue and congrats at solving your own problem. 😁
