### ISSUE TITLE
First class support for testing frameworks with Swift Package Manager

### ISSUE THREAD

**Issue by thislooksfun** [Quick/Quick#659]
Original title: Running code generated with `swift build` gives error `dyld: Library not loaded: @rpath/XCTest.framework/Versions/A/XCTest`

- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

1. Added `.Package(url: "https://github.com/Quick/Quick.git", majorVersion: 1, minor: 0),` to `Package.swift`
2. Ran `swift build`
3. Ran `.build/debug/[REDACTED]`, and got error.

### What did you expect to happen?

Running `.build/debug/[REDACTED]` should run without error.

### What actually happened instead?

Attempting to run `.build/debug/[REDACTED]` errored with:
```
dyld: Library not loaded: @rpath/XCTest.framework/Versions/A/XCTest
  Referenced from: /Users/[REDACTED]/Desktop/Programming/Swift/Perfect/[REDACTED]/.build/debug/[REDACTED]
  Reason: image not found
Abort trap: 6
```

### Environment

List the software versions you're using:

 - Quick: *1.x.x* (whatever's the most recent at the time of writing this)
 - Nimble: *?.?.?* (whatever the above version uses)
 - Swift Version: *Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Swift Package Manager *3.0.2 (swiftpm-11750)*

### Project that demonstrates the issue

The project in question is unfortunately closed source and not publicly announced (hence [REDACTED] above), but I can throw something together quickly to demonstrate the issue if you would like.

**Comment by thislooksfun** [comment]
@istx25 I see you've added the "needs-more-information" tag, does that mean you need more information from me, and if so, what?

**Comment by istx25** [comment]
Hi @thislooksfun. Thank you for filing this issue. I'd appreciate it if you would put together another project that demonstrates the issue in isolation. From there, we can investigate further. :)

**Comment by ikesyo** [comment]
You may be seeing https://github.com/Quick/QuickOnLinuxExample but that is outdated and Quick is now integrated with `swift test` command. So you should run `swift test` instead of `swift build` and `.build/debug/[REDACTED]`.

**Comment by ikesyo** [comment]
FYI ReactiveSwift is a working example of Quick with SwiftPM: https://github.com/ReactiveCocoa/ReactiveSwift/tree/master/Tests.

**Comment by thislooksfun** [comment]
I see that, but is there any way to not have to switch out `Package.swift` files? That's the part that's failing. I can make it work, but it's a pain.

**Comment by thislooksfun** [comment]
I'm discussing a new addition to SwiftPM that would fix this issue on the swift-evolution mailing list, subject `[SwiftPM] Proposal: Add support for test-only dependencies`.

**Comment by jeffh** [comment]
Sadly, replacing the `Package.swift` file is currently the only way until SPM supports test-only dependencies.

**Comment by thislooksfun** [comment]
Yeah, I realize that, hence my bringing it up on the mailing list.

**Comment by ikesyo** [comment]
This can be closed now. See #725 and #721 for the details.
