### ISSUE TITLE
#CRASH while running the test target 

### ISSUE THREAD

**Issue by veeraraj** [Quick/Quick#676]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Trying to run test target
### What did you expect to happen?

Tests has to be executed as usual.

### What actually happened instead?

On loading app got crashed without any traces.
### Environment

List the software versions you're using:

 - Quick: *0.9.3*
 - Nimble: *4.1.0*
 - Xcode Version: *8.2.1* & *8.1* 
 - Swift Version: *2.3* 

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.2.0 beta 1* (Use `pod --version` in Terminal)

### Project that demonstrates the issue

![image](https://cloud.githubusercontent.com/assets/3583771/21883118/d233417c-d8ad-11e6-856d-f085f1aad101.png)

11:38:55.075 Xcode[43336:9330261] Clearing timeout timer while paused in the debugger. Timeout conditions may not be detected during this session.
11:40:06.826 Xcode[43336:9330261] Clearing timeout timer while paused in the debugger. Timeout conditions may not be detected during this session.
11:40:16.836 Xcode[43336:9330261] Clearing timeout timer while paused in the debugger. Timeout conditions may not be detected during this session.
11:40:28.250 Xcode[43336:9330261] Test operation failure: Test operation was canceled.
11:40:28.250 Xcode[43336:9330261] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled." UserInfo={NSLocalizedDescription=Test operation was canceled.} didCancel: 1

**Comment by jeffh** [comment]
Hey @veeraraj,

Thanks for filing an issue. I have a couple of questions.

Is there any test code for Quick and Nimble that when you comment out prevents this bug? Also, are you running a specific test or all the tests?

**Comment by veeraraj** [comment]
Hi Jeffh,

    Thanks for getting back. Yes We have a more than 56 test cases in a test target and It was working fine. The crash occurs when trying to execute both a single test case and all the test cases.

**Comment by wongzigii** [comment]
It seems to be something which can be Xcode issue. I saw this several times on TravisCI.
Relate: https://github.com/travis-ci/travis-ci/issues/6422

**Comment by ikesyo** [comment]
This is inactive and looks like this may be unrelated to Quick. Closing.
