### ISSUE TITLE
No carthage support?

### ISSUE THREAD

**Issue by TofPlay** [Quick/Quick#684]
Does Quick support Carthage? I do not see a badge [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage) or an installation section for Carthage in the README.md file

**Comment by morganchen12** [comment]
Quick (and Nimble) both support Carthage. [ReactiveSwift](https://github.com/ReactiveCocoa/ReactiveSwift) is an example of a project that uses Quick through Carthage.

**Comment by TofPlay** [comment]
Ok 🙂 . In this case badge and install section for carthage are just missing on the README.md.

**Comment by jeffh** [comment]
The README links to the [installation](https://github.com/Quick/Quick/blob/master/Documentation/en-us/InstallingQuick.md). Otherwise more than half of the README would be installation instructions. Although it doesn't hurt to add the badge, but we might as well add the cocoa pods badge as well.
