### ISSUE TITLE
No Such Module 'Quick' After Enabling Test Coverage

### ISSUE THREAD

**Issue by heshamsalman** [Quick/Quick#695]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
I enabled test coverage in the testing scheme. 

### What did you expect to happen?
Test coverage to work and Quick to remain functional.

### What actually happened instead?
Quick -- or nimble, whichever is placed first on the import list -- is now showing 'no module found'. The tests still run.

After turning off code coverage, it seems that they're "found" again. 

### Environment

List the software versions you're using:

 - Quick: *1.1.0*
 - Nimble: *6.0.1*
 - Xcode Version: *8.2.1*
 - Swift Version: Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.1.1*

**Comment by alexvbush** [comment]
experiencing the same issue. Quick: 1.1.0, Nimble: 7.0.0, Xcode: 8.3.2, Swift: 3.1
