### ISSUE TITLE
Performace issue with a large number of tests

### ISSUE THREAD

**Issue by dbarden** [Quick/Quick#696]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Created a bunch of tests (approximately 7k) in our application.

### What did you expect to happen?

That the performance of the execution would be stable (in the order of 1ms per simple test).

### What actually happened instead?

The average time to run a simple test got into the 50ms.

### Environment

 - Quick: *1.1.0*

 - Cocoapods: *1.2.0* (Use `pod --version` in Terminal)

### Project that demonstrates the issue

I didn't upload one yet, but I can create if you need it.

### Investigation

After taking a look on the _Example.run()_, on the very end, it's doing [this comparison](https://github.com/Quick/Quick/blob/e4fa1e85c0305ba4e0866f25812d3fa398f3a048/Sources/Quick/Example.swift#L85). The problem is that `world.includedExamples` is a computed property which performs a `.filter` in an array with all the tests. Which is not scaling very well when the number of tests starts grow to thousands :)

I'll send a PR that caches the results of `world.includedExampleCount` and does not calculated it over and over again. Since when the tests are run, the number of tests is already defined, I hope that this is fine.

**Comment by piotr-tobolski** [comment]
I think it should be marked as critical or at least very high and I hope it will be fixed in the next release. Quick performance overhead is currently just insane.
