### ISSUE TITLE
Swift 3 linking error

### ISSUE THREAD

**Issue by JanC** [Quick/Quick#703]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
Hi,
I have an issue when migrating a framework project `MyKit` from Xcode 7.3 to 8.3. Everything compiles fine but I get a linker error (see below) when running the tests.

The setup of my project  is the following
- `MyKit.framework`: an objective c framework target. It does have any Swift legacy or version settings set
- `MyKitTests` which is the test target using Quick

All worked fine in Xcode 7 and I'm trying to migrate the test target to Xcode 8. So I

- Migrate from Xcode 7 to Xcode 8.3
- Updated Quick from `v0.9.3` to `v1.1.0` (carthage update)

I also tried settings explicitly `SWIFT_VERSION = 3.0;` in all my targets but it did not help.

### What actually happened instead?
When I run my tests, I get the error
```
ld: MyKit/Carthage/Build/iOS/Quick.framework/Quick compiled with newer version of Swift language (3.0) than previous files (2.0) for architecture x86_64
```

So this shows that Quick was properly compiled with Swift 3.0 as expected but I'm not sure what the `previous files (2.0)` refer.

### Environment

 - Quick: `v1.1.0`
 - Xcode Version: Xcode 8.3
 - Swift Version: `Xcode Default`
 - Carthage: `0.15.1`

### Project that demonstrates the issue
I was trying to re-create a sample project but all works fine in a new project
- I create a `MyKit.framework` and `MyKitTests` targets using Xcode 7.3 
- Added Quick `v0.9.3` -> the tests run fine in Xcode 7
- Updated  Quick to `v1.1.0` and recompiled with Xcode 8 and tests run fine in Xcode 8

I realise that this is not a purely Quick problem but maybe you can help me with this. Thanks

**Comment by JanC** [comment]
The problem was that another test dependency (`OHHTTPStubs`) was using a binary version so I just recompiled it using `carthage update --platform iOS --no-use-binaries` and all works well now.

cheers and sorry for the noise

**Comment by jeffh** [comment]
Thanks for following up and closing the issue.
