### ISSUE TITLE
Let's delete the Quick/Wiki repository

### ISSUE THREAD

**Issue by istx25** [Quick/Quick#705]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

We originally created the https://github.com/Quick/Wiki repository to hold all of our documentation examples and whatnot but it kind of stagnated in November '16.

I still think it's a good idea but we should take some time to ideate and possibly in a few months get to actually putting a real solution together.

Is that reasonable? @Quick/core

**Comment by modocache** [comment]
+1

**Comment by mokagio** [comment]
😞 that's mainly my fault... I was very pumped at the idea, but ended up not having enough time to dedicate to it.

**Comment by istx25** [comment]
I disagree. I also disappeared for like several months due to personal reasons. So don't feel bad. I'd like to do something similar which we can properly plan out in the coming plans and execute it.

**Comment by wongzigii** [comment]
Or we can use https://github.com/Quick/Quick/wiki  :)

**Comment by istx25** [comment]
That's also a good idea. Though, I'm wondering if we can upload zip files to the Wiki.

**Comment by istx25** [comment]
I'm going to go ahead and delete the Wiki repository and we can continue from there. :D
