### ISSUE TITLE
Hi Xcode Version 8.3.2 (8E2002)

### ISSUE THREAD

**Issue by saroar** [Quick/Quick#706]
is it wokring with Xcode Version 8.3.2 (8E2002)
and swift Apple Swift version 3.1 ?

**Comment by morganchen12** [comment]
Yes.

Are you running into anything unexpected?

**Comment by saroar** [comment]
please check this http://prntscr.com/f1r96b

**Comment by morganchen12** [comment]
How are you installing Quick?

**Comment by mjjimenez** [comment]
I'm running into the same thing with Quick/Nimble. Installing it via Cocoapods.

```
source 'https://github.com/CocoaPods/Specs'

platform :ios, '<%= deployment_target %>'

# Uncomment this line if you use Swift
use_frameworks!

target '<%= project_name %>' do
  # Application Pods
end

abstract_target :unit_tests do
  target '<%= test_target_name %>'
  pod 'Quick'
  pod 'Nimble'
  pod 'SwiftLint'
end
```

**Comment by ikesyo** [comment]
Maybe you should update CocoaPods itself first.

**Comment by mjjimenez** [comment]
Yeah you were right @ikesyo , just updated my cocoapods and it worked fine. This should probably be closed.
