### ISSUE TITLE
Build error when using Quick with Swift Package Manager: Use of '@import' when modules are disabled

### ISSUE THREAD

**Issue by agordeev** [Quick/Quick#707]
- [*] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I'm trying to integrate Quick with my [Vapor](https://github.com/vapor/vapor) 2 project using Swift Package Manager. Here's how my Package.swift looks like:

    let package = Package(
        name: "FreelanceJobs-server",
        targets: [
            Target(name: "App"),
            Target(name: "Run", dependencies: ["App"])
        ],
        dependencies: [
            .Package(url: "https://github.com/vapor/vapor.git", Version(2, 0, 0, prereleaseIdentifiers: ["beta"])),
            // other dependecies go here...
            .Package(url: "https://github.com/Quick/Quick.git", majorVersion: 1)
        ],
        exclude: [
            "Config",
            "Database",
            "Localization",
            "Public",
            "Resources"
        ]
    )

After installing dependencies I can see `QuickSpecBase` and `Quick` in target list, but when I try to build the project, I get this error:

    Use of '@import' when modules are disabled

at `QuickSpecBase.h`

<img width="260" alt="screen shot 2017-05-09 at 6 18 13 pm" src="https://cloud.githubusercontent.com/assets/2883524/25858236/eae45200-34e3-11e7-81fd-905b5f3dc142.png">

I've set `Defines module` build setting for my project to `YES`, but this didn't help.

### Environment

 - Xcode Version: 8.3.2 (8E2002)
 - Swift Version: `Xcode Default`

`$ swift build --version`

Apple Swift Package Manager - Swift 3.1.0 (swiftpm-12084)

**Comment by ikesyo** [comment]
Do you mean that you are using a `xcodeproj` which is generated by `swift package generate-xcodeproj`?

**Comment by ikesyo** [comment]
Just submitted #708 to address this.

**Comment by agordeev** [comment]
>Do you mean that you are using a xcodeproj which is generated by swift package generate-xcodeproj?

Yes.

>Just submitted #708 to address this.

How do I use it? Looks like there's no way to fetch from `master` with Swift Package Manager.

**Comment by ikesyo** [comment]
> How do I use it? Looks like there's no way to fetch from master with Swift Package Manager.

That is not merged into `master` yet. Maybe you can use the branch by something like this:

```
swift package update
swift package edit Quick --branch fix-swiftpm-integration-with-generated-xcode-projects
```

**Comment by agordeev** [comment]
$ swift package edit Quick --branch fix-swiftpm-integration-with-generated-xcode-projects

returns:

    error: branchAlreadyExists

**Comment by ikesyo** [comment]
So how about using `--revision` option instead.

**Comment by agordeev** [comment]
Now I'm getting this:

<img width="258" alt="screen shot 2017-05-10 at 4 36 41 pm" src="https://cloud.githubusercontent.com/assets/2883524/25901257/e8ab0a04-359e-11e7-9e9d-4db8cab4e782.png">

**Comment by ikesyo** [comment]
Quick's SwiftPM support on macOS are not intended to be used with `generate-xcodeproj`. Looks like SwiftPM does not naturally support testing frameworks which links to XCTest for generated Xcode projects.

A possible workaround I found is using the following command when generating a project:

```
swift package -Xlinker -framework -Xlinker XCTest generate-xcodeproj
```

**Comment by agordeev** [comment]
Now I'm getting this:

<img width="335" alt="screen shot 2017-05-11 at 6 51 13 pm" src="https://cloud.githubusercontent.com/assets/2883524/25958936/d8c56e36-367a-11e7-8467-d84243e6d247.png">

and it looks like my project is completely brokes, as Clean and Discard All Changes didn't help :)

**Comment by ikesyo** [comment]
I'm pretty not sure about that unfortunately.

**Comment by ikesyo** [comment]
Anyway I think that would be current limitation of SwiftPM's Xcode project generation (related to testing dependencies those link to XCTest framework). So I recommend you to file an issue on bugs.swift.org or start a discussion on an appropriate Swift mailing list.

**Comment by RahulKatariya** [comment]
This should help I guess

`swift package generate-xcodeproj --xcconfig-overrides settings.xcconfig`

_settings.xcconfig ->_
```
MACOSX_DEPLOYMENT_TARGET = 10.13
CLANG_ENABLE_MODULES = YES;
```

**Comment by coppercash** [comment]
```swift
// settings.xcconfig
OTHER_LDFLAGS = $(inherited) -framework XCTest
```

This works well for me.
