### ISSUE TITLE
Xcode 9 Build Errors

### ISSUE THREAD

**Issue by rehatkathuria** [Quick/Quick#714]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

- Downloaded Xcode 9.0 Beta 2 (9M137d)
- Created a new single view project 
- Added Quick and Nimble to the test target through CocoaPods
- Imported both modules into the test file created by Xcode
- Hit `CMD` + `U`

### What did you expect to happen?

I expected the project to compile without errors.

### What actually happened instead?

Xcode complained about errors.

### Environment

List the software versions you're using:

 - Quick: *1.1.0*
 - Nimble: *7.0.1*
 - Xcode Version: *Xcode 9.0 Beta 2 (9M137d)*
 - Swift Version: *`Xcode Default`*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.2.1* (Use `pod --version` in Terminal)
 - Swift Package Manager *Swift 4.0.0-dev (swiftpm-13081.10)*

### Project that demonstrates the issue

https://github.com/rehatkathuria/foobar

**Comment by rehatkathuria** [comment]
Hello everyone! As someone who used to have a terrible habit of ignoring tests I'd just like to quickly thank everyone who's been involved with this project as it's made me fall in love with testing. I love the cleanliness that Quick brings to my projects and have loved working with it! Thank you to everyone here 🙌✌️

**Comment by ikesyo** [comment]
What happens if you use current `master` branch in you Podfile?

```
pod "Quick", :git => "https://github.com/Quick/Quick", :branch => "master"
```

Locally I can build `Quick.xcworkspace` with Xcode 9 beta 2.

**Comment by rehatkathuria** [comment]
Oh, christ, this is horrendously embarrassing but I think I've overlooked something extremely crucial. The build error that I'm seeing is inside of the `Nimble` module. Closing this issue for now so. Will open up in the more appropriate repo. Silly me.
