### ISSUE TITLE
Don't use _runtime(ObjC)

### ISSUE THREAD

**Issue by kballard** [Quick/Quick#718]
The source of this library uses `#if _runtime(ObjC)` in multiple places. This directive is not intended for use outside of the standard library itself, and is not supported. It should be replaced with a check for Apple's platforms specifically (e.g. `#if os(iOS) || os(OSX) || os(watchOS) || os(tvOS)`).

A user on the #swift-lang IRC channel has reported that `_runtime(ObjC)` doesn't seem to be defined when it should. They said they're trying to use Quick in a Swift 3 project using SPM4.

**Comment by shaps80** [comment]
Those are 2 very different checks. 

`#if os(iOS)` refers to the platform SDK you’re targeting.   
`#if _runtime(ObjC)` refers to the language. 

These are not interchangeable.

**Comment by oleander** [comment]
`#if _runtime(ObjC)` looks to be evaluated to true when on a platform that supports Objective-C.

**Comment by shaps80** [comment]
Interesting. I hadn’t checked but assumed it was specific to usage of the language rather than support for it. If that’s how it’s used throughout then I agree.

**Comment by oleander** [comment]
That's the only common denominator i can find after a few hours of trial and error. Maybe @kballard can shed some more light on the expression.

**Comment by kballard** [comment]
I haven't researched this in detail, but my understanding is `#if _runtime(ObjC)` is true whenever the Swift language integrates with the Obj-C runtime, and that this is true for Apple platforms and false for other platforms. So it's basically equivalent to checking for all of Apple's OS's. Technically, Swift could compile a special version of the stdlib for GNUStep that sets `#if _runtime(ObjC)`, but I'd be kinda surprised if that actually happened, especially because it would probably break horribly as the stdlib makes assumptions about implementation details of Foundation, or of internal SPI calls).

**Comment by ikesyo** [comment]
We already use the os checks in some places, e.g. https://github.com/Quick/Quick/blob/5f0b899/Tests/QuickTests/QuickTestHelpers/XCTestCaseProvider.swift#L33. So this should be the right direction.

**Comment by jeffh** [comment]
I think there was a weird case where macOS Swift (downloaded from swift.org) does not have objc runtime. I haven’t had time to verify if that’s still the case for swift 4.

- Jeff

**Comment by kballard** [comment]
I just tested an older toolchain I downloaded during the 3.0 dev cycle and `_runtime(_ObjC)` is true there.

**Comment by ikesyo** [comment]
https://github.com/Quick/Nimble/issues/447 has been merged.

**Comment by ikesyo** [comment]
#720 has been merged, so let's close this now.
