### ISSUE TITLE
link to setup xcworkspace does not work

### ISSUE THREAD

**Issue by christophsturm** [Quick/Quick#723]
the install docs
https://github.com/Quick/Quick/blob/master/Documentation/en-us/InstallingQuick.md
contain a link how to set up xcodeworkspaces: 
> If you don't already have a .xcworkspace for your project, create one. (Here's how)

and that "here's how" link no longer works and is redirected to the xcode docs index page.

**Comment by ikesyo** [comment]
Thanks for the report! It would be great if you know an alternative documentation link.

**Comment by ikesyo** [comment]
I found that https://help.apple.com/xcode/mac/11.4/#/devf5378fca9 is the current appropriate documentation link.
