### ISSUE TITLE
Cannot build specs on Linux

### ISSUE THREAD

**Issue by itsravenous** [Quick/Quick#725]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Use Quick to test [my Swift project](https://github.com/mwsrp/i3s-classic-swift/tree/use_quick_for_tests) on Linux. Used [the QuickOnLinux example](https://github.com/Quick/QuickOnLinuxExample) as a reference. 

### What did you expect to happen?

To be able to build the project and run tests :)

### What actually happened instead?

```bash
$ swift build
Compile Swift Module 'Spec' (2 sources)
/home/xxxx/dev/critter/swift-i3s/Sources/Spec/main.swift:4:5: error: cannot convert value of type 'Point2dSpec' to expected element type 'QuickSpec.Type'
    Point2dSpec(),
    ^~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
```

Files:
- [The spec](https://github.com/mwsrp/i3s-classic-swift/blob/use_quick_for_tests/Sources/Spec/Point2dSpec.swift) 
- [The struct I'm attempting to test](https://github.com/mwsrp/i3s-classic-swift/blob/use_quick_for_tests/Sources/I3S/point2d.swift)

### Environment

List the software versions you're using:

 - Quick: *1.1.0*
 - Nimble: *5.0.0*
 - Xcode Version: n/a
 - Swift Version: *3.1.1*
Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Swift Package Manager *3.1.0*

### Project that demonstrates the issue

https://github.com/mwsrp/i3s-classic-swift/tree/use_quick_for_tests (note specific branch - master uses XCT)

**Comment by ikesyo** [comment]
Unfortunately the example repository is fairly outdated now. Quick is now integrated with Swift Package Manager's test support: https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#testing.

 So what you should really do is:

- Place test sources into `Tests/FooBarTests` directory as of Swift Package Manager convention
- Place `QCKMain(...)` in `Test/LinuxMain.swift` file

    ```
    import XCTest
    import FooBar
    @testable import FooBarTests
    
    QCKMain([
        FooBarSpec.self // not `FooBarSpec()`
    ])
    ```
- Then you could run the test suites by `swift test` command

See also https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV3.md#test-target-layouts.

**Comment by itsravenous** [comment]
Thanks! I'll try this out :)

**Comment by modocache** [comment]
> Unfortunately the example repository is fairly outdated now.

We should either:

1. Update https://github.com/Quick/QuickOnLinuxExample and build it continuously to make sure it stays up-to-date, or
2. Add the instructions @ikesyo posted above to Quick's documentation.

**Comment by ikesyo** [comment]
Submitted https://github.com/Quick/QuickOnLinuxExample/issues/3.

**Comment by ikesyo** [comment]
Merged https://github.com/Quick/QuickOnLinuxExample/pull/4. Let's close this.
