### ISSUE TITLE
How to test Notifications from NSNotificationCenter

### ISSUE THREAD

**Issue by jkunzelman** [Quick/Quick#727]
Hello,

Not a problem with quick but having trouble figuring out a way to test that a class sends a notification when updates occur. No matter what happens the expect seems to hit the time out on this example.

I've tried a few different options, here's where I"m at now:

```
it("should post DataUpdated notification when asked") {
                        var success = ""
                        subject.shouldPostDataUpdate = true
                        NotificationCenter.default.addObserver(forName: NSNotification.Name(rawValue:"DataUpdated"),
                                                                   object: self,
                                                                   queue: nil,
                                                                   using: {
                                                                        (notification) in
                                                                        success = "notified"
                                                                        })
                        subject.start()
                        expect(success).toEventually(equal("notified"),timeout:4)
}
```
I can run the app outside of tests and my notifications all work fine. 

I've looked into mocking the notification center, but I'm confused why my expect is not getting the change to success = notified.

**Comment by ikesyo** [comment]
> `object: self`

That seems wrong. The parameter is a sender, not a receiver so that may be `object: subject` or `object: nil`. You should also see https://developer.apple.com/documentation/foundation/notificationcenter/1411723-addobserver.

**Comment by jkunzelman** [comment]
That was a good catch, but not the root cause of my issue. Turned out my test was correct and I wasn't setting my NSNotificationCenter dependency property in my initializer.
