### ISSUE TITLE
Xcode 9 beta 4

### ISSUE THREAD

**Issue by kevinfez** [Quick/Quick#729]
- [√] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Created a new project using Xcode 9 beta 4, pod installed Nimble and Quick

### What did you expect to happen?

Expected default (empty) tests to run and pass

### What actually happened instead?

Quick fails to compile, therefore tests fail to build

### Environment

 - Quick: *1.1.0* 
```pod Quick```
 - Nimble: *7.0.1* 
```pod Nimble :git => 'https://github.com/Quick/Nimble.git', :branch => 'xcode9-beta'```
 - Xcode Version: *9.0 beta 4 (9M189t)*
 - Swift Version: *4.0* (swiftlang-900.0.54.11 clang-900.0.31)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.2.0* using Cocopods.app

<img width="1746" alt="screen shot 2017-07-27 at 4 57 34 pm" src="https://user-images.githubusercontent.com/7257376/28697062-48d57cc0-72ee-11e7-8cbb-3480ad93db62.png">
<img width="1746" alt="screen shot 2017-07-27 at 4 57 51 pm" src="https://user-images.githubusercontent.com/7257376/28697064-4cd8abc6-72ee-11e7-8cbc-52208439fc03.png">

**Comment by kevinfez** [comment]
oh and I do have Defines Module set to yes.

<img width="1105" alt="screen shot 2017-07-27 at 5 13 52 pm" src="https://user-images.githubusercontent.com/7257376/28697194-08e6b916-72ef-11e7-9c07-d9e7c500d5d5.png">

**Comment by kevinfez** [comment]
*accidental close*

**Comment by kevinfez** [comment]
related to #717

**Comment by kevinfez** [comment]
<details>
<summary>Idk if any of this is useful... but if you're interested...</summary>

Adding @interfaces for Example and Callsite in the ```Quickspec.m``` file (no idea if I wrote them correctly) and changing the called function in ```XCTestSuite+QuickTestSuiteBuilder.m``` file (not sure if it's the correct function) will enable compiling but results in a run time error (see image 3)

```Quickspec.m``` *added Example and Callsite*
<img width="1103" alt="screen shot 2017-07-27 at 5 47 06 pm" src="https://user-images.githubusercontent.com/7257376/28697900-3cbc8694-72f4-11e7-8bf8-3db7d5cfbd22.png">

```XCTestSuite+QuickTestSuiteBuilder.m``` *changed called function*
<img width="1110" alt="screen shot 2017-07-27 at 5 49 07 pm" src="https://user-images.githubusercontent.com/7257376/28697904-40d78bf2-72f4-11e7-8f13-4062e4803b69.png">

```QuickConfiguration.m``` *runtime error*
<img width="1746" alt="screen shot 2017-07-27 at 5 51 20 pm" src="https://user-images.githubusercontent.com/7257376/28697905-464bcc1a-72f4-11e7-8104-7534d6ab9edf.png">

</details>

**Comment by ikesyo** [comment]
> Quick fails to compile

Current `master` successfully compiles.

**Comment by kevinfez** [comment]
Hmm, I specified the master branch in my podfile just to make sure it was getting it from master and it's still not working on my end. 
I made another clean project, pod installed Nimble and Quick, tried running just the default test and it fails to run. 

*screenshot of error when trying to run the tests*
<img width="1745" alt="screen shot 2017-07-27 at 10 12 56 pm" src="https://user-images.githubusercontent.com/7257376/28703498-4c6fe138-7319-11e7-9657-6fff7b919644.png">

*the zipped project*
[QuickProject.zip](https://github.com/Quick/Quick/files/1182072/QuickProject.zip)

**Comment by ikesyo** [comment]
Hmm so this should be a CocoaPod issue. This project is compatible with Swift 3.2 but not with Swift 4 syntax yet. Please check https://github.com/CocoaPods/CocoaPods/issues/6791 for the details.

**Comment by kevinfez** [comment]
ah I see, for those who also stumble into this issue here's a podfile example with a post_install that can change the swift versions of specified pods

thanks to xmartlabs/Eureka#1096

```
project 'QuickProject.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickProject
  def testing_pods
    pod 'Quick'
    pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'xcode9-beta'
  end

  target 'QuickProjectTests' do
    testing_pods
    # Pods for testing
  end

  target 'QuickProjectUITests' do
    testing_pods
    # Pods for testing
  end
  
  # Manually making Quick compiler version be swift 3.2
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'Quick'
        print "Changing Quick swift version to 3.2\n"
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.2'
        end
      end
    end
  end

end

```

**Comment by ikesyo** [comment]
FYI `3.2` is not a valid value for `SWIFT_VERSION` build setting. You should use `3.0`.

**Comment by kevinfez** [comment]
do you happen to have a source that 3.2 is an invalid setting?

Suppling either ```3.0``` or ```3.2``` in the podfile results in the same thing for me: the swift version for Quick is set to ```Swift 3.2```

*set to* ```3.0```
<img width="817" alt="screen shot 2017-07-28 at 4 46 42 am" src="https://user-images.githubusercontent.com/7257376/28716065-fa330788-734f-11e7-80f1-b022c1fdc17e.png">

*set to* ```3.2```
<img width="1630" alt="screen shot 2017-07-28 at 4 47 47 am" src="https://user-images.githubusercontent.com/7257376/28716066-fc72d7d0-734f-11e7-870e-79ffab83e0f6.png">


I'm not concerned about backwards compatibility with Xcode 8, but maybe someone else will be.

**Comment by ikesyo** [comment]
I didn't know that, thanks for the tip.

**Comment by andrashatvani** [comment]
@ikesyo What is the solution? Can you please add the information to the readme?

**Comment by kevinfez** [comment]
@ikesyo [my comment above](https://github.com/Quick/Quick/issues/729#issuecomment-318574286) would most likely solve your problem since you're using Xcode 9. You need to specify that Quick should be using Swift 3.2 to compile since Xcode 9 only supports 3.2 and 4 but defaults to 4 which Quick does not support.

**Comment by andrashatvani** [comment]
@kevinfez It didn't solve the issue for me. I don't even see references to Quick in the build settings of the Pods project.

**Comment by kevinfez** [comment]
@andersio (sorry realized I tagged the wrong person in my previous comment) 
I downloaded Xcode 9 beta 5, copy and pasted my stuff from above and now I see that Nimble got rid of their Xcode 9 beta branch and merged it into master; However, when I pod installed Nimble *it downloads version 6,* which is very weird since it should be download 7.0.1, but trying to specify >= 7.0.1 will throw an error, so try pointing the pod file at the GitHub directly using this.

```pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'master'```

This successfully downloaded version 7.0.1 for me, and Nimble is now compiling.

**Comment by kevinfez** [comment]
@andrashatvani were you able to resolve your issue?

**Comment by andrashatvani** [comment]
@kevinfez Still no luck, here's my Podfile:

```ruby
platform :ios, '11.0'
use_frameworks!

target 'bcHealth' do
    use_frameworks!

    pod 'Kanna'
    pod 'SwiftLint'

    def testing_pods
        pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'master'
        pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'master'
    end

    target 'bcHealthTests' do
        testing_pods
    end

    target 'bcHealthUITests' do
        testing_pods
    end

    # Manually making Quick compiler version be swift 3.2
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'Quick'
                print "Changing Quick swift version to 3.2\n"
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '3.2'
                end
            end
        end
    end
end
```

**Comment by kevinfez** [comment]
@andrashatvani hm, well that pod file looks fine, I guess I should ask just to make sure, did you follow the set up directions and set the Defines Modules flag on both your project and pods project to "yes"?

<img width="1106" alt="screen shot 2017-08-16 at 12 50 32 am" src="https://user-images.githubusercontent.com/7257376/29353270-836b10ae-821e-11e7-8b8b-5cdd7a3851c2.png">
<img width="1105" alt="screen shot 2017-08-16 at 12 56 15 am" src="https://user-images.githubusercontent.com/7257376/29353271-83796abe-821e-11e7-9fc6-8687a1abc9cb.png">

**Comment by andrashatvani** [comment]
@kevinfez Yes:
<img width="514" alt="screen shot 2017-08-16 at 10 10 39" src="https://user-images.githubusercontent.com/695746/29353672-4ba29528-826b-11e7-8f87-4709c5308c08.png">
<img width="467" alt="screen shot 2017-08-16 at 10 11 01" src="https://user-images.githubusercontent.com/695746/29353676-520c433c-826b-11e7-8a04-ab6d2276c136.png">

**Comment by andrashatvani** [comment]
@kevinfez Also the framework search paths look good:
<img width="1597" alt="screen shot 2017-08-16 at 10 17 57" src="https://user-images.githubusercontent.com/695746/29354011-6cc17bb0-826c-11e7-9bf6-7709bd23a982.png">

What else could it be?

**Comment by kevinfez** [comment]
@andrashatvani my framework search paths are not set to anything
<img width="1110" alt="screen shot 2017-08-16 at 1 35 51 am" src="https://user-images.githubusercontent.com/7257376/29354748-4917c3a2-8223-11e7-95b1-afe10a57e457.png">

also I tried using your pod file and I had to specify kanna's swift 4.0 feature branch
```pod 'Kanna', :git => 'https://github.com/tid-kijyun/Kanna.git', :branch => 'feature/v4.0.0'```

**Comment by andrashatvani** [comment]
@kevinfez Well, embarrassing, but I just had to run the test (Command+U) phase of the project to build the frameworks…

**Comment by AlexKel** [comment]
On Xcode 9 Beta 6 here.

adding 
```ruby
 # Manually making Quick compiler version be swift 3.2
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'Quick' || target.name == 'Nimble'
        print "Changing Quick swift version to 3.2\n"
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.2'
        end
      end
    end
  end
```
as @kevinfez suggested fixed it for me. I've had a to add `Nimble` as well there.

**Comment by Codeglee** [comment]
I updated Defines module in both pods + app settings, ran the tests again and this did the trick.
Intellisense and no more module issues.

Thanks @kevinfez!
