### ISSUE TITLE
Xcode 9 fails to build with error: No known class method for selector 'selectedTestSuiteForTestCaseWithName:'

### ISSUE THREAD

**Issue by danielsaidi** [Quick/Quick#739]
- [X ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Created a new Xcode 9 project, then added a unit test project and added Quick 1.1.0 and Nimble 6.0.0 to it using CocoaPods.

### What did you expect to happen?

I didn't really expect things to work, since Xcode 9 is still in beta, but the Quick and Nimble repos say they should work with Swift 4.

### What actually happened instead?

Quick fails to build `XCTestSuite+QuickTestQuiteBuilder.m` since this fails:

```
+ (nullable instancetype)qck_hooked_testSuiteForTestCaseWithName:(nonnull NSString *)name {
    return [QuickTestSuite selectedTestSuiteForTestCaseWithName:name];
}
```

It fails with the error `No known class method for selector 'selectedTestSuiteForTestCaseWithName:'`.

### Environment

List the software versions you're using:

 - Quick: 1.1.0
 - Nimble: 6.0.0
 - Xcode Version: Version 9.0 beta 6
 - Swift Version: 4

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.2.1

**Comment by ikesyo** [comment]
Hi, this is already addressed in `master`, so please use `master` branch for a while.
