### ISSUE TITLE
Releasing new version

### ISSUE THREAD

**Issue by sunshinejr** [Quick/Quick#747]
Hey guys! So yesterday I've made a [PR](https://github.com/Quick/Quick/pull/746) with fix to SPM. I would love to use version requirement for SPM instead of a commit hash, and since the last release was in February, maybe it's time to do another release? What do you think?

**Comment by ikesyo** [comment]
@Quick/core

I will do a release job if I could get CocoaPods trunk access.

**Comment by ashfurrow** [comment]
Done! Sorry, should've done that with Nimble 😅

**Comment by ikesyo** [comment]
v1.2.0 has been released 🎉 

https://github.com/Quick/Quick/releases/tag/v1.2.0

**Comment by edopelawi** [comment]
Wow. I'll check this out, fingers crossed!
