### ISSUE TITLE
Can't compile Quick 1.1.0 with Xcode 9 (9A235) and Cocoapods

### ISSUE THREAD

**Issue by edopelawi** [Quick/Quick#748]
- [v] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I installed the version 1.1.0 through Cocoapods, and run my updated tests using Xcode 9.

### What did you expect to happen?

My tests to run.

### What actually happened instead?

I got several compile-time issues instead:

```
- QuickSpec.m:100:18: No visible @interface for 'Example' declares the selector 'run'
- QuickSpec.m:105:38: Property 'name' not found on object of type 'Example *'
- QuickSpec.m:131:22: Property 'isSharedExample' not found on object of type 'Example *'
- QuickSpec.m:132:33: Property 'callsite' not found on object of type 'Example *'
- QuickSpec.m:133:35: Property 'callsite' not found on object of type 'Example *'
```
### Environment

List the software versions you're using:

 - Quick: *1.1.0*
 - Nimble: *7.02*
 - Xcode Version: *Version 9.0 (9A235)*
 - Swift Version: *4.0* 
 - Cocoapods: *1.1.1*

### Project that demonstrates the issue

[This project.](https://github.com/edopelawi/QuickNimbleCompileIssue)

Of course, I could make my Podfile refer to the `master` branch... but [my library](https://github.com/edopelawi/CascadingTableDelegate) uses (travis-ci.com)'s free runner, and they can't do that. Even after adding `echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config` before running `pod install` in my .travis.yml script.

Thanks in advance, folks! Stay awesome! :)

**Comment by Blackjacx** [comment]
Same issue in my project:

https://github.com/Blackjacx/SHSearchBar

**Comment by ikesyo** [comment]
Could you please follow #747? Closing.
