### ISSUE TITLE
Compilation Errors with Swift 4 and Xcode 9

### ISSUE THREAD

**Issue by Narsail** [Quick/Quick#749]
### What did you do?

Tried to compile my Project with Swift 4 and Xcode 9.

### What did you expect to happen?

That everything will build successfully.

### What actually happened instead?

Quick and Nimble show strange errors. It is kinda strange because I don't get these errors on a different project.

Errors:
<img width="1440" alt="screen shot 2017-09-29 at 18 47 06" src="https://user-images.githubusercontent.com/7859096/31026406-a013160c-a546-11e7-8bb0-79042a86b3c3.png">
<img width="1440" alt="screen shot 2017-09-29 at 18 48 56" src="https://user-images.githubusercontent.com/7859096/31026480-e0277f94-a546-11e7-88e7-6cc633a971f4.png">

### Environment

List the software versions you're using:

 - Quick: *1.2.0*
 - Nimble: *7.0.2*
 - Xcode Version: Version 9.0 (9A235)
 - Swift Version: `Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.3.1

**Comment by Constantine-Fry** [comment]
Hi, @Narsail. did you resolve the issue?

**Comment by Narsail** [comment]
Nope. And I couldn't find the pattern yet. I some of my frameworks it is occurring, in some it isn't. That is strange.

**Comment by Constantine-Fry** [comment]
I've found the way to solve the problem. The error was due to  `APPLICATION_EXTENSION_API_ONLY` set to `YES` on project level. Once I set this property to `NO` it fixed compilation. Funny enough keeping it on for Targets works without any problem.

**Comment by Narsail** [comment]
Mmh on my first attempt your proposed solution didn't work. Even turning it off on the targets didn't help

**Comment by Constantine-Fry** [comment]
@Narsail, forgot to mention one more step: do `pod install`. It will update the settings for Quick pod and it should work.

**Comment by Narsail** [comment]
@Constantine-Fry Indeed. That worked. Thanks a lot!

**Comment by matadan** [comment]
I have this problem in an otherwise empty project. APPLICATION_EXTENSION_API_ONLY is set to NO but I still get these compiler errors.

**Comment by ikesyo** [comment]
Should be addressed by #791.
