### ISSUE TITLE
Documentation: Error in Swift Code Snipped

### ISSUE THREAD

**Issue by michaelom** [Quick/Quick#753]
The Swift code snipped in https://github.com/Quick/Quick/blob/master/Documentation/en-us/ConfiguringQuick.md#adding-global-beforeeach-and-aftereach-closures does not compile:

```
class FinConfiguration: QuickConfiguration {
  override class func configure(configuration: Configuration) {
...
```
Developers not comfortable with inheriting objective-c classes might not find the solution to be obvious: It should be `_ configuration` instead of `configuration`

```
class FinConfiguration: QuickConfiguration {
  override class func configure(_ configuration: Configuration) {
...
```

**Comment by modocache** [comment]
Nice catch, thanks @michaelom! Could you send a pull request to fix this?
