### ISSUE TITLE
+[Quick.World sharedWorld]: unrecognized selector sent to class

### ISSUE THREAD

**Issue by badrinathvm** [Quick/Quick#756]
- [ Yes  ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Testing a basic test case. The same scenario works well in Xcode 8 and Swift 3.x 

### What did you expect to happen?

Should execute without any exception

### What actually happened instead?

 +[Quick.World sharedWorld]: unrecognized selector sent to class 0x10ef5a400

 Quality[10558:544637] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[Quick.World sharedWorld]: unrecognized selector sent to class 0x10ef5a400'

<img width="1280" alt="screen shot 2017-10-14 at 11 28 30 am" src="https://user-images.githubusercontent.com/1479179/31578344-4a80026a-b0d4-11e7-9b2c-995eab8c2f7b.png">

Code 

<img width="619" alt="screen shot 2017-10-14 at 11 40 19 am" src="https://user-images.githubusercontent.com/1479179/31578357-8a0e80fa-b0d4-11e7-9b95-c8db8aa9012b.png">

Any help would be really appreciated.

### Environment

List the software versions you're using:

 - Quick: 1.1.0
 - Nimble: 7.0.2
 - Xcode Version: Version 9.0 (9A235)
 - Swift Version: Swift 4
 - Cocoapods: 1.2.0.rc.1
 - Swift Package Manager : Apple Swift Package Manager - Swift 4.0.0-dev (swiftpm-13126)

### Project that demonstrates the issue

Project Link : 

(https://github.com/badrinathvm/UnitTests)

Unit Test:

https://github.com/badrinathvm/UnitTests/blob/master/QualityTests/LableSpec.swift

**Comment by ikesyo** [comment]
This is already addressed. Please update to Quick 1.2.0.

**Comment by badrinathvm** [comment]
Let me try

**Comment by ikesyo** [comment]
> pod 'Quick', '1.2.0' should work rt ?

It should.

**Comment by badrinathvm** [comment]
It was showing 
[!] Unable to satisfy the following requirements:

- `Quick (= 1.2.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Quick (= 1.2.0)`.

**Comment by badrinathvm** [comment]
I did a " pod repo update " and able to install the 1.2.0 .

**Comment by ikesyo** [comment]
Just run `pod repo update` then. Updating CocoaPods to 1.3.0 would also be a help.
