### ISSUE TITLE
failed build on Xcode 9

### ISSUE THREAD

**Issue by zkhCreator** [Quick/Quick#757]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
use carthage to add quick to my project.

I clean all the cache, and use `carthage update Quick --platform iOS --no-use-binaries` to create the framework

### What did you expect to happen?
I can run my project success

### What actually happened instead?
Module compiled with Swift 3.1 cannot be imported in Swift 4.0: filePath/Build/iOS/Quick.framework/Modules/Quick.swiftmodule/x86_64.swiftmodule

### Environment
 - Quick: *1.2.0*
 - Nimble: *7.0.2*
 - Xcode Version: * Version 9.0 (9A235)*
 - Swift Version: *Xcode Default* (Maybe Swift 4)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.3.1* (Use `pod --version` in Terminal)
 - Carthage: *0.23.0* (Use `carthage version` in Terminal)
 - Swift Package Manager *3.1.0 (swiftpm-12084)* (Use `swift build --version` in Terminal)

**Comment by zkhCreator** [comment]
Nimble.framework also failed

**Comment by ikesyo** [comment]
I guess you are using Carthage. Could you please make it sure that your commad line tools are pointed to Xcode 9? 

```
xcode-select -print-path
```

**Comment by ikesyo** [comment]
And also your Carthage version is a bit outdated.

**Comment by zkhCreator** [comment]
thanks, I switch my xcode-select to Xcode 8.3.3 somedays ago.And I will update my carthage on time.
