### ISSUE TITLE
Tests don't compile with Apple TV device selected

### ISSUE THREAD

**Issue by igoriols** [Quick/Quick#764]
### What did you do?
I started a tvOS project and used Quick/Nimble for testing. But the test target only works when Apple TV simulator is selected. If I select an Apple TV real device, there are compile errors related with the it clause.

### What did you expect to happen?
The tests should compile normally when I select an Apple TV simulator or real device.

### What actually happened instead?
When a Apple TV real device is selected as device target, the tests doesn't compile. There are compile errors with the `it` clause: "Use of unresolved identifier 'it'"

### Environment

List the software versions you're using:

 - Quick: 1.2.0
 - Nimble: 7.0.2
 - Xcode Version: 9.1 (9B55) 
 - Swift Version: Xcode Default
 - Carthage: 0.27.0

### Project that demonstrates the issue

https://github.com/igoriols/QuickNimbleTest

**Comment by wongzigii** [comment]
Sorry, I don't have a real Apple TV so I can't reproduce this. :(

**Comment by sunshinejr** [comment]
@igoriols what command did you use to install libraries using Carthage? I had this problem when I installed libraries only for iOS, for instance, leaving appleTV behind.

**Comment by igoriols** [comment]
@sunshinejr I used `carthage update --platform tvOS`. I looked inside the framework and I saw that the framework for tvOS was compiled only for x86_64 (used for simulator). Actually, the device works with arm64 architecture. I think that is the problem.

![screen shot 2018-01-04 at 09 18 30](https://user-images.githubusercontent.com/8026597/34563398-3f7f8bae-f131-11e7-87de-f6fd4b8708bd.png)

**Comment by ikesyo** [comment]
Unfortunately this can’t be done. Bitcode is required (non-optional) for `appletvos` SDK (device SDK) but this testing framework depends on XCTest framework which does not contain bitcode. So we can only support `appletvsimulator` SDK.

See also https://github.com/Quick/Quick/pull/524 and https://github.com/Carthage/Carthage/pull/1280 for the details.
