### ISSUE TITLE
Unsupported Swift Version warning

### ISSUE THREAD

**Issue by weitzel926** [Quick/Quick#768]
- [ X] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I am evaluating Quick as a possible solution to BDD testing for an Objective-C project.  I am looking for a framework with long term support but more readability than XCTest, so I prefer BDD.  I created a Objective-C project to do this.  I used CocoaPods to install quick and nimble.  I also intend to use OCMock.

# Podfile
use_frameworks!

platform :ios, '11.2'

def testing_pods
    pod 'Quick'
    pod 'Nimble'
	pod 'OCMock'
end

target 'SFQuickTests' do
    testing_pods
end

### What actually happened instead?

When xcode opens, I get a warning:

![image](https://user-images.githubusercontent.com/3514194/35485964-56b93d5a-0424-11e8-81ed-946fdd2869ab.png)

From other issues in the issue tracker for quick, it appears that the latest Swift should be supported, so I am confused why I'm seeing this.  The project is not a legacy project, it is a new project I setup with XCode 9.2 just for this purpose.

### Environment

List the software versions you're using:

 - Quick: 1.2.0
 - Nimble: 7.0.3
 - Xcode Version: 9.2
 - Swift Version: `Xcode Default`

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.3.1

**Comment by ornithocoder** [comment]
Hello, @weitzel926! I don't know how up-to-date my answer is, but can you try adding the following to your `Podfile`?

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

Regards, Dr. O. ;-) BAM.

**Comment by weitzel926** [comment]
Makes sense, that patched the problem.  Thanks!
