### ISSUE TITLE
How to test is function is called or not?

### ISSUE THREAD

**Issue by eMdOS** [Quick/Quick#773]
Is there any way to test if a function is called?

When using `XCTest` framework directly, this can be tested using **expectations**. 

I have seen some code samples using booleans with an initial value as `false` and the setting them as `true` when calling the related functions but I don't like this approach. 

I wonder if there is an expectation-like option available in `Quick`.

**Comment by shaps80** [comment]
A few months ago `QuickSpec.current` was introduced to expose expectations.

`let expectation = QuickSpec.current.expectation(description: "my function was called")`
`expectation.fulfill()`

When testing a closure, this is fairly simple. However if you need to test a function that is called internally to a class, you can do a couple of things.

1. Subclass and implement the expectation in the mock. This obviously assumes you have a class and its not marked final – less than ideal
2. Use a protocol in your implementation, then write a mock instance that exposes the expectation – **recommended**

**Comment by shaps80** [comment]
Crude Example:

```swift
// protocol definition
protocol NetworkServiceHandling {
    func perform(request: FetchRequest)
}

// concrete instance
final class NetworkService: NetworkServiceHandling { }

// mock instance
final class MockNetworkService: NetworkServiceHandling {
    internal var expectation: XCTestExpectation?

    func perform(request: FetchRequest) {
        expectation?.fulfill()
    }
}
```

**Comment by eMdOS** [comment]
I have read some threads about it, but the thing is that I'm getting the message `Type 'QuickSpec' has no member 'current'` when trying to do it.

I am using carthage and the resolved version is `github "Quick/Quick" "v1.2.0"`.

So, seems like `current` is not part of the Public API of `QuickSpec`.

By the way, I am using Swift.

**Comment by shaps80** [comment]
Ahh... you're right. That API was added in October and the 1.2 release was in September. I'm know with pods you could just point directly to a tag, branch, etc... 

I'm not that familiar with Carthage, but perhaps someone else can help you here.

/cc @ikesyo

**Comment by eMdOS** [comment]
@shaps80 according to the project versioning, the latest released version is the one I am currently using: https://github.com/Quick/Quick/releases/tag/v1.2.0

So, if that API was added in October, why it is not released yet?

Is `master` branch containing that API?

Thanks in advance.

**Comment by shaps80** [comment]
Because no release has occurred since v1.2 AFAIK. It does look like it got merged into develop though. So if you point to develop you should be able to get access to that API. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eMdOS** [comment]
Git it, thanks. I pointed it to `master` and now it is working.
