### ISSUE TITLE
Can't compile because "Nimble/Nimble-Swift.h" can't be found. CocoaPods 1.5 & static

### ISSUE THREAD

**Issue by jmfriend** [Quick/Quick#780]
I've been waiting for cocoaPods 1.5 to come out so I can finally use Quick and Nimble! The reason I couldn't before was that some of the pods I use (hockeyapp and new relic) use static libraries. This meant I could not have use_frameworks! in my Podfile because that led to the transitive_dependencies issue when mixing dynamic and static libraries with Cocoapods. I should perhaps also mention that I have a private pod that integrates with hockeyapp and new relic. I think it's the combination of all those things that leads to the transitive_dependencies issue.

CocoaPods 1.5 http://blog.cocoapods.org/CocoaPods-1.5.0/ now supports Swift Static Libraries. Therefore I thought I'd now be able to use Quick and Nimble.

However, building Quick and Nimble in Cocoapods 1.5 as static libraries seems to cause an error to to occur in Quick that has happened before in Nimble. Essentially there seem to be a private objective-c test file (QCKDSL.m) that references a bridging header (Nimble/Nimble-Swift.h) that does not exist. This is the similar issue that impacted Nimble: https://github.com/Quick/Nimble/pull/283 

To use static libraries, you just remove "use_frameworks!"  from the Podfile, so that's what I did as well as include Quick and Nimble. 

I hoped that my tests would build and I'd be able to start using Quick and Nimble.

What happened instead was a build error: 

Can't compile because "Nimble/Nimble-Swift.h" can't be found. 

### Environment

List the software versions you're using:

 - Quick: 1.2.0
 - Nimble: 7.1.0
 - Xcode Version: 9.2
 - Swift Version: 4.0 

 - Cocoapods: 1.5

### Project that demonstrates the issue

I've not included a project, because my project is large and involved. Also, I'm assuming that any project will have this issue if you try to include it as a static library by removing "use_frameworks!"  from the Podfile. Plus I'm assuming that the solution will be similar to what ever the fix was that resolved what seems a similar issue that occurred with Nimble before.

**Comment by davidahouse** [comment]
FWIW: The related issue on the CocoaPods board: https://github.com/CocoaPods/CocoaPods/issues/7594

Looks like the current suggestion is to change the import statements.

**Comment by jmfriend** [comment]
Great spot! I didn't see that yesterday. So it's a Cocoapods issue, but as you say there is a way of pod authors working around it, by using an import construct like: 

#if __has_include("TestLib-Swift.h")
    #import "TestLib-Swift.h"
#else
    #import <TestLib/TestLib-Swift.h>
#endif

Any chance this might happen?

**Comment by ikesyo** [comment]
Thanks for that info! I will tackle this within a few days.

**Comment by davidahouse** [comment]
@ikesyo I went ahead and created a PR for this issue. Hope that helps.

**Comment by jmfriend** [comment]
Just to be clear, because I'm not sure I was before, the same issue impacts Quick and Nimble. Or, any pod that includes swift and objective-c it would appear.

**Comment by fer662** [comment]
@ikesyo I was attempting this fix for the same problem, and was unable to get it to work. I was using cocoapods 1.5.3, and when I reverted back to 1.5.0 it started working. Is there a new proposed workaround or it just broke?

**Comment by ShoaibPathan** [comment]
Include of a non-modular header inside framework module 'Nimble.Swift': ' i am running with this issue .please help me out to resolve it?
