### ISSUE TITLE
Expecting an assertion, eventually

### ISSUE THREAD

**Issue by nevillco** [Quick/Quick#783]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Wrote the following test suite:

```
func assertNotThree(_ value: Int) {
    assert(value != 3)
}

func asyncAssertNotThree(_ value: Int) {
    DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
        assertNotThree(3)
    }
}

class NimbleExperimentTests: XCTestCase {

    func testAssertion() {
        let expression = { assertNotThree(3) }
        expect(expression: expression).to(throwAssertion())
    }

    func testAssertionAsync() {
        let expression = { asyncAssertNotThree(3) }
        expect(expression: expression).toEventually(throwAssertion())
    }
    
}
```

### What did you expect to happen?

I would expect both tests to pass.

### What actually happened instead?

The assertion inside `func testAssertionAsync()` does not get caught; I get the console message:

> Assertion failed: file /Users/connorneville/Documents/Projects/NimbleExperiment/NimbleExperimentTests/NimbleExperimentTests.swift, line 14

Then, after a short delay, the test suite seems to reboot itself, and I get this console message:

> Restarting after unexpected exit or crash in NimbleExperimentTests/testAssertionAsync(); summary will include totals from previous launches.

After this, the tests complete, and `func testAssertionAsync()` fails, having not caught the assertion.

### Environment

 - Quick: *1.2.0*
 - Nimble: *7.0.3*
 - Xcode Version: *9.2 (9C40b)*
 - Swift Version: *4.0*
 - Cocoapods: *1.5.0*

**Comment by ikesyo** [comment]
Looks like this is not related to Quick, closing.
