### ISSUE TITLE
Feature request: support for Given When Then

### ISSUE THREAD

**Issue by mennolovink** [Quick/Quick#794]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### Request: Support for given when then

So that the following could be done:

```Swift
given("A viewController") {
	
    var sut: ViewController!
	
    beforeEach {
        sut = ViewController()
    }
	
    when("viewDidLoad") {

        beforeEach {
            sut.viewDidLoad()
        }

        then("title is set") {
            expect(sut.title).to(equal("Expected Title"))
        }

        then("backgroundColor is set") {
            expect(sut.view.backgroundColor).to(equal(UIColor.white))
        }
    }
}
```

And would result in:

![Test results](https://raw.githubusercontent.com/mennolovink/QuickGWT/develop/Art/TestResults.png)

### The code needed to do this

Is already available [here](https://github.com/mennolovink/QuickGWT/blob/develop/QuickGWT/Classes/GivenWhenThen.swift)

### Project that demonstrates the issue

The following project shows how this could work
https://github.com/mennolovink/QuickGWT

### Pull request
I'd be happy to create a pull request for this, but would like to know up front if something like this would be considered for merging.

Kind regards, 
Menno Lovink

**Comment by sunshinejr** [comment]
Hey @mennolovink. AFAIK there were multiple discussions about this topic already, and the conclusion was that it probably won't be implemented in the core library, but there is already a library that does just that - adds extensions. See [Brisker](https://github.com/pedrovereza/Brisker) by @pedrovereza.

**Comment by mennolovink** [comment]
Ok, good to know!
