### ISSUE TITLE
Test suite succeeds but only one unit test executed

### ISSUE THREAD

**Issue by bryanboyko** [Quick/Quick#795]
### What did you do?

Refactored a bunch of Swift code to objective c and changed tests folder structure. Then ran tests (%U in .xcworkspace or with CLI).

### What did you expect to happen?

All unit tests should execute.

### What actually happened instead?

Test suite succeeds, but only one test runs. 

The following method is executed on `+initialize` and returns all expected invocations.

```
+ (NSArray *)testInvocations
```

However, the following closure is only executed once for the entire test suite.

```
    IMP implementation = imp_implementationWithBlock(^(QuickSpec *self){
        self.example = example;
        currentSpec = self;
        [example run];
    });
```

Also to note. Individually running test specs from the navigation bar in the left side of XCode will cause all tests within a spec to be run.

### Environment

List the software versions you're using:

  - Quick (1.3.0)
  - Nimble (7.1.1)
 - Xcode Version: 9.2
 - Swift Version: 4.0

 - Cocoapods: 1.5.0

### Project that demonstrates the issue

Our SDK is open source. Feel free to checkout 2.0.1 release on commit `08c64562045a5879d9d8f482e5ecd0100960fc0e` in master branch of repo https://github.com/MAXAds/max-ios-sdk

Clone the repo, pod install, open MAX.xcworkspace, and hit '%U'

**Comment by bryanboyko** [comment]
Update:

In QuickSpec.m, adding the following log to this method `+ (void)initialize`

```
NSLog(@"Calling 'testInvocations' from QuickSpec");
```

and the following line to this method override `+ (NSArray *)testInvocations`

```
NSLog(@"CLASS: %@ \n WITH INVOCATIONS: %@", NSStringFromClass([self class]), invocations);
```

And then hitting '%U' shows some informative logs.

-> It looks as though the correct invocations are returned from `+ (NSArray *)testInvocations` on QuickSpec.m call from '+-(void)initialize` but then when XCTestCase calls `+ (NSArray *)testInvocations` the invocations array is blank.

Blank except for the one unit test that runs

**Comment by ikesyo** [comment]
Looks like that because you have a focused test `fit` here: https://github.com/MAXAds/max-ios-sdk/commit/846f1441a9fc35b47f08fe271af385753a742017#diff-c7d80cd1c28cdfe3099686d02c80b17e. Focused tests means only the tests will be executed.

**Comment by bryanboyko** [comment]
Brilliant!

Thanks!

Must have added the f by accident at some point..
