### ISSUE TITLE
Swift 4.1 on Xcode 10.0 support

### ISSUE THREAD

**Issue by doozMen** [Quick/Quick#799]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

* Updated to Xcode 10.0 beta
* Updated Quick via pod

### What did you expect to happen?

just build

### What actually happened instead?

* I get error: 

```swift
error: Cycle inside Quick; building could produce unreliable results.
Cycle details:
→ Target 'Quick' has link command with output '/Users/doozmen/Documents/dooz/Open/ios-faro/Example/Build/Products/Debug-iphonesimulator/Quick/Quick.framework/Quick'
```

### Environment

Xcode 10.0 build 10L176w
 - Quick: *1.3.0*
 - Nimble: *7.1.2*
 - Xcode Version: *10.0 build 10L176w*
 - Swift Version: *4.1*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.5.0* (Use `pod --version` in Terminal)

### Project that demonstrates the issue
https://github.com/doozMen/ios-faro

**Comment by jalmaas** [comment]
I get this error on "second builds" after changing simulator. Clean build folder resolves it until i change something

**Comment by ikesyo** [comment]
Is this still happening on Xcode 10 GM seed?

**Comment by ikesyo** [comment]
@doozMen Since you are using CocoaPods, `gem update xcodeproj` and rerunning `pod install` would work for you.

https://github.com/CocoaPods/Xcodeproj/blob/master/CHANGELOG.md#160-2018-08-16

> Create new targets with the Xcode 10 default ordering for build phases.
