### ISSUE TITLE
afterSuite blocks do not run if there are excluded tests

### ISSUE THREAD

**Issue by IMNiles** [Quick/Quick#809]
- [x ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

When there are excluded examples (using 'xcontext,' 'xit,' etc), the count of examples used by Example.run() (_world.includedExampleCount_) is incorrect (it's too large), which causes the logic that decides whether to call _world.suiteHooks.executeAfters()_ to fail (because the _numberOfExamplesRun_ count never reaches the _numberOfIncludedExamples_).

The calculation of _numberOfIncludedExamples_ was apparently introduced to correct https://github.com/Quick/Quick/issues/482, because the count was not taking focused tests into account.  This calculation *also* needs to take excluded tests into account or the count will still be wrong.

For example, if you have 100 examples, but 3 of them are excluded with 'xit', the check to run the "afters" will be watching for example # 100, but it only gets to 97, so the afters never run, and the test run ends.

I have a fix for the issue, but haven't had a chance to run all the tests yet.  I'll open a PR when I get a chance to do that.  

### What did you expect to happen?

the afterSuite block to be executed after all the tests ran

### What actually happened instead?

the afterSuite block did not run

### Environment

List the software versions you're using:

 - Quick: 1.2.0 (but the behavior is unchanged in master)
 - Nimble: N/A
 - Xcode Version: 9.3.1 (9E501) 
 - Swift Version: 4.1 

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.5.2

**Comment by revolter** [comment]
Isn't there any workaround to have working `afterSuite`s until this is fixed?
