### ISSUE TITLE
what is the equivalence of xctest class setup and teardown in quick framework?

### ISSUE THREAD

**Issue by simpzan** [Quick/Quick#811]
I want to do setup and teardown before and after some tests, not all. with xctest I can put these tests in a XCTestCase class and do setup and teardown in the setup/teardown class functions.
How to achieve this with Quick? I assume there's something like `beforeGroup/afterGroup`, but I didn't find it. :(

**Comment by ornithocoder** [comment]
You're looking for `beforeEach` and `afterEach` ([docs here](https://github.com/Quick/Quick/blob/master/Documentation/en-us/QuickExamplesAndGroups.md#sharing-setupteardown-code-using-beforeeach-and-aftereach)).

**Comment by simpzan** [comment]
@ornithocoder no, I mean setup/teardown `class function`. they run only once for all test functions in a test case class. `beforeEach/afterEach` can't meet my needs.

**Comment by ikesyo** [comment]
`QuickSpec` itself is still `XCTestCase` subclass so you can override `class func setUp()` and `class func tearDown()`.

**Comment by ikesyo** [comment]
Or you might be interested in #161.
