### ISSUE TITLE
Xcode 10 warning: use 'public' instead of 'open'

### ISSUE THREAD

**Issue by paulz** [Quick/Quick#823]
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

`pod lib lint`

### What did you expect to happen?

no warnings

### What actually happened instead?

```
   - WARN  | xcodebuild:  Quick/Sources/Quick/Behavior.swift:7:21: warning: static declarations are implicitly 'final'; use 'public' instead of 'open'
```

### Environment

List the software versions you're using:

 - Quick: *1.3.2*
 - Nimble: *7.3.1*
 - Xcode Version: *10.0 (10A255)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *4.2* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.5.3* (Use `pod --version` in Terminal)
 - Carthage: *0.31.1* (Use `carthage version` in Terminal)
 - Swift Package Manager *Swift 4.2.0 (swiftpm-14248)* (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

Error reproduced on CI:
https://travis-ci.org/paulz/ImageCoordinateSpace/jobs/440920196#L2939

Sample Project:
```
git clone https://github.com/paulz/ImageCoordinateSpace.git
cd ImageCoordinateSpace
git checkout xcode10
pod lib lint
```
reproduces the issue
```
 -> ImageCoordinateSpace (1.0.7)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
    - NOTE  | [iOS] xcodebuild:  warning: ignoring duplicated output file: '.../Build/Products/Debug-iphonesimulator/ImageCoordinateSpace-Unit-Tests.xctest/Assets.car' (in target 'ImageCoordinateSpace-Unit-Tests')
    - WARN  | xcodebuild:  Quick/Sources/Quick/Behavior.swift:7:21: warning: static declarations are implicitly 'final'; use 'public' instead of 'open'

[!] ImageCoordinateSpace did not pass validation, due to 1 warning (but you can use `--allow-warnings` to ignore it).
You can use the `--no-clean` option to inspect any issue.
```

**Comment by wongzigii** [comment]
Fix in #821 Thanks
