### ISSUE TITLE
Add file template for QuickConfiguration subclass

### ISSUE THREAD

**Issue by modocache** [Quick/Quick#83]
Once shared examples are ported to Objective-C in #80, add a file template for shared example subclasses. Like the spec file template, it should allow users to create a new file using either Swift or Objective-C.

**Comment by mokagio** [comment]
Hello there 👋I'm happy to help with this, expect a PR soon-ish 👍

BTW having the "help wanted" and "easy contribution" is such a great idea to help people get started, well done!
