### ISSUE TITLE
Unable to install via Cocoapods or Source Code

### ISSUE THREAD

**Issue by jeromeDefReputation** [Quick/Quick#835]
* [X] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
Pod installed Quick/Nimble using the installation guide...I also dragged and dropped the Source Framework Code from both projects, no build issues during that process but runtime issues as described in "What actually happened instead."

### What did you expect to happen?
No build issues and to be able to run a test.

### What actually happened instead?
Frameworks not being included in the 'Frameworks' folder and the Pods > Frameworks > iOS path folder and thus not being able to run tests. Running an empty test spits out this error in the log...

"
Showing Recent Messages
TestQuickTwoUITests-Runner.app (20931) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying error: The test runner failed to load the test bundle. Executable cannot be loaded for some other reason, such as a problem with a library it depends on or a code signature/entitlements mismatch.))
"

### Environment
List the software versions you're using:

* Quick: _1.3.2_
* Nimble: _7.3.1_
* Xcode Version: _10.1 (10B61)_ (Open Xcode; In menubar: Xcode > About Xcode)
* Swift Version: _Xcode Default_

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

* Cocoapods: _1.6.0_

### Project that demonstrates the issue
N/A

**Comment by ikesyo** [comment]
Looks like the error message means your project setup is incorrect or insufficient.
