### ISSUE TITLE
Tests should not succeed by default

### ISSUE THREAD

**Issue by alekop** [Quick/Quick#842]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I wrote a test that succeeded without evaluating its expectation. This seems like incorrect behavior to me. If tests can pass without proving anything, then we cannot trust them.

```
func doSomething(completion: @escaping ([Int]?) -> Void) {
    // should call the completion func, but it doesn't -> test should fail
    //completion([1, 2, 3])
}

class MySpec: QuickSpec {
    override func spec() {
        describe("MySpec") {
            it("should do something") {
                doSomething { results in
                    // This should fail because expect is never executed, but it passes
                    // Why is success the default behavior?!
                    expect(results).toNot(beNil())
                }
            }
        }
    }
}
```

### What did you expect to happen?

The test should have failed. If I use waitUntil, the test does fail with a timeout, which is correct - it lets me know something is broken.

### What actually happened instead?

The test passed.

### Environment

List the software versions you're using:

 - Quick: *1.3.4*
 - Nimble: *7.3.3*
 - Xcode Version: *10.1 (10B61)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *4.2* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.5.3* (Use `pod --version` in Terminal)

### Project that demonstrates the issue

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by ikesyo** [comment]
That's because Quick does not know when the asynchronous callback will be called and you don't let Quick wait for the completion. For such async tests, you should use either

1. Nimble's `waitUntil`:
    ```swift
    it("should do something") {
        waitUntil { done in
            doSomething { results in
                expect(results).toNot(beNil())
                done()
            }
        }
    }
    ```
2. or `XCTestExpectation` / `XCTWaiter` API:
   ```swift
    let expectation = QuickSpec.current.expectation(description: "some description")
    doSomething { results in
        expect(results).toNot(beNil())
        expectation.fulfill()
    }
    XCTWaiter().wait(for: [expectation], timeout: 1)
    ```

**Comment by alekop** [comment]
Thanks @ikesyo! I actually tried replacing to with toEventually, but that also passed. It makes sense to me now. It's because Quick doesn't know how many expectations there are in a test, it only evaluates those that run.

**Comment by jonchui** [comment]
I actually just ran into this problem, except i AM using the `waitUntil` and i'm finding Tests succeeded, even though my `done` is not called!?!?

```
context("conversationType == .groupChannel, config.session non-nil") {
                context("error returned from server") {
                    urlSession.persistNextData = mockServerJSONError(errorMessage: "could not delete")
                    
                    it("returns a failure result") {
                        waitUntil { (done) in
                            API.shared.deleteConversationAndChannel(mockGroupConvo,
                                                                    config:glooSessionWithLoggedInUser.config()) { result in
                                                                        print("returned result: \(result)")
                                                                        expect(result.errorOrNil).toNot(beNil())
                                                                        done()
                            }
                        }
                        
                    }
                }
                
            }
```

Am i doing something wrong?

replacing the `waitUntil` with:

```
                        let expectation = QuickSpec.current.expectation(description: "delete API call")

                            API.shared.deleteConversationAndChannel(mockGroupConvo,
                                                                    config:glooSessionWithLoggedInUser.config()) { result in
                                                                        print("returned result: \(result)")
                                                                        expect(result.errorOrNil).toNot(beNil())
                                                                        expectation.fulfill()
                            }

                        XCTWaiter().wait(for: [expectation], timeout: 0.5)
```

works though! And the expectation DOES get hit!
