### ISSUE TITLE
Update the embedded Nimble from 8.0.0 to 8.0.1

### ISSUE THREAD

**Issue by tcherna** [Quick/Quick#845]
Can you update the embedded Nimble from 8.0.0 to 8.0.1 to pick up the contain/beEmpty ambiguity issue that appears fixed?

### What did you do?

Updated Quick to latest version (2.0.0)

### What did you expect to happen?

tests build properly

### What actually happened instead?

tests fail on Set contain.

### Environment

List the software versions you're using:

 - Quick: *2.0.0*
 - Nimble: *8.0.0*
 - Xcode Version: 10.2 (10E125)
 - Swift Version: `Xcode Default`

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

**Comment by ikesyo** [comment]
I assume Nimble is Quick's internal testing dependency so you should be able to use your desired version. Anyway the update should be good and I'll do that.

**Comment by tcherna** [comment]
thanks :)
