### ISSUE TITLE
🤖 QuickBot needs a verified email

### ISSUE THREAD

**Issue by phatblat** [Quick/Quick#849]
@QuickBot was disabled in #848. It is [failing builds](https://travis-ci.org/Quick/Quick/jobs/516624952#L209) due to not having a verified email address.

```
$ bundle exec danger
bundler: failed to load command: danger (/Users/travis/build/Quick/Quick/vendor/bundle/ruby/2.4.0/bin/danger)
Octokit::UnverifiedEmail: POST https://api.github.com/repos/Quick/Quick/issues/848/comments: 403 - At least one email address must be verified to do that. // See: https://help.github.com/articles/adding-an-email-address-to-your-github-account
```

@wongzigii are you the only one who can configure @QuickBot?

**Comment by wongzigii** [comment]
Yes, I am going to take a look at this issue. BTW, I can share this account across our Quick team.

**Comment by phatblat** [comment]
Thanks @wongzigii! What do you think about putting the credentials in a new private Quick repo that only the core team has access to?

**Comment by wongzigii** [comment]
Sure, for some reason, I can't remember the bot account anymore, I am still waiting for GitHub support reply to recover the bot account. Or we can create a new account for this purpose.

**Comment by wongzigii** [comment]
@phatblat Oop, we can't create any private repo. :(  

![image](https://user-images.githubusercontent.com/7384288/56078187-aa8ae980-5e17-11e9-89cf-5b1a3d57d25c.png)

**Comment by wongzigii** [comment]
I've created a private repo in my personal account to store the bot credentials. And I've invited you guys to be the collaborators. cc/@phatblat cc/@ikesyo 
If anyone else wants to access it, just ping me a message.

**Comment by phatblat** [comment]
Awesome! Is @quickbot’s email verified now?

**Comment by wongzigii** [comment]
@phatblat yep，we can re-enable the bot again in travis.yml
