### ISSUE TITLE
Quick crashes after upgrading XCode 10.2

### ISSUE THREAD

**Issue by ivangodfather** [Quick/Quick#853]
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
I have updated to latest version of XCode 10.2 
When i switch back to previous version of XCode it just works.

### What did you expect to happen?

Tests still executing

### What actually happened instead?

UITests thrown an exception when running them. 

<img width="1666" alt="Screenshot 2019-04-10 at 08 37 46" src="https://user-images.githubusercontent.com/1838117/55857168-aa1af600-5b6c-11e9-97d4-7218be678062.png">

<img width="1678" alt="Screenshot 2019-04-10 at 08 37 57" src="https://user-images.githubusercontent.com/1838117/55857373-3e855880-5b6d-11e9-8628-5e6588e01f25.png">

### Environment

List the software versions you're using:

 - Quick: *2.0.0*
 - Nimble: *8.0.1*
 - Xcode Version: *10.2 (10E125)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *XCode Default* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.5.3* (Use `pod --version` in Terminal)

**Comment by gzafra** [comment]
I have been able to replicate the issue in a small project: https://github.com/gzafra/QuickCrashTest

It does happen when subclassing QuickSpec and, weirdly enough, only if using some specific types (in this case a Date within a struct)... 

Using a class instead of a struct gets rid of the issue. Also does commenting out the Date.

**Comment by somedev** [comment]
I also faced with this issue. Any thoughts why it might happen only on  Xcode 10.2 (rather iOS SDK 12.2)?

**Comment by baller784** [comment]
Faced same problem on Xcode 10.2

**Comment by somedev** [comment]
Checked on Xcode 10.2.1 - same problem here

**Comment by baller784** [comment]
Temporary solution. Like @gzafra said: "It does happen when subclassing QuickSpec". In my case it happened, when declaring `Date` types outside of `override func spec()`.

For example:
```swift
class SpendableCollectorSpec: BaseSpec {
    let date = Date()

    override func spec() {
      ...
    }
}
```
Changed into:
```swift
class SpendableCollectorSpec: BaseSpec {
    override func spec() {
        let date = Date()
        ...
    }
}
```
The bug appeared, when `date` was declared outside of `func spec()`.

**Comment by phatblat** [comment]
Crash confirmed. Thanks for the sample project @gzafra! This is certainly a weird case, but I'll look into it.

**Comment by ikesyo** [comment]
I submitted a fix for this: https://github.com/Quick/Quick/pull/873
