### ISSUE TITLE
Update Quick to support Xcode 10.2.1 Swift 5

### ISSUE THREAD

**Issue by Rumiya** [Quick/Quick#880]
- [ ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Converting project syntax to Swift 5.

### What did you expect to happen?

The syntax would update and compile successfully with Swift 5.0.1.

### What actually happened instead?

On code line `import Quick` received an error `Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler`.

### Environment

List the software versions you're using:

 - Quick: *1.3.2*
 - Nimble: *7.3.2*
 - Xcode Version: *10.2.1 (10E1001)*
 - Swift Version: *5.0* 

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Carthage: *0.33.0*
 - Swift Package Manager *4.2.0*

**Comment by ikesyo** [comment]
That's because you don't rebuild the framework with Xcode 10.2.1, you are using the one previously built with Xcode 10.1. So just rebuilding with `carthage build` should work.

**Comment by ikesyo** [comment]
And also you'll need to update Quick 2.x (the latest version is [2.1.0](https://github.com/Quick/Quick/releases/tag/v2.1.0)).

**Comment by Rumiya** [comment]
Thanks, that worked!
