### ISSUE TITLE
Docuementation for data-driven examples

### ISSUE THREAD

**Issue by pobengtsson** [Quick/Quick#890]
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

Hi, thanks for making Quick and Nimble, 

I don't write any swift code in my project without some examples/tests in Quick/Nimble. I feature that I was missing from how I could use e.g. Jasmine or scalatest, was to do data-driven specs.

For a long period I thought it wasn't possible as I couldn't find any examples in the documentation or on the internet. A short while back, I thought I'd give it one more try and if there was something preventing success, file an issue. To my great joy, I found a way that just worked. :)
(I wrote about this on my blog found [here](http://niffic.se/2019/04/data-driven-unit-tests-in-swift-using-quick-nimble/))

_if the maintainers consider this way of writing tests supported over time and versions_, I am willing put together a documentation PR including an example of data-drive tests using Quick for fellow coders' benefit.

What is your view?

### Code example for how to drive tests with data

```
import Quick
import Nimble

func double(_ value : Int) -> Int { return 2*value }

class QuickDataDrivenTests: QuickSpec {
    override func spec() {
        describe("the double function") {
            let specified_examples : [(input: Int, output: Int)] = [
                (input: 0, output: 0),
                (input: 1, output: 2),
                (input: 2, output: 4)
            ]
            specified_examples.forEach { (input: Int, output: Int) in
                context("for input \(input) and output \(output) ") {
                    var for_each_executed_with_input : Int?
                    beforeEach {
                        for_each_executed_with_input = input
                    }
                    it("should execute the beforeEach") {
                        expect(for_each_executed_with_input).toNot(beNil())
                    }
                    it("should execute the before each with each entry") {
                        expect(for_each_executed_with_input).to(equal(input))
                    }
                    it("should double the input for output") {
                        expect(double(input)).to(equal(output))
                    }
                }
            }
        }
    }
}
```
### Versions I tested it on
 - Quick: 2.0
 - Nimble: Nimble 8.0
 - Xcode Version: 10.2.1
 - Swift Version: 4.2 and 5.0

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.5.3

**Comment by revolter** [comment]
Thank you very much for the example!

I changed it a bit to:

```swift
import Quick
import Nimble

func double(_ value : Int) -> Int { return 2*value }

class TestData<T> {

    public let context: String
    public let input: T
    public let output: T
    public let line: UInt

    init(context: String, input: T, output: T, line: UInt = #line) {
        self.input = input
        self.output = output
        self.line = line

        self.context = "for input \(self.input) and output \(self.output)"
    }
}

class QuickDataDrivenTests: QuickSpec {
    override func spec() {
        describe("the double function") {
            let dataSet = [
                TestData<Int>(input: 0, output: 0),
                TestData<Int>(input: 1, output: 2),
                TestData<Int>(input: 2, output: 4)
            ]
            dataSet.forEach { (data) in
                context(data.context) {
                    var for_each_executed_with_input : Int?

                    beforeEach {
                        for_each_executed_with_input = data.input
                    }

                    it("should execute the beforeEach", line: data.line) {
                        expect(for_each_executed_with_input, line: data.line).toNot(beNil())
                    }

                    it("should execute the before each with each entry", line: data.line) {
                        expect(for_each_executed_with_input, line: data.line).to(equal(data.input))
                    }

                    it("should double the input for output", line: data.line) {
                        expect(double(input), line: data.line).to(equal(data.output))
                    }
                }
            }
        }
    }
}
```

This way, when a test fail, Xcode marks with red the line where the test's `TestData` was initialized, instead of marking the same `expect` line for every test data.

**Comment by pobengtsson** [comment]
Line references was a cool addition, that improves the whole thing. 👍

**Comment by randomeizer** [comment]
Thanks for posting about this @pobengtsson. I saw your blog post as well. I've been playing with options for this and had a suggestion for improving it, not sure the best way to actually document it (review this pull request? provide my own?).

Anyway, I found that adding a small function made the whole thing much more readable. Specifically:

```swift
/**
 Used to iterate through a set of given data. This can then be used to provide multiple examples of data.
- Parameter input: The list of data to iterate through.
- Parameter then: The closure to execute each item on.
 */
func given<Input>(_ input: Input..., then: (_: Input) -> Void) {
    for i in input { then(i) }
}
```

It's super simple, but lets you write a test like this:

 ```swift
 given(
     (1, plus: 1, is: 2),
     (1, plus: 2, is: 2),
     (1, plus: 3, is: 4)
 ) { (a, b, result) in
     it("\(a) plus \(b) is \(result)") {
         expect(a + b).to(equal(result))
     }
 }
 ```

In this case, the second item `(1 plus 2)` has an error in the data, and will fail on the `expect` line, since `1 + 2 != 2`.

The error itself won't indicate which line of data failed, but you can tell from the generated `it` test name, since it interpolates the values into the title, which in this case would report that `1_plus_2_is_2()` failed. However, if you want to get more specific, you can use the `#line` feature of Swift to grab the line number, then pass it to `expect` to report the specific line, like so:
 
 ```swift
 given(
     (1, plus: 1, is: 2, line: #line),
     (1, plus: 2, is: 2, line: #line),
     (1, plus: 3, is: 4, line: #line)
 ) { (a, b, result, line: UInt) in
     it("\(a) plus \(b) is \(result)") {
         expect(line: line, a + b).to(equal(result))
     }
 }
 ```
 
This will now highlight the second row of data as failing instead of the `expect` line.

*Note:* It's important to specify `line: UInt` in the input signature, since `UInt` is the type that the `expect` function requires for its `line:` parameter.

I also didn't have any issues with requiring a `context` internal to the call or anything like this.

It would be awesome if `given` was added to Quick. I had a bit of a look at the code to do a pull request, but was unsure if it was simply a matter of adding `given` above to `DSL.swift` or if it would also need to be added to `World+DSL.swift`, etc. I'm only using it in Swift code on macOS, so not sure how much work would be required to add it safely across the board.

**Comment by pobengtsson** [comment]
Nice. It would be nice to have the given function and documentation included in Quick. @ikesyo would such an addition be welcome in Quick?

**Comment by ikesyo** [comment]
I think that doesn't depend on any Quick APIs and can be used for vanilla XCTest as well, so I'm not convinced of adding it to Quick is good. I recommend you to create a separate package for that specific purpose.

**Comment by randomeizer** [comment]
It's literally one function. I get what you're saying, but I think a whole separate package would be overkill.

If it's not something that you're interested in adding to the actual library, then perhaps you can update the documentation to include the suggestion for people interested in using the technique @pobengtsson?

**Comment by pobengtsson** [comment]
OK, added a commit to the PR #940 with additions to the documentation the examples.
@randomeizer I made a really brief addition, take a look and suggest changes you would like.

@ikesyo what changes to the doc-PR #940 would you like to see to consider merging it, if at all?

**Comment by randomeizer** [comment]
I added some comments to the documentation. I'm not sure that any of the `Test` data classes are super useful, with regards to being data-driven tests - each test case will have a different set of input and result values depending on what you're testing, and tuples can do a super clear job of describing themselves, I think.
