### ISSUE TITLE
Trying to run a specific spec does not run any tests

### ISSUE THREAD

**Issue by cooksimo** [Quick/Quick#891]
What did you do?

Running a spec with the play button in Xcode results in no tests being run. I raised this earlier in #889 but it was immediately closed. 

Upon further investigation I've discovered the fix in #873 is causing this issue. Specifically the `defaultTestSuite` is not called when running a specific spec.

What did you expect to happen?

The specific spec to be run

What actually happened instead?

No tests were run

Environment

List the software versions you're using:

Quick: latest from master 32804c3
Nimble: 8.0.1
Xcode Version: 10.2.1 (Open Xcode; In menubar: Xcode > About Xcode)
Swift Version: Xcode Default (Open Xcode Preferences; Components > Toolchains. If none, use Xcode Default.)
Please also mention which package manager you used and its version. Delete the
other package managers in this list:

Cocoapods: 1.6.1

**Comment by ikesyo** [comment]
https://github.com/Quick/Quick/issues/889#issuecomment-491676882

> Hmm, ok, this was working pre-Quick 2.0 and Xcode 10.2

I confirmed the issue, this works on Quick 2.0 and 2.1, but does not work on current `master`.

**Comment by acumenrev** [comment]
Same issue with Xcode 10.2.1 and Swift 5

**Comment by acumenrev** [comment]
After upgrading to Xcode 10.3, this issue is gone.

**Comment by trinhngocthuyen** [comment]
I encountered the same issue with Xcode10.2.1. I try using the fix in https://github.com/Quick/Quick/pull/901 and it works properly
