### ISSUE TITLE
Add Swift 5 to podspec swift versions

### ISSUE THREAD

**Issue by benasher44** [Quick/Quick#895]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

`pod install`

### What did you expect to happen?

Quick builds with Swift 5

### What actually happened instead?

Quick builds with Swift 4.2

### Environment

List the software versions you're using:

 - Quick: *2.1.0*
 - Nimble: *8.0.1*
 - Xcode Version: 10.2.1
 - Swift Version: 5.0.1

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.7.1* (Use `pod --version` in Terminal)

### Project that demonstrates the issue

N/A

I believe Quick was updated to build for Swift 5. It would be great to update the podspec like so: `s.swift_versions = ['4.2', '5.0']` for those of us trying to get fully migrated to Swift 5.

Thanks!

**Comment by freak4pc** [comment]
@ikesyo is there anyone who could assist with this? There's no way to install this as a dependency for Swift 5 projects otherwise.

**Comment by fanticqq** [comment]
It still builds with Swift 4.2
