### ISSUE TITLE
Crash when pod install with Quick and Nimble

### ISSUE THREAD

**Issue by nguyentrai2011** [Quick/Quick#899]
- [ ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

- Create new app in Xcode 
- Init Pod 
- pod install

### What did you expect to happen?

- Can build success

### What actually happened instead?

Crash with this error message below:
`dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftXCTest.dylib
  Reason: image not found`

### Environment

List the software versions you're using:

 - Quick: 8.0.2
 - Nimble: 2.1.0
 - Xcode Version: 10.2.1
 - Swift Version: Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.7.2
 - Swift Package Manager: Swift 5.0.0 (swiftpm-14490.62.2)

### Project that demonstrates the issue

- I just create new project, install pod with Quick and Nimble then run project

**Comment by ikesyo** [comment]
Are you sure that you add the libraries to a test target, not to an application target? The error message says XCTest framework does not exist at runtime so it should mean that you are running an application target but not a test target.

**Comment by nguyentrai2011** [comment]
@ikesyo my fault, I added Quick and Nimble in application target in Podfile.
Thanks,
