### ISSUE TITLE
Cedar to Quick migration

### ISSUE THREAD

**Issue by BaluNaik** [Quick/Quick#900]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
We are using Cedar framework for the test suite and we started the migration from Obj-c to swift.
Now we have the challenge to find some suitable methods and syntax.

### What did you expect to happen?
Required suitable methods and syntax for 
1. `nice_fake_for`
2. `spy_on`
3. `stub_method`

Sample example
```
    beforeEach(^{
        networkAdapter = nice_fake_for(@protocol(SomeNetworkProtocol));
        connector = [SomeConnector instance];
    });
    
    describe(@"performSync", ^{
        it(@"should call networkAdapter", ^{
            spy_on(networkAdapter);
            networkAdapter stub_method(@selector(POSTRequestDataTask:parameters:headers:didSucceed:didFail:));
        });
        context(@"when networkAdapter returns response", ^{
            it(@"should call success block", ^{
                NSDictionary *response = @{};
                networkAdapter stub_method("POSTRequestDataTask:parameters:headers:didSucceed:didFail:").and_do_block(^(NSString *URL, NSDictionary *params, NSDictionary *headers, void (^success)(id response), void (^error)(id response, NSError* error)) {
                    success(response);
                }).return_value();
            });
            
            [connector performSync:@[] didSucceed:^(id response) {
                YES should be_truthy;
            } didFail:^(NSError * _Nullable error) {
                YES should be_falsy;
            }];
        });
```

### What actually happened instead?

Need help on an alternative way to fix this.

### Environment

List the software versions you're using:

 - Quick: *2.1.0*
 - Nimble: *8.0.2*
 - Xcode Version: *10.2.1 (10E1001)*
 - Swift Version: *4.2*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.5.3* 
 - Swift Package Manager *5.0.0 (swiftpm-14490.62.2)*

**Comment by vst-ableton** [comment]
This seems to be related more to the Objective-C -> Swift migration than to Quick. It's not possible to do this kind of runtime _magic_ in Swift.

**Comment by VojtaStavik** [comment]
This seems to be related more to the Objective-C -> Swift migration than to Quick. It's not possible to do this kind of runtime magic in Swift.

**Comment by ikesyo** [comment]
Closing as this is out of scope of Quick.
