### ISSUE TITLE
Function builders and Quick?

### ISSUE THREAD

**Issue by VojtaStavik** [Quick/Quick#908]
Function builders are (most likely) coming to Swift soon: [WIP proposal](https://github.com/apple/swift-evolution/blob/9992cf3c11c2d5e0ea20bee98657d93902d5b174/proposals/XXXX-function-builders.md). They bring a completely new set of possibilities for building custom DSL's.

I think it could be interesting to start thinking whether function builders is something Quick can benefit from.

**Thoughts?**

**Comment by onmyway133** [comment]
@VojtaStavik Hi, I've been exploring with function builder in my Spek library https://github.com/onmyway133/Spek

**Comment by amomchilov** [comment]
Should we reopn this?

Result builders are now implemented (and no-longer underscored), and Spek hasn't been updated.
