### ISSUE TITLE
Object instantiated as a different class on Spec

### ISSUE THREAD

**Issue by ravelantunes** [Quick/Quick#91]
When initializing one of my controllers in a spec, I get the following class _TtC9OiOrlando14NewsController for an object that should be of type NewsController.

The following code works on a regular build, but crashes on the tests due to the incorrect typecasting:
```swift
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let controller: NewsController = storyboard.instantiateViewControllerWithIdentifier("NewsController") as NewsController;
```

If I don't typecast to NewsController, but to UIViewController, it doesn't crash:
```swift
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let controller: UIViewController = storyboard.instantiateViewControllerWithIdentifier("NewsController") as UIViewController;
```

This first test succeeds, and the second fails:
```swift
describe("the news controller after initialized") {
    it("is should be of type UIViewController") {
        expect(controller.isKindOfClass(UIViewController)).to.beTrue()
    }
}

describe("the news controller after initialized") {
   it("is should be of type NewsController") {
      expect(controller.isKindOfClass(NewsController)).to.beTrue()
    }
}
```

The NewsController class is correctly included in the Tests target.

Am I doing something wrong?
Are the objects being wrapped in a different object at runtime?

**Comment by modocache** [comment]
Instructions added in #254. Thanks all!
