### ISSUE TITLE
beforeSuite + sharedExamples + itBehavesLike 

### ISSUE THREAD

**Issue by oneGain** [Quick/Quick#914]
- [ ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

![image](https://user-images.githubusercontent.com/27275119/63328050-ffa8b000-c361-11e9-833d-8dccde65b42f.png)
```
class BaseBehavesLikeSpec: QuickSpec {
    override func spec() {
        beforeSuite {
            sharedExamples("something like") { (sharedExampleContext: @escaping SharedExampleContext) in
                it("makes something") {
                    print(sharedExampleContext())
                    let cont = sharedExampleContext()
                    expect(cont["keywg"]).notTo(beNil())
                }
            }
        }
        
        itBehavesLike("something like") { ["key": "value"] }
    }
}
```

### What did you expect to happen?
I expect expect do well
I want to run the same tests against several different kinds of objects, so I try do that

### What actually happened instead?

but it crash

### Environment

List the software versions you're using:

 - Quick: 2.0.0
 - Nimble: 8.0.1
 - Xcode Version: 10.2.1 (10E1001)
 - Swift Version: `Xcode Default`.

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: 1.7.4

### Project that demonstrates the issue

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by oneGain** [comment]
consle log:
2019-08-20 15:36:52.787098+0800 xctest[77779:1078346] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An exception occurred when building Quick's example groups.
Some possible reasons this might happen include:

- An 'expect(...).to' expectation was evaluated outside of an 'it', 'context', or 'describe' block
- 'sharedExamples' was called twice with the same name
- 'itBehavesLike' was called with a name that is not registered as a shared example

Here's the original exception: 'NSInternalInconsistencyException', reason: 'No shared example named 'something like' has been registered. Registered shared examples: '[]'', userInfo: '(null)''
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f2a76fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010e84bac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f2a7555 +[NSException raise:format:] + 197
	3   Quick                               0x00000001275ff794 __23+[QuickSpec initialize]_block_invoke + 298
	4   Quick                               0x0000000127616689 $s5Quick5WorldC30performWithCurrentExampleGroup_7closureyAA0fG0C_yyXEtF12$sIyB_Ieg_TRIyB_Tf1ncn_nTf4nng_n + 57
	5   Quick                               0x0000000127613ef1 $s5Quick5WorldC30performWithCurrentExampleGroup_7closureyAA0fG0C_yyXEtFTo + 65
	6   Quick                               0x00000001275ff649 +[QuickSpec initialize] + 169
	7   libobjc.A.dylib                     0x000000010e84c698 CALLING_SOME_+initialize_METHOD + 19
	8   libobjc.A.dylib                     0x000000010e84ca2a initializeNonMetaClass + 269
	9   libobjc.A.dylib                     0x000000010e84d54f _ZL24initializeAndMaybeRelockP10objc_classP11objc_objectR8mutex_ttILb0EEb + 144
	10  libobjc.A.dylib                     0x000000010e8533e2 lookUpImpOrForward + 205
	11  libobjc.A.dylib                     0x000000010e8610d4 _objc_msgSend_uncached + 68
	12  XCTest                              0x000000010e6d7e17 +[XCTestSuite testSuiteForTestCaseClass:] + 123
	13  Quick                               0x000000012760db60 $s5Quick0A9TestSuiteC08selectedbC003forB12CaseWithNameACSgSS_tFZTf4xd_n + 416
	14  Quick                               0x000000012760ca5e $s5Quick0A9TestSuiteC08selectedbC003forB12CaseWithNameACSgSS_tFZTo + 46
	15  XCTest                              0x000000010e6da9e9 +[XCTestSuite testClassSuitesForTestIdentifiers:skippingTestIdentifiers:testExecutionOrdering:] + 479
	16  XCTest                              0x000000010e6da184 -[XCTestSuite _initWithTestConfiguration:] + 1347
	17  XCTest                              0x000000010e6da7ee +[XCTestSuite testSuiteForTestConfiguration:] + 69
	18  XCTest                              0x000000010e75093b __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 96
	19  XCTest                              0x000000010e750a57 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.80 + 68
	20  XCTest                              0x000000010e6f0474 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 588
	21  XCTest                              0x000000010e75073d -[XCTTestRunSession runTestsAndReturnError:] + 623
	22  XCTest                              0x000000010e6bd41c -[XCTestDriver runTestsAndReturnError:] + 446
	23  XCTest                              0x000000010e74256f _XCTestMain + 2333
	24  xctest                              0x000000010ddc0cb9 main + 263
	25  libdyld.dylib                       0x0000000111433541 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ikesyo** [comment]
Please see https://github.com/Quick/Quick/blob/master/Documentation/en-us/SharedExamples.md for how to use shared examples.

**Comment by oneGain** [comment]
Thanks,
