### ISSUE TITLE
Cannot find Quick/Quick-Swift.h ?

### ISSUE THREAD

**Issue by heefan** [Quick/Quick#923]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?
I just add the followings lines into my project's testing target, 

```
target 'TestTarget' do
    project 'TestTarget/TestTarget.xcodeproj'
    use_frameworks!
    inherit! :search_paths 

    pod 'Quick'
    pod 'Nimble'
end
```

### What did you expect to happen?
Pass the compilation. 

### What actually happened instead?
It shows the following error, 
```swift
#if __has_include("Quick-Swift.h")
#import "Quick-Swift.h"
#else
#import <Quick/Quick-Swift.h>
#endif
```

Cannot find `Quick/Quick-Swift.h`

### Environment

List the software versions you're using:

 - Quick: *2.2.0*
 - Nimble: *8.0.4*
 - Xcode Version: *10.2.1 (10E1001)* 
 - Swift Version: *5.0* 

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.7..5*

**Comment by wangdu1005** [comment]
I have the same issue. Does anyone  can help us? I create a new project and install quick and nimble by Carthage, which it work fine. But I have to use cocoapods install it on company project. So help!! thanks you

**Comment by ikesyo** [comment]
Could you try with `:modular_headers => true`?

```ruby
pod 'Quick', :modular_headers => true
```

If that works, I'll consider adding `'DEFINES_MODULE' => 'YES'` to the podspec's `pod_target_xcconfig`.

ref: http://blog.cocoapods.org/CocoaPods-1.5.0/#modular-headers
