### ISSUE TITLE
QuickSpec's name always return null

### ISSUE THREAD

**Issue by retsohuang** [Quick/Quick#925]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Using QuickSpec to test RealmSwift code and setup like below

```swift
class OrderSpec: QuickSpec {
  override func spec() {
    describe("an order") {
      beforeEach {
        Realm.Configuration.defaultConfiguration.inMemoryIdentifier = self.name
      }
    }
  }
}
```

### What did you expect to happen?

test success

### What actually happened instead?

test failed because of the `self.name` always return `-[OrderSpec (null)]` that cause the in-memory Realm's data will not be cleaned up at each test run. 

### Environment

List the software versions you're using:

 - Quick: 8.0.4
 - Nimble: 2.2.0
 - Xcode Version: Version 10.3 (10G8)
 - Swift Version: 5.0

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: v1.8.0

**Comment by ikesyo** [comment]
You could/should use `QuickSpec.current.name` over `self.name`.
