### ISSUE TITLE
What about Quick purely on Swift ?

### ISSUE THREAD

**Issue by yuriy-yarosh** [Quick/Quick#926]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Tried to build Quick using bazel.

### What did you expect to happen?

For it to build, of course.

### What actually happened instead?

It failed similarly to #923 due to a circular dependency between existing swift and objc code.

Bazel / Buck / Pants have no means to process a mix of swift & objc sources afaik... and it's actually contradicts with those build systems design.

### Environment

 - Quick: 2.2.0
 - Nimble: irrelevant
 - Xcode Version: 11.1
 - Swift Version: 5.1

So, my idea was something like "Why not get rid of the existing ObjC code ?".
ObjC runtime can be accessed directly from swift nowadays.

I'll add some Bazel support too...

**Comment by ikesyo** [comment]
> So, my idea was something like "Why not get rid of the existing ObjC code ?".
ObjC runtime can be accessed directly from swift nowadays.

Classes defined in Swift can't be subclassed from Objective-C. That is because `QuickSpec` is defined in Objective-C.

**Comment by yuriy-yarosh** [comment]
@ikesyo yup, that makes sense, so there should be some additional refactoring involved to decouple the World, Config objects and the TestSuiteBuilder... maybe adding an additional wrapper or a mirroring class.

**Comment by ManWithBear** [comment]
Main problem is `NSInvocation` not available in Swift. And only way to add tests in runtime by overriding `+ (NSArray<NSInvocation *> *)testInvocations` method on `XCTestCase`.

Here I'm showing how to achieve runtime test generation (what Quick doing) in Swift.
https://stackoverflow.com/a/55204082/4280337
So even if you rewrite all Quick parts to Swift, here will be at least 1 dealing with `NSInvocation`

**Comment by yuriy-yarosh** [comment]
@ManWithBear yup, I get that.
My point is that it's worth decoupling existing Swift code from objc i.e. World Object so there would be no circular dependency - it would allow compiling Quick on Bazel.

**Comment by ikesyo** [comment]
Please refer to these:
- https://github.com/bazelbuild/rules_apple/issues/179
- https://github.com/line/rules_apple_line/blob/master/docs/README.md#mixed_static_framework
