### ISSUE TITLE
Xcode 11.2 hangs for toEventually

### ISSUE THREAD

**Issue by danielsaidi** [Quick/Quick#932]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I upgraded to Xcode 11.2 and ran our test suite.

### What did you expect to happen?

The test suite should successfully complete with no test errors.

### What actually happened instead?

The test suite hangs on the first `toEventually` it encounters. 

The same code still works in Xcode 11.1.

### Environment

List the software versions you're using:

 - Quick: 2.2.0
 - Nimble: 8.0.2
 - Xcode Version: Version 11.2 (11B52)
 - Swift Version: Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: -
 - Carthage: -
 - Swift Package Manager: Apple Swift Package Manager - Swift 5.1.0 (swiftpm-15502)

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by tomquist** [comment]
I stumbled over the same problem. Seems to be related to SPM. When I enable optimizations (e.g. run tests in Release configuration) it works again. To me it seems to be some kind of a compiler bug. But this is actually a Nimble issue so I'll open an issue there.

**Comment by danielsaidi** [comment]
Oh, that’s embarrassing...I actually double-checked that it was a Nimble issue, but still managed to report incorrectly :/

Anyhow, great find! I’ll try it when I get to work. Do you want me to close this issue or should I leave it open until the Nimble issue is fixed?

**Comment by tomquist** [comment]
I created a Nimble issue here https://github.com/Quick/Nimble/issues/708
