### ISSUE TITLE
QuickSpec does not record assertions on current spec.

### ISSUE THREAD

**Issue by nikita-leonov** [Quick/Quick#939]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

We noticed that xcpretty was not capturing results of QuickSpec expectations for our XCUITests. It was reporting tests failed in spec summary, but not for individual tests. Further comparison of logs with XCTest with QuickSpec showed that lines like "Assertion Failure: SomeSpec.swift:64: expected to ..."  were missing from output.

### What did you expect to happen?

We expected this lines to be in the spec.

### What actually happened instead?

No assertions in log.

### Environment

List the software versions you're using:

 - Quick: 2.2.0
 - Nimble: 8.0.4
 - Xcode Version: 10.3 / 11.2.1
 - Swift Version: 5.0 / ...

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Carthage: 0.33.0

### Project that demonstrates the issue

None.

### Notes & Fix
What we actually found that `recordFailure` method was executed not on a current spec. Following fix did help to get assertions in log:
```
extension QuickSpec {
    open override func recordFailure(withDescription description: String, inFile filePath: String, atLine lineNumber: Int, expected: Bool) {
        if self != QuickSpec.current {
            QuickSpec.current.recordFailure(withDescription: description, inFile: filePath, atLine: lineNumber, expected: expected)
        } else {
            super.recordFailure(withDescription: description, inFile: filePath, atLine: lineNumber, expected: expected)
        }
    }
}
```

Is it something that other users seeing? Should we contribute this into Quick?

**Comment by nikita-leonov** [comment]
I believe these issues are related to the fix above: 
- https://github.com/Quick/Nimble/issues/379
- https://github.com/xcpretty/xcpretty/issues/322

**Comment by ikesyo** [comment]
Is this related to #888?
