### ISSUE TITLE
[documentation] iOS 13 no longer seems to trigger viewDidAppear when calling endAppearanceTransition in unit tests

### ISSUE THREAD

**Issue by nickm01** [Quick/Quick#941]
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

In Xcode 10.2.1 (iOS 12.4), in order to trigger `viewDidAppear` logic did the following:

```
    let viewController = ViewController()
    let _ = viewController.view
    let window = UIWindow(frame: UIScreen.main.bounds)
    window.layer.speed = 10
    viewController.modalPresentationStyle = .fullScreen
    viewController.beginAppearanceTransition(true, animated: false)
    window.rootViewController = viewController
    window.makeKeyAndVisible()
    viewController.endAppearanceTransition()
...
    expect(viewController.viewDidAppearCalled).to(equal(true))
```

### What did you expect to happen ?

It should pass

### What actually happened instead?

In Xcode 11.3 / iOS 12 or Xcode 10 / iOS 12 the above test passes, in Xcode 11.3/ iOS 13 it does not.

### Environment

List the software versions you're using:

 - Quick: *2.2.0*
 - Nimble: *8.0.4*
 - Xcode Version: *13.3 (11C29)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *5.1* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - CocoaPods: *1.6.1* (Use `pod --version` in Terminal)

### Project that demonstrates the issue

See the only test in the project.
https://github.com/nickm01/Test13ViewWillAppear

**Comment by ikesyo** [comment]
This is not related to Quick itself, closing.

**Comment by nickm01** [comment]
@ikesyo respectfully disagree.  Documentation https://github.com/Quick/Quick/blob/master/Documentation/en-us/TestingApps.md indicates this should work.

**Comment by ikesyo** [comment]
Does that only happen on Quick and not on normal XCTest?

**Comment by nickm01** [comment]
@ikesyo this happens with XCTest too so not directly related to quick.  My point is the documentation needs updating.

**Comment by ikesyo** [comment]
Okay now I understand that you are referring to documentation.
