### ISSUE TITLE
tvOS framework not generated supporting device specific files

### ISSUE THREAD

**Issue by gangadharbonda** [Quick/Quick#943]
- [ ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I tried to generate the tvOS framework by using "Carthage update --platform tvOS" but it did not generate arm64 modules 

**Error populated is :**
 Could not find module 'Quick' for target 'arm64-apple-tvos'; found: x86_64-apple-tvos-simulator, x86_64

### What did you expect to happen?

I want the Quick framework to be generated along with arm 64 files

### What actually happened instead?
It generated **Quick or Nimble** framework on using Carthage only the simulator files 

Please replace this with what happened instead.

### Environment

List the software versions you're using:

 - Quick: 2.2.0
 - Nimble: 8.0.4
 - Xcode Version: 11.3.1
 - Swift Version: XCode default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Carthage: 0.34.0

[Archive.zip](https://github.com/Quick/Quick/files/4063740/Archive.zip)

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by gangadharbonda** [comment]
Want to check if we have any luck on fixing this

**Comment by ikesyo** [comment]
Unfortunately this can't be achievable. See the followings for the details:

- https://github.com/Quick/Quick/issues/764#issuecomment-379831690
- https://github.com/Quick/Quick/pull/524
- https://github.com/Carthage/Carthage/pull/1280
