### ISSUE TITLE
Initializing local variables in beforeEach produces "Variable captured by a closure before being initialized"

### ISSUE THREAD

**Issue by dmoles** [Quick/Quick#958]
- [✓ ] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Given the following spec:

```swift
    override func spec() {
        describe("BlockingStore") {
            
            var store: BlockingStore<Int, IntAction>
            var states: [Int?]
            var listener: Listener<Int>

            beforeEach {
                store = BlockingStore<Int, IntAction>(self.reducer)
                listener = { (_ s: Int?) in states.append(s) }
            }
            
            describe("dispatch") {
                it("dispatches an action") {
                    let unsubscribe = store.subscribe(listener) // nil
                    store.dispatch(IntAction.increment) // 1
                    store.dispatch(IntAction.null) // 1
                    store.dispatch(IntAction.decrement) // 0
                    expect(states).to(equal([nil, 1, 1, 0]))
                    unsubscribe()
                }
            }
        }
    }
```

### What did you expect to happen?

I expected the code to compile.

### What actually happened instead?

References to `store`, `states`, and `listener`, both in `beforeEach {}` and in `it("dispatches an action") {}`, produce the error:

> Variable `<name>` captured by a closure before being initialized.

### Notes

I'm pretty new to Swift but I think I basically understand from analogous situations in other languages what the compiler is trying to tell me: when I write `store =` in the `beforeEach` block, it's trying to capture the current _value_ of the `store` variable, which doesn't exist because it hasn't been initialized.

If this was Java, the problem would be that "closures" (functions, anonymous classes) can only capture final or effectively final variables, i.e. capture them by value, and I'd need to wrap them in some reference type. If it was Go, the problem would be that I was declaring those variables as values rather than pointers.

What's the trick to get the Swift compiler to treat these as references rather than values?

### Environment

List the software versions you're using:

 - Quick: 2.2.0
 - Nimble: 8.0.7
 - Xcode Version: 11.4 (11E146)
 - Swift Version: 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
 - Swift Package Manager 5.2.0

**Comment by dmoles** [comment]
OK, figured it out after looking more closely at the [`beforeEach` docs](https://github.com/Quick/Quick/blob/master/Documentation/en-us/QuickExamplesAndGroups.md#sharing-setupteardown-code-using-beforeeach-and-aftereach): declaring the variables as implicitly unwrapped optionals with `!`:

```swift
            var store: BlockingStore<Int, IntAction>!
            var states: [Int?]!
            var listener: Listener<Int>!
```

(This also surfaced that I'd forgot to initialize `states` in my `beforeEach`, though it took me a little while to realize that was the reason I was getting `Unexpectedly found nil while implicitly unwrapping an Optional value` in `states.append(s)`, and it didn't have anything to do with `s` itself.)

I can see why this works -- `store` is no longer a `BlockingStore`, it's an `Optional<BlockingStore>` -- so it's effectively "wrapping them in some reference type" as I discussed for Java. But is it considered good Swift style?

**Comment by ikesyo** [comment]
Generally speaking using IUO ( implicitly unwrapped optional) is not a good style. But for this usecase, IUO is required for lazy initialization purpose. `lateinit` in Kotlin is similar to the usecase.

**Comment by ikesyo** [comment]
See also: https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html#ID334
