### ISSUE TITLE
Swift 5.1.3 toolchain generates a Swift Interface that's incompatible with Swift 5.2

### ISSUE THREAD

**Issue by devioustree** [Quick/Quick#961]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Module stability was enabled in #957. I tried building Quick with Carthage using Swift 5.1.3 and then linking it to a test target compiled with Swift 5.2.

### What did you expect to happen?

I expected the test target to compile and link successfully.

### What actually happened instead?

The generated `.swiftinterface` seems to be incompatible between these Swift versions.

```
/Build/iOS/Quick.framework/Modules/Quick.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:94:33: error: initializer does not override a designated initializer from its superclass
  @objc override dynamic public init(name: Swift.String)
        ~~~~~~~~                ^
/Build/iOS/Quick.framework/Modules/Quick.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:92:44: error: 'XCTestSuite' is not a member type of 'XCTest'
@objc public class QuickTestSuite : XCTest.XCTestSuite {
                                    ~~~~~~ ^
XCTest.XCTest:1:12: note: 'XCTest' declared here
open class XCTest : NSObject {
           ^
FooTest.swift:10:8: error: failed to load module 'Quick'
import Quick
```

### Notes

Rebuilding Quick in Swift 5.2 means it will successfully link. The generated `.swiftmodule` has a number of changes. However, it is incompatible with Swift 5.1.3.

### Environment

List the software versions you're using:

 - Quick: *master*
 - Nimble: N/A
 - Xcode Version: *11.3.1* and *11.4* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *5.1.3* and *5.2*

 - Carthage: *0.34.0*

**Comment by ikesyo** [comment]
Quick v3 drops support for Swift 5.1 and before, so closing.
