### ISSUE TITLE
Missing Compatibility Check on Xcode 12

### ISSUE THREAD

**Issue by Sherlouk** [Quick/Quick#995]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I'm using Quick in a Swift Package and when using Quick v3.0.0 I'm getting the following error:

> Quick/QuickSpec.swift:142:15: 'recordFailure(withDescription:inFile:atLine:expected:)' is only available in macOS 10.13 or newer

This corresponds to this block of code [here](https://github.com/Quick/Quick/blob/master/Sources/Quick/QuickSpec.swift#L142-L147) which was recently changed under #990!

Reverting back to v2.2.1 does fix the problem.

The package description has products set to an array solely containing `.macOS(.v10_15)` and is being built against my current Mac running v10.15.4 (Catalina).

![Captured 2020-07-05 at 13 56 28](https://user-images.githubusercontent.com/15193942/86533210-590cc580-bec7-11ea-9777-0c2eeb0f9254.png)

### Environment

List the software versions you're using:

 - Quick: *3.0.0*
 - Nimble: *8.1.1*
 - Xcode Version: *v12 Beta 1 (12A6159)*
 - Swift Version: *5.3.0*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Swift Package Manager *Swift 5.3.0* (Swift Build Tools also 5.3)

### Project that demonstrates the issue

https://github.com/Sherlouk/SPM-Demo-QuickRegressionCompat

Just open `Package.swift` and build the default scheme against the "My Mac" device.

cc: @ikesyo

**Comment by smoothdvd** [comment]
Same here.

**Comment by ikesyo** [comment]
Actually this is not a regression in Quick, this is due to a breaking change in Xcode 12 (I'm not sure if it is intentional or not).

**Comment by Sherlouk** [comment]
@ikesyo Not a problem if you wish to declassify it a regression - only reason I did so was because Quick does work on Xcode 12, if you drop back one version of the library. 

It's only the latest version of Quick which is actually broken!

**Comment by ikesyo** [comment]
Actually Xcode 12 broke Quick v3 (that works successfully Xcode 11.4 to Xcode 11.7) 🙃

**Comment by ikesyo** [comment]
Looks like this is not an issue anymore at least on Xcode 12.0 beta 6. ☺️
