### ISSUE TITLE
Compile error with the SwiftPM-generated Xcode project on v3.0.0

### ISSUE THREAD

**Issue by samisuteria** [Quick/Quick#997]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Add Quick to SPM Package.swift as a dependency and try to run tests.

### What did you expect to happen?

Test target would compile and run. 

### What actually happened instead?

Test target failed to compile. Got the following error: 

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_XCTestCase", referenced from:
      _OBJC_CLASS_$__QuickSpecBase in QuickSpecBase.o
  "_OBJC_METACLASS_$_XCTestCase", referenced from:
      _OBJC_METACLASS_$__QuickSpecBase in QuickSpecBase.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Environment

List the software versions you're using:

 - Quick: 3.0.0
 - Xcode Version: 11.5
 - Swift Version: Xcode Default

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Swift Package Manager: 5.2.0

### Project that demonstrates the issue

Just ran `swift package init` and added Quick as a dependency to the package and test target. 

```
// swift-tools-version:5.2
import PackageDescription

let package = Package(
    name: "DemoSPM",
    products: [
        .library(name: "DemoSPM", targets: ["DemoSPM"]),
    ],
    dependencies: [
        .package(url: "https://github.com/Quick/Quick", from: "3.0.0"),
    ],
    targets: [
        .target(name: "DemoSPM", dependencies: []),
        .testTarget(name: "DemoSPMTests", dependencies: [
            .target(name: "DemoSPM"),
            .product(name: "Quick", package: "Quick"),
        ]),
    ]
)
```

**Comment by smoothdvd** [comment]
Same on Xcode 12 Beta 5 and macOS Big Sur 11 Beta 5.

**Comment by freak4pc** [comment]
Having the same issue, thanks for the `CLANG_ENABLE_MODULES` note @chipp!

**Comment by freak4pc** [comment]
And same on Xcode 11.6, by the way

**Comment by ikesyo** [comment]
> Just ran `swift package init` and added Quick as a dependency to the package and test target.

I tried that but couldn't reproduce, `swift test` ran successfully. 🤔

**Comment by chipp** [comment]
> I tried that using Xcode 11.7 but couldn't reproduce, `swift test` ran successfully. 🤔 

you need to generate Xcode project first `swift package generate-xcodeproj` and then run tests in Xcode

**Comment by ikesyo** [comment]
https://github.com/Quick/Quick/issues/997#issuecomment-678449200

@chipp Hmm so are the issue you are hitting and the originally reported issue different? The original description in https://github.com/Quick/Quick/issues/997#issue-661020910 doesn't say anything about `swift package generate-xcodeproj`. I'm confused 😕

**Comment by ikesyo** [comment]
Xcode 11.0 or later can directly open a Swift Package (`Package.swift`) so I think you normally don't need to generate an xcodeproj by `swift package generate-xcodeproj`.

**Comment by freak4pc** [comment]
The automatically synthesized project is usually not too useful for people who have custom build settings etc. so many people would generate the project and add it to their VCS. 

There are also people who have mixed projects (SPM & other dependency managers) due to some of SPM's constraints.

**Comment by ikesyo** [comment]
ref #984

**Comment by ikesyo** [comment]
Could you try #1023?

**Comment by stefanrenne** [comment]
Just tested this using 
```.package(name: "Quick", url: "https://github.com/Quick/Quick.git", .branch("quickobjcruntime-umbrella-header"))```
I can confirm that this solves the issue.
