### ISSUE TITLE
Crash on enumerateSubclasses

### ISSUE THREAD

**Issue by venice81** [Quick/Quick#999]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Quick/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

just starting tests

### What did you expect to happen?

crash on enumerateSubclasses method

### What actually happened instead?

I'm using FBAudienceNetwork.
The exception is "FBNativeAdDataModel is a final class and cannot be subclassed. FBNativeAdDataModel"

### Environment

List the software versions you're using:

 - Quick: 3.0.0
 - Nimble: 8.1.1.
 - Xcode Version: 11.6
 - Swift Version: Xcode Default
 - CocoaPods: 1.9.3

### Project that demonstrates the issue

<img width="1366" alt="스크린샷 2020-07-23 10 34 27" src="https://user-images.githubusercontent.com/299458/88245158-0a399b00-ccd1-11ea-9c98-721a29f5a45b.png">

**Comment by virgilius-santos** [comment]
Hi, this error occurs when I execute tests with iOS 10.3.1, the same test with iOS 11.3 or 13.5 doesn't fail

Environment
List the software versions you're using:

Quick: 3.0.0
Nimble: 8.1.1.
Xcode Version: 11.6
Swift Version: 5
CocoaPods: 1.9.3
Simulator: iPhone SE (1st generation), iOS 10.3.1

**Comment by marte5** [comment]
Wie lange würdet Ihr denn noch mit dem Hauskaufen warten? Werden die Preise noch weiter steigen?  [https://www.ivd24immobilien.de/haus-kaufen/](url)

**Comment by lordzsolt** [comment]
I've started getting these random crash as well. And it's happening super randomly.

**Comment by ikesyo** [comment]
> I'm using FBAudienceNetwork.
The exception is "FBNativeAdDataModel is a final class and cannot be subclassed. FBNativeAdDataModel"

Looks like that is due to how you setup FBAudienceNetwork: https://developers.facebook.com/support/bugs/147221075773612/

**Comment by lordzsolt** [comment]
I'm not using any Facebook library and still getting these crashes on the CI.
